// src/routes/(auth)/login/+page.svelte
<script lang="ts">
	import { goto } from '$app/navigation';
	import { page } from '$app/stores';

	let username = '';
	let password = '';
	let error = '';
	let loading = false;

	async function handleSubmit() {
		loading = true;
		error = '';
		try {
			const res = await fetch('/api/trpc/auth.login', {
				method: 'POST',
				headers: { 'Content-Type': 'application/json' },
				body: JSON.stringify({
					json: { username, password }
				})
			});
			const data = await res.json();
			if (data.error) {
				error = data.error.message || '登录失败';
			} else {
				await goto('/');
			}
		} catch (e) {
			error = '网络错误，请稍后重试';
		} finally {
			loading = false;
		}
	}
</script>

<div class="flex min-h-screen items-center justify-center bg-gray-50 py-12 px-4 sm:px-6 lg:px-8">
	<div class="w-full max-w-md space-y-8">
		<div>
			<h2 class="mt-6 text-center text-3xl font-bold tracking-tight text-gray-900">
				跑腿物品核验协同台
			</h2>
			<p class="mt-2 text-center text-sm text-gray-600">
				请登录您的账号
			</p>
		</div>

		<form class="mt-8 space-y-6" on:submit|preventDefault={handleSubmit}>
			{#if error}
				<div class="rounded-md bg-red-50 p-4">
					<div class="text-sm text-red-700">{error}</div>
				</div>
			{/if}

			<div class="space-y-4">
				<div>
					<label class="label" for="username">用户名</label>
					<input
						id="username"
						name="username"
						type="text"
						required
						class="input"
						bind:value={username}
						disabled={loading}
					/>
				</div>

				<div>
					<label class="label" for="password">密码</label>
					<input
						id="password"
						name="password"
						type="password"
						required
						class="input"
						bind:value={password}
						disabled={loading}
					/>
				</div>
			</div>

			<div>
				<button type="submit" class="btn-primary w-full" disabled={loading}>
					{loading ? '登录中...' : '登录'}
				</button>
			</div>

			<div class="text-center text-sm text-gray-600">
				还没有账号？
				<a href="/register" class="font-medium text-indigo-600 hover:text-indigo-500">
					立即注册
				</a>
			</div>
		</form>
	</div>
</div>

// frontend/src/routes/login.tsx
import { createFileRoute, useNavigate } from '@tanstack/react-router'
import { useState } from 'react'
import api from '@/lib/api'
import { useAuth } from '@/hooks/useAuth'
import { Wrench } from 'lucide-react'

function Login() {
  const [username, setUsername] = useState('')
  const [password, setPassword] = useState('')
  const [error, setError] = useState('')
  const [loading, setLoading] = useState(false)
  const navigate = useNavigate()
  const { login } = useAuth()

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    setError('')
    setLoading(true)
    try {
      const res = await api.post('/auth/login', { username, password })
      login(res.data.access_token, res.data.user)
      navigate({ to: '/schedule' })
    } catch (err: any) {
      setError(err.response?.data?.detail || '登录失败，请检查用户名和密码')
    } finally {
      setLoading(false)
    }
  }

  return (
    <div className="min-h-screen flex items-center justify-center bg-gradient-to-br from-slate-100 to-slate-200">
      <div className="w-full max-w-md p-8 bg-white rounded-xl shadow-lg">
        <div className="text-center mb-8">
          <div className="w-16 h-16 mx-auto rounded-full bg-primary-600 flex items-center justify-center mb-4">
            <Wrench size={28} className="text-white" />
          </div>
          <h1 className="text-2xl font-bold text-slate-900">汽车维修工位排班跟进台</h1>
          <p className="text-slate-500 mt-2">请登录您的账号</p>
        </div>
        <form onSubmit={handleSubmit} className="space-y-5">
          <div>
            <label className="label">用户名</label>
            <input
              type="text"
              className="input w-full"
              value={username}
              onChange={(e) => setUsername(e.target.value)}
              placeholder="请输入用户名"
              required
            />
          </div>
          <div>
            <label className="label">密码</label>
            <input
              type="password"
              className="input w-full"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              placeholder="请输入密码"
              required
            />
          </div>
          {error && <p className="text-sm text-red-600">{error}</p>}
          <button type="submit" className="btn btn-primary w-full justify-center" disabled={loading}>
            {loading ? '登录中...' : '登录'}
          </button>
        </form>
        <div className="mt-6 text-center text-sm text-slate-500">
          <p>默认账号（请先在后端注册）</p>
        </div>
      </div>
    </div>
  )
}

export const Route = createFileRoute('/login')({
  component: Login,
})
