// apps/web/src/app/exceptions/page.tsx
'use client';

import { useEffect, useState } from 'react';
import Link from 'next/link';
import {
  Plus, AlertTriangle, Search, Filter, ChevronRight, ShieldAlert, Clock, User, Target,
  FileCheck2, BadgeCheck, ArrowUpRight,
} from 'lucide-react';
import { api } from '@/lib/api';
import { useActivityId } from '@/components/ActivitySelector';
import { fmtDateTime, STATUS_STYLES, LABELS } from '@/lib/utils';

const STATUS_FILTERS = [
  { value: '', label: '全部' },
  ...Object.entries(LABELS.ExceptionStatus).map(([k, v]) => ({ value: k, label: v })),
];
const TYPE_FILTERS = [
  { value: '', label: '全部类型' },
  ...Object.entries(LABELS.ExceptionType).map(([k, v]) => ({ value: k, label: v })),
];

const SEVERITY_STYLES: Record<string, string> = {
  LOW: 'badge bg-emerald-100 text-emerald-700',
  MEDIUM: 'badge bg-amber-100 text-amber-700',
  HIGH: 'badge bg-orange-100 text-orange-700',
  CRITICAL: 'badge bg-rose-100 text-rose-700',
};

export default function ExceptionsPage() {
  const activityId = useActivityId();
  const [data, setData] = useState<any>({ list: [], total: 0 });
  const [status, setStatus] = useState('');
  const [type, setType] = useState('');
  const [keyword, setKeyword] = useState('');
  const [page, setPage] = useState(1);
  const pageSize = 20;

  const [showForm, setShowForm] = useState(false);
  const [formData, setFormData] = useState<any>({});

  const refresh = () => {
    api.get('/exceptions', { activityId, status, type, keyword, page, pageSize }).then(setData);
  };
  useEffect(() => { refresh(); }, [activityId, status, type, keyword, page]);

  const openNew = () => {
    setFormData({ activityId, type: 'REFUND_DISPUTE', title: '', description: '', impactScope: '', severity: 'MEDIUM', liabilityParty: 'UNCLEAR' });
    setShowForm(true);
  };

  const submit = async () => {
    await api.post('/exceptions', formData);
    setShowForm(false);
    refresh();
  };

  const groupByStatus: Record<string, number> = {};
  (data.list || []).forEach((e: any) => {
    groupByStatus[e.status] = (groupByStatus[e.status] || 0) + 1;
  });

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-slate-900 flex items-center gap-2">
            <ShieldAlert className="w-7 h-7 text-rose-500" />
            异常处理台
          </h1>
          <p className="text-sm text-slate-500 mt-1">退票争议、座位冲突等异常单闭环处理，影响范围与责任归属明确记录</p>
        </div>
        <button className="btn-primary" onClick={openNew}>
          <Plus className="w-4 h-4" /> 新建异常单
        </button>
      </div>

      <div className="grid grid-cols-5 gap-4">
        {[
          { label: '全部异常', value: data.total || 0, color: 'from-slate-500 to-slate-700', icon: AlertTriangle },
          { label: '待处理', value: groupByStatus.OPEN || 0, color: 'from-rose-500 to-rose-600', icon: Target },
          { label: '处理中', value: (groupByStatus.INVESTIGATING || 0) + (groupByStatus.PENDING_RESPONSE || 0), color: 'from-amber-500 to-orange-600', icon: Clock },
          { label: '已解决', value: (groupByStatus.RESOLVED || 0) + (groupByStatus.CLOSED || 0), color: 'from-emerald-500 to-teal-600', icon: BadgeCheck },
          { label: '已升级', value: groupByStatus.ESCALATED || 0, color: 'from-violet-500 to-purple-600', icon: ArrowUpRight },
        ].map((k) => (
          <div key={k.label} className="card p-5">
            <div className="flex items-start justify-between">
              <div>
                <div className="text-sm text-slate-500">{k.label}</div>
                <div className="mt-2 text-2xl font-bold text-slate-900">{k.value}</div>
              </div>
              <div className={`w-10 h-10 rounded-xl bg-gradient-to-br ${k.color} text-white flex items-center justify-center`}>
                <k.icon className="w-5 h-5" />
              </div>
            </div>
          </div>
        ))}
      </div>

      <div className="card p-4 flex items-center gap-4 flex-wrap">
        <div className="relative flex-1 max-w-sm">
          <Search className="w-4 h-4 text-slate-400 absolute left-3 top-1/2 -translate-y-1/2" />
          <input
            className="input pl-9"
            placeholder="异常单号 / 标题 / 描述"
            value={keyword}
            onChange={(e) => { setKeyword(e.target.value); setPage(1); }}
          />
        </div>
        <div className="flex items-center gap-2">
          <Filter className="w-4 h-4 text-slate-500" />
          <select className="input !w-32" value={status} onChange={(e) => { setStatus(e.target.value); setPage(1); }}>
            {STATUS_FILTERS.map((f) => <option key={f.value} value={f.value}>{f.label}</option>)}
          </select>
          <select className="input !w-40" value={type} onChange={(e) => { setType(e.target.value); setPage(1); }}>
            {TYPE_FILTERS.map((f) => <option key={f.value} value={f.value}>{f.label}</option>)}
          </select>
        </div>
      </div>

      <div className="card overflow-hidden">
        <table className="table">
          <thead>
            <tr>
              <th>异常单号</th>
              <th>类型</th>
              <th>标题 / 关联</th>
              <th>严重程度</th>
              <th>责任归属</th>
              <th>处理人</th>
              <th>状态</th>
              <th>创建时间</th>
              <th className="text-right">操作</th>
            </tr>
          </thead>
          <tbody>
            {data.list?.length === 0 && <tr><td colSpan={9} className="text-center py-10 text-slate-400">暂无异常单</td></tr>}
            {data.list?.map((e: any) => (
              <tr key={e.id}>
                <td className="font-mono text-brand-600 font-semibold">{e.exceptionNo}</td>
                <td>
                  <span className="badge bg-indigo-50 text-indigo-700">
                    {LABELS.ExceptionType[e.type] || e.type}
                  </span>
                </td>
                <td>
                  <div className="font-medium text-slate-900 max-w-xs truncate">{e.title}</div>
                  {e.order && (
                    <div className="text-xs text-slate-500 mt-0.5">
                      关联订单：
                      <Link href={`/orders/${e.orderId}`} className="text-brand-600 hover:underline ml-1">
                        {e.order.orderNo}
                      </Link>
                      {e.order.customerName && <span className="text-slate-400 ml-1">({e.order.customerName})</span>}
                    </div>
                  )}
                </td>
                <td>
                  <span className={SEVERITY_STYLES[e.severity] || SEVERITY_STYLES.MEDIUM}>
                    {LABELS.Severity[e.severity] || e.severity}
                  </span>
                </td>
                <td>
                  <span className="badge bg-slate-100 text-slate-700">
                    {LABELS.LiabilityParty[e.liabilityParty] || e.liabilityParty}
                  </span>
                </td>
                <td>
                  {e.handlerName ? (
                    <div className="text-sm flex items-center gap-1">
                      <User className="w-3.5 h-3.5 text-slate-400" />
                      {e.handlerName}
                    </div>
                  ) : <span className="text-slate-400 text-xs">未分配</span>}
                </td>
                <td>
                  <span className={STATUS_STYLES[e.status]}>{LABELS.ExceptionStatus[e.status] || e.status}</span>
                </td>
                <td className="text-xs text-slate-500">{fmtDateTime(e.createdAt)}</td>
                <td className="text-right">
                  <Link href={`/exceptions/${e.id}`} className="btn-secondary !px-3 !py-1 text-xs inline-flex items-center">
                    处理 <ChevronRight className="w-3.5 h-3.5" />
                  </Link>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      {showForm && (
        <div className="fixed inset-0 bg-slate-900/50 z-50 flex items-center justify-center p-6" onClick={() => setShowForm(false)}>
          <div className="card w-full max-w-xl p-6" onClick={(e) => e.stopPropagation()}>
            <div className="flex items-center justify-between mb-4">
              <div className="text-lg font-semibold flex items-center gap-2">
                <ShieldAlert className="w-5 h-5 text-rose-500" />
                新建异常单
              </div>
              <button onClick={() => setShowForm(false)} className="text-slate-400 hover:text-slate-600 text-xl leading-none">×</button>
            </div>
            <div className="space-y-4">
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="label">异常类型</label>
                  <select className="input" value={formData.type} onChange={(e) => setFormData({ ...formData, type: e.target.value })}>
                    {Object.entries(LABELS.ExceptionType).map(([k, v]) => <option key={k} value={k}>{v}</option>)}
                  </select>
                </div>
                <div>
                  <label className="label">严重程度</label>
                  <select className="input" value={formData.severity} onChange={(e) => setFormData({ ...formData, severity: e.target.value })}>
                    {Object.entries(LABELS.Severity).map(([k, v]) => <option key={k} value={k}>{v}</option>)}
                  </select>
                </div>
              </div>
              <div>
                <label className="label">标题</label>
                <input className="input" value={formData.title || ''} onChange={(e) => setFormData({ ...formData, title: e.target.value })} placeholder="一句话概括异常" />
              </div>
              <div>
                <label className="label">详细描述</label>
                <textarea className="input min-h-[80px]" value={formData.description || ''} onChange={(e) => setFormData({ ...formData, description: e.target.value })} />
              </div>
              <div>
                <label className="label">影响范围</label>
                <textarea className="input min-h-[60px]" value={formData.impactScope || ''} onChange={(e) => setFormData({ ...formData, impactScope: e.target.value })} placeholder="涉及订单数、金额、客户数量等" />
              </div>
              <div>
                <label className="label">关联订单 ID（可选）</label>
                <input className="input" value={formData.orderId || ''} onChange={(e) => setFormData({ ...formData, orderId: e.target.value })} />
              </div>
              <div>
                <label className="label">初步责任归属</label>
                <select className="input" value={formData.liabilityParty} onChange={(e) => setFormData({ ...formData, liabilityParty: e.target.value })}>
                  {Object.entries(LABELS.LiabilityParty).map(([k, v]) => <option key={k} value={k}>{v}</option>)}
                </select>
              </div>
            </div>
            <div className="flex justify-end gap-2 mt-6">
              <button className="btn-secondary" onClick={() => setShowForm(false)}>取消</button>
              <button className="btn-primary" onClick={submit}>提交</button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

// src/routes/exceptions/+page.svelte
<script lang="ts">
  import { trpc } from '$lib/trpc/client';
  import { onMount } from 'svelte';
  import { page } from '$app/stores';
  import { goto } from '$app/navigation';

  let exceptions: any[] = [];
  let total = 0;
  let pageNum = 1;
  let pageSize = 20;
  let totalPages = 0;
  let status = '';
  let severity = '';
  let responsibility = '';
  let loading = true;
  let showNewModal = false;
  let showDetailModal = false;
  let selectedException: any = null;
  let resolveResult = '';
  let showResolveModal = false;

  let newException = {
    patientId: '',
    title: '',
    description: '',
    severity: 'medium' as const,
    impactScope: '',
    responsibility: 'patient' as const,
    responsiblePerson: ''
  };

  $: {
    if ($page.url.searchParams.get('new') === 'true') {
      showNewModal = true;
    }
  }

  async function loadExceptions() {
    loading = true;
    try {
      const result: any = await trpc.exceptionOrder.list.query({
        page: pageNum,
        pageSize,
        status: status || undefined,
        severity: severity || undefined,
        responsibility: responsibility || undefined
      });
      exceptions = result.items;
      total = result.total;
      totalPages = result.totalPages;
    } finally {
      loading = false;
    }
  }

  async function handleSearch() {
    pageNum = 1;
    loadExceptions();
  }

  async function handleCreateException(e: Event) {
    e.preventDefault();
    try {
      await trpc.exceptionOrder.create.mutate({
        ...newException
      });
      showNewModal = false;
      newException = {
        patientId: '',
        title: '',
        description: '',
        severity: 'medium',
        impactScope: '',
        responsibility: 'patient',
        responsiblePerson: ''
      };
      loadExceptions();
      goto('/exceptions');
    } catch (err: any) {
      alert(err.message);
    }
  }

  async function viewDetail(id: string) {
    selectedException = await trpc.exceptionOrder.get.query({ id });
    showDetailModal = true;
  }

  function openResolveModal() {
    resolveResult = '';
    showResolveModal = true;
    showDetailModal = false;
  }

  async function handleResolve() {
    if (!selectedException || !resolveResult) return;
    await trpc.exceptionOrder.resolve.mutate({
      id: selectedException.id,
      handlingResult: resolveResult
    });
    showResolveModal = false;
    resolveResult = '';
    loadExceptions();
  }

  async function closeException(id: string) {
    if (confirm('确定关闭此异常单？')) {
      await trpc.exceptionOrder.close.mutate({ id });
      loadExceptions();
    }
  }

  const severityLabel = (s: string) => {
    const map: Record<string, string> = {
      low: '低',
      medium: '中',
      high: '高',
      critical: '严重'
    };
    return map[s] || s;
  };

  const severityClass = (s: string) => {
    const map: Record<string, string> = {
      low: 'badge-info',
      medium: 'badge-warning',
      high: 'badge-danger',
      critical: 'badge-danger'
    };
    return map[s] || 'badge-gray';
  };

  const statusLabel = (s: string) => {
    const map: Record<string, string> = {
      open: '待处理',
      investigating: '调查中',
      resolved: '已解决',
      closed: '已关闭'
    };
    return map[s] || s;
  };

  const statusClass = (s: string) => {
    const map: Record<string, string> = {
      open: 'badge-danger',
      investigating: 'badge-warning',
      resolved: 'badge-success',
      closed: 'badge-gray'
    };
    return map[s] || 'badge-gray';
  };

  const responsibilityLabel = (r: string) => {
    const map: Record<string, string> = {
      patient: '患者责任',
      clinic: '诊所责任',
      doctor: '医生责任',
      system: '系统问题',
      other: '其他'
    };
    return map[r] || r;
  };

  function closeModal() {
    showNewModal = false;
    goto('/exceptions');
  }

  $: if (pageNum) {
    loadExceptions();
  }

  onMount(() => {
    loadExceptions();
  });
</script>

<div class="p-8">
  <div class="flex items-center justify-between mb-6">
    <div>
      <h1 class="text-2xl font-bold text-gray-900">异常单管理</h1>
      <p class="mt-1 text-gray-500">处理爽约等异常情况，记录影响范围和责任归属</p>
    </div>
    <button class="btn-primary" on:click={() => (showNewModal = true)}>
      ➕ 上报异常
    </button>
  </div>

  <div class="card mb-6">
    <div class="card-body">
      <div class="flex gap-4 items-end flex-wrap">
        <div class="w-40">
          <label class="label">状态</label>
          <select bind:value={status} class="input-field" on:change={handleSearch}>
            <option value="">全部状态</option>
            <option value="open">待处理</option>
            <option value="investigating">调查中</option>
            <option value="resolved">已解决</option>
            <option value="closed">已关闭</option>
          </select>
        </div>
        <div class="w-40">
          <label class="label">严重程度</label>
          <select bind:value={severity} class="input-field" on:change={handleSearch}>
            <option value="">全部</option>
            <option value="low">低</option>
            <option value="medium">中</option>
            <option value="high">高</option>
            <option value="critical">严重</option>
          </select>
        </div>
        <div class="w-40">
          <label class="label">责任归属</label>
          <select bind:value={responsibility} class="input-field" on:change={handleSearch}>
            <option value="">全部</option>
            <option value="patient">患者责任</option>
            <option value="clinic">诊所责任</option>
            <option value="doctor">医生责任</option>
            <option value="system">系统问题</option>
            <option value="other">其他</option>
          </select>
        </div>
        <button class="btn-secondary" on:click={handleSearch}>查询</button>
      </div>
    </div>
  </div>

  <div class="card">
    <div class="overflow-x-auto">
      <table class="w-full">
        <thead class="bg-gray-50">
          <tr>
            <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">标题</th>
            <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">严重程度</th>
            <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">状态</th>
            <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">责任归属</th>
            <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">创建时间</th>
            <th class="px-6 py-3 text-right text-xs font-medium text-gray-500 uppercase tracking-wider">操作</th>
          </tr>
        </thead>
        <tbody class="divide-y divide-gray-200">
          {#if loading}
            <tr>
              <td colspan="6" class="px-6 py-12 text-center text-gray-500">加载中...</td>
            </tr>
          {:else if exceptions.length === 0}
            <tr>
              <td colspan="6" class="px-6 py-12 text-center text-gray-500">暂无异常单</td>
            </tr>
          {:else}
            {#each exceptions as exc}
              <tr class="hover:bg-gray-50">
                <td class="px-6 py-4">
                  <p class="text-sm font-medium text-gray-900">{exc.title}</p>
                  {#if exc.description}
                    <p class="text-sm text-gray-500 mt-1 truncate max-w-md">{exc.description}</p>
                  {/if}
                </td>
                <td class="px-6 py-4 whitespace-nowrap">
                  <span class={`badge ${severityClass(exc.severity)}`}>
                    {severityLabel(exc.severity)}
                  </span>
                </td>
                <td class="px-6 py-4 whitespace-nowrap">
                  <span class={`badge ${statusClass(exc.status)}`}>
                    {statusLabel(exc.status)}
                  </span>
                </td>
                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                  {exc.responsibility ? responsibilityLabel(exc.responsibility) : '-'}
                </td>
                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                  {new Date(exc.createdAt).toLocaleString()}
                </td>
                <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                  <button
                    class="text-dental-600 hover:text-dental-900"
                    on:click={() => viewDetail(exc.id)}
                  >
                    详情
                  </button>
                </td>
              </tr>
            {/each}
          {/if}
        </tbody>
      </table>
    </div>

    {#if totalPages > 1}
      <div class="px-6 py-4 border-t border-gray-100 flex items-center justify-between">
        <div class="text-sm text-gray-500">
          共 {total} 条，第 {pageNum} / {totalPages} 页
        </div>
        <div class="flex gap-2">
          <button
            class="btn-secondary text-sm"
            disabled={pageNum <= 1}
            on:click={() => (pageNum--)}
          >
            上一页
          </button>
          <button
            class="btn-secondary text-sm"
            disabled={pageNum >= totalPages}
            on:click={() => (pageNum++)}
          >
            下一页
          </button>
        </div>
      </div>
    {/if}
  </div>
</div>

{#if showNewModal}
  <div class="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
    <div class="bg-white rounded-xl w-full max-w-lg max-h-[90vh] overflow-y-auto">
      <div class="p-6 border-b border-gray-100">
        <div class="flex items-center justify-between">
          <h2 class="text-lg font-semibold text-gray-900">上报异常</h2>
          <button class="text-gray-400 hover:text-gray-600" on:click={closeModal}>✕</button>
        </div>
      </div>
      <form on:submit={handleCreateException} class="p-6 space-y-4">
        <div>
          <label class="label">患者ID *</label>
          <input type="text" bind:value={newException.patientId} class="input-field" required placeholder="请输入患者UUID" />
        </div>
        <div>
          <label class="label">标题 *</label>
          <input type="text" bind:value={newException.title} class="input-field" required />
        </div>
        <div class="grid grid-cols-2 gap-4">
          <div>
            <label class="label">严重程度</label>
            <select bind:value={newException.severity} class="input-field">
              <option value="low">低</option>
              <option value="medium">中</option>
              <option value="high">高</option>
              <option value="critical">严重</option>
            </select>
          </div>
          <div>
            <label class="label">责任归属</label>
            <select bind:value={newException.responsibility} class="input-field">
              <option value="patient">患者责任</option>
              <option value="clinic">诊所责任</option>
              <option value="doctor">医生责任</option>
              <option value="system">系统问题</option>
              <option value="other">其他</option>
            </select>
          </div>
        </div>
        <div>
          <label class="label">描述</label>
          <textarea bind:value={newException.description} class="input-field" rows="3"></textarea>
        </div>
        <div>
          <label class="label">影响范围</label>
          <textarea bind:value={newException.impactScope} class="input-field" rows="2"></textarea>
        </div>
        <div>
          <label class="label">责任人</label>
          <input type="text" bind:value={newException.responsiblePerson} class="input-field" />
        </div>
        <div class="flex justify-end gap-3 pt-4">
          <button type="button" class="btn-secondary" on:click={closeModal}>取消</button>
          <button type="submit" class="btn-primary">提交</button>
        </div>
      </form>
    </div>
  </div>
{/if}

{#if showDetailModal && selectedException}
  <div class="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
    <div class="bg-white rounded-xl w-full max-w-xl max-h-[90vh] overflow-y-auto">
      <div class="p-6 border-b border-gray-100">
        <div class="flex items-center justify-between">
          <h2 class="text-lg font-semibold text-gray-900">异常单详情</h2>
          <button class="text-gray-400 hover:text-gray-600" on:click={() => (showDetailModal = false)}>✕</button>
        </div>
      </div>
      <div class="p-6 space-y-4">
        <div>
          <p class="text-sm text-gray-500 mb-1">标题</p>
          <p class="font-medium text-gray-900">{selectedException.title}</p>
        </div>
        <div class="grid grid-cols-3 gap-4">
          <div>
            <p class="text-sm text-gray-500 mb-1">严重程度</p>
            <span class={`badge ${severityClass(selectedException.severity)}`}>
              {severityLabel(selectedException.severity)}
            </span>
          </div>
          <div>
            <p class="text-sm text-gray-500 mb-1">状态</p>
            <span class={`badge ${statusClass(selectedException.status)}`}>
              {statusLabel(selectedException.status)}
            </span>
          </div>
          <div>
            <p class="text-sm text-gray-500 mb-1">责任归属</p>
            <span class="text-sm text-gray-900">
              {selectedException.responsibility ? responsibilityLabel(selectedException.responsibility) : '-'}
            </span>
          </div>
        </div>
        {#if selectedException.description}
          <div>
            <p class="text-sm text-gray-500 mb-1">描述</p>
            <p class="text-sm text-gray-700">{selectedException.description}</p>
          </div>
        {/if}
        {#if selectedException.impactScope}
          <div>
            <p class="text-sm text-gray-500 mb-1">影响范围</p>
            <p class="text-sm text-gray-700">{selectedException.impactScope}</p>
          </div>
        {/if}
        {#if selectedException.handlingResult}
          <div>
            <p class="text-sm text-gray-500 mb-1">处理结果</p>
            <p class="text-sm text-gray-700 bg-green-50 p-3 rounded-lg">{selectedException.handlingResult}</p>
          </div>
        {/if}
        {#if selectedException.responsiblePerson}
          <div>
            <p class="text-sm text-gray-500 mb-1">责任人</p>
            <p class="text-sm text-gray-900">{selectedException.responsiblePerson}</p>
          </div>
        {/if}
        <div class="flex justify-between text-xs text-gray-400 pt-2 border-t">
          <span>创建时间：{new Date(selectedException.createdAt).toLocaleString()}</span>
          {#if selectedException.closedAt}
            <span>关闭时间：{new Date(selectedException.closedAt).toLocaleString()}</span>
          {/if}
        </div>
        <div class="flex justify-end gap-3 pt-4 border-t">
          {#if selectedException.status !== 'resolved' && selectedException.status !== 'closed'}
            <button class="btn-primary" on:click={openResolveModal}>
              处理解决
            </button>
          {/if}
          {#if selectedException.status === 'resolved' && selectedException.status !== 'closed'}
            <button
              class="btn-secondary"
              on:click={() => closeException(selectedException.id)}
            >
              关闭
            </button>
          {/if}
        </div>
      </div>
    </div>
  </div>
{/if}

{#if showResolveModal}
  <div class="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
    <div class="bg-white rounded-xl w-full max-w-md">
      <div class="p-6 border-b border-gray-100">
        <div class="flex items-center justify-between">
          <h2 class="text-lg font-semibold text-gray-900">处理异常</h2>
          <button class="text-gray-400 hover:text-gray-600" on:click={() => (showResolveModal = false)}>✕</button>
        </div>
      </div>
      <div class="p-6 space-y-4">
        <div>
          <label class="label">处理结果 *</label>
          <textarea bind:value={resolveResult} class="input-field" rows="4" placeholder="请详细描述处理过程和结果"></textarea>
        </div>
        <div class="flex justify-end gap-3">
          <button class="btn-secondary" on:click={() => (showResolveModal = false)}>取消</button>
          <button class="btn-primary" on:click={handleResolve}>提交</button>
        </div>
      </div>
    </div>
  </div>
{/if}
