// frontend/src/routes/complaints/index.tsx
import { useState, useEffect, useCallback } from 'react'
import { createFileRoute, useNavigate, useSearch } from '@tanstack/react-router'
import { Plus, Search, ChevronLeft, ChevronRight } from 'lucide-react'
import { api } from '@/api/client'
import StatusBadge from '@/components/StatusBadge'
import ComplaintFormModal from '@/components/ComplaintFormModal'
import { STATUS_LABELS, PRIORITY_LABELS, PRIORITY_COLORS } from '@/types'
import type { ComplaintListItem, ComplaintStatus, Priority, SourceChannel } from '@/types'

const PAGE_SIZE = 10

export const Route = createFileRoute('/complaints/')({
  component: ComplaintsPage,
})

function ComplaintsPage() {
  const navigate = useNavigate()
  const search = useSearch({ strict: false }) as Record<string, string>
  const [complaints, setComplaints] = useState<ComplaintListItem[]>([])
  const [loading, setLoading] = useState(true)
  const [showModal, setShowModal] = useState(false)

  const [statusFilter, setStatusFilter] = useState(search.status || '')
  const [channelFilter, setChannelFilter] = useState(search.channel || '')
  const [priorityFilter, setPriorityFilter] = useState(search.priority || '')
  const [searchQuery, setSearchQuery] = useState(search.q || '')
  const [page, setPage] = useState(Number(search.page) || 1)

  const fetchComplaints = useCallback(async () => {
    setLoading(true)
    try {
      const params: Record<string, string> = {}
      if (statusFilter) params.status = statusFilter
      if (channelFilter) params.source_channel = channelFilter
      if (priorityFilter) params.priority = priorityFilter
      if (searchQuery) params.q = searchQuery
      const data = await api.complaints.list(params)
      setComplaints(data)
    } catch {
      setComplaints([])
    } finally {
      setLoading(false)
    }
  }, [statusFilter, channelFilter, priorityFilter, searchQuery])

  useEffect(() => {
    fetchComplaints()
  }, [fetchComplaints])

  useEffect(() => {
    const params: Record<string, string> = {}
    if (statusFilter) params.status = statusFilter
    if (channelFilter) params.channel = channelFilter
    if (priorityFilter) params.priority = priorityFilter
    if (searchQuery) params.q = searchQuery
    if (page > 1) params.page = String(page)
    navigate({ to: '/complaints', search: params, replace: true })
  }, [statusFilter, channelFilter, priorityFilter, searchQuery, page, navigate])

  const filtered = complaints
  const totalPages = Math.max(1, Math.ceil(filtered.length / PAGE_SIZE))
  const paged = filtered.slice((page - 1) * PAGE_SIZE, page * PAGE_SIZE)

  const goToDetail = (id: string) => {
    navigate({ to: '/complaints/$complaintId', params: { complaintId: id } })
  }

  return (
    <div>
      <div className="flex items-center justify-between mb-4">
        <h2 className="text-xl font-semibold text-slate-800">客诉列表</h2>
        <button
          onClick={() => setShowModal(true)}
          className="flex items-center gap-1.5 px-4 py-2 text-sm font-medium text-white bg-blue-600 rounded-md hover:bg-blue-700"
        >
          <Plus className="w-4 h-4" />
          新建客诉
        </button>
      </div>

      <div className="bg-white rounded-lg border border-slate-200 mb-4">
        <div className="flex flex-wrap items-center gap-3 px-4 py-3">
          <select
            value={statusFilter}
            onChange={e => { setStatusFilter(e.target.value); setPage(1) }}
            className="border border-slate-300 rounded-md px-3 py-1.5 text-sm focus:outline-none focus:ring-1 focus:ring-blue-500"
          >
            <option value="">全部状态</option>
            {(Object.entries(STATUS_LABELS) as [ComplaintStatus, string][]).map(([k, v]) => (
              <option key={k} value={k}>{v}</option>
            ))}
          </select>
          <select
            value={channelFilter}
            onChange={e => { setChannelFilter(e.target.value); setPage(1) }}
            className="border border-slate-300 rounded-md px-3 py-1.5 text-sm focus:outline-none focus:ring-1 focus:ring-blue-500"
          >
            <option value="">全部渠道</option>
            {(['电话', '微信', '平台', '现场'] as SourceChannel[]).map(c => (
              <option key={c} value={c}>{c}</option>
            ))}
          </select>
          <select
            value={priorityFilter}
            onChange={e => { setPriorityFilter(e.target.value); setPage(1) }}
            className="border border-slate-300 rounded-md px-3 py-1.5 text-sm focus:outline-none focus:ring-1 focus:ring-blue-500"
          >
            <option value="">全部优先级</option>
            {(Object.entries(PRIORITY_LABELS) as [Priority, string][]).map(([k, v]) => (
              <option key={k} value={k}>{v}</option>
            ))}
          </select>
          <div className="relative flex-1 min-w-[200px]">
            <Search className="absolute left-2.5 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400" />
            <input
              type="text"
              placeholder="搜索标题、民宿名..."
              value={searchQuery}
              onChange={e => { setSearchQuery(e.target.value); setPage(1) }}
              className="w-full pl-8 pr-3 py-1.5 border border-slate-300 rounded-md text-sm focus:outline-none focus:ring-1 focus:ring-blue-500"
            />
          </div>
        </div>
      </div>

      <div className="bg-white rounded-lg border border-slate-200 overflow-hidden">
        <div className="overflow-x-auto">
          <table className="w-full">
            <thead>
              <tr className="border-b border-slate-200">
                <th className="px-4 py-3 text-xs">编号</th>
                <th className="px-4 py-3 text-xs">标题</th>
                <th className="px-4 py-3 text-xs">状态</th>
                <th className="px-4 py-3 text-xs">优先级</th>
                <th className="px-4 py-3 text-xs">来源渠道</th>
                <th className="px-4 py-3 text-xs">民宿名</th>
                <th className="px-4 py-3 text-xs">处理人</th>
                <th className="px-4 py-3 text-xs">创建时间</th>
                <th className="px-4 py-3 text-xs">标签</th>
              </tr>
            </thead>
            <tbody>
              {loading ? (
                <tr>
                  <td colSpan={9} className="px-4 py-8 text-center text-sm text-slate-400">加载中...</td>
                </tr>
              ) : paged.length === 0 ? (
                <tr>
                  <td colSpan={9} className="px-4 py-8 text-center text-sm text-slate-400">暂无数据</td>
                </tr>
              ) : (
                paged.map(c => (
                  <tr
                    key={c.id}
                    onClick={() => goToDetail(c.id)}
                    className={`border-b border-slate-100 cursor-pointer hover:bg-slate-50 transition-colors ${c.status === 'closed' ? 'opacity-60' : ''}`}
                  >
                    <td className="px-4 py-3 text-sm text-slate-500 font-mono">{c.id.slice(0, 8)}</td>
                    <td className="px-4 py-3 text-sm text-slate-800 font-medium max-w-[200px] truncate">{c.title}</td>
                    <td className="px-4 py-3"><StatusBadge status={c.status} /></td>
                    <td className="px-4 py-3">
                      <span className={`inline-flex items-center px-2 py-0.5 rounded-full text-xs font-medium ${PRIORITY_COLORS[c.priority]}`}>
                        {PRIORITY_LABELS[c.priority]}
                      </span>
                    </td>
                    <td className="px-4 py-3 text-sm text-slate-600">{c.source_channel}</td>
                    <td className="px-4 py-3 text-sm text-slate-600">{c.homestay_name}</td>
                    <td className="px-4 py-3 text-sm text-slate-600">{c.handler_name || '-'}</td>
                    <td className="px-4 py-3 text-sm text-slate-500">{c.created_at.slice(0, 10)}</td>
                    <td className="px-4 py-3">
                      <div className="flex flex-wrap gap-1">
                        {c.tags.slice(0, 2).map((tag, i) => (
                          <span key={i} className="inline-flex items-center px-1.5 py-0.5 rounded text-xs bg-slate-100 text-slate-600">{tag}</span>
                        ))}
                        {c.tags.length > 2 && (
                          <span className="text-xs text-slate-400">+{c.tags.length - 2}</span>
                        )}
                      </div>
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>

        {totalPages > 1 && (
          <div className="flex items-center justify-between px-4 py-3 border-t border-slate-200">
            <span className="text-sm text-slate-500">
              共 {filtered.length} 条，第 {page}/{totalPages} 页
            </span>
            <div className="flex items-center gap-1">
              <button
                onClick={() => setPage(p => Math.max(1, p - 1))}
                disabled={page <= 1}
                className="p-1.5 rounded-md hover:bg-slate-100 disabled:opacity-30 disabled:cursor-not-allowed"
              >
                <ChevronLeft className="w-4 h-4" />
              </button>
              <button
                onClick={() => setPage(p => Math.min(totalPages, p + 1))}
                disabled={page >= totalPages}
                className="p-1.5 rounded-md hover:bg-slate-100 disabled:opacity-30 disabled:cursor-not-allowed"
              >
                <ChevronRight className="w-4 h-4" />
              </button>
            </div>
          </div>
        )}
      </div>

      <ComplaintFormModal
        open={showModal}
        onClose={() => setShowModal(false)}
        onSuccess={fetchComplaints}
      />
    </div>
  )
}

// src/routes/(app)/complaints/+page.svelte
<script lang="ts">
	import { goto } from '$app/navigation';
	import { STATUS_LABELS, STATUS_COLORS } from '$lib/utils/permissions';
	import type { PageData } from './$types';

	interface ComplaintItem {
		id: string;
		description: string;
		status: string;
		deadline: Date | string | null;
		createdAt: Date | string;
		tags?: { id: string; code: string; label: string; category: string }[];
		assigneeName?: string | null;
		visitorName?: string | null;
		visitorPhone?: string | null;
		assigneePhone?: string | null;
		isOverdue: boolean;
		[key: string]: any;
	}

	let { data }: { data: PageData & { complaints: { items: ComplaintItem[]; total: number; page: number; pageSize: number } } } = $props();

	const statusOptions = [
		{ value: '', label: '全部' },
		{ value: 'pending', label: '待处理' },
		{ value: 'assigned', label: '已分配' },
		{ value: 'in_progress', label: '处理中' },
		{ value: 'escalated', label: '已升级' },
		{ value: 'resolved', label: '已解决' },
		{ value: 'closed', label: '已关闭' },
		{ value: 'rejected', label: '已驳回' },
		{ value: 'resubmitted', label: '已重提' }
	];

	function updateFilter(key: string, value: string) {
		const params = new URLSearchParams();
		if (key === 'status' && value) params.set('status', value);
		else if (data.filters.status) params.set('status', data.filters.status);

		if (key === 'tagCode' && value) params.set('tagCode', value);
		else if (data.filters.tagCode && key !== 'tagCode') params.set('tagCode', data.filters.tagCode);

		if (key === 'assigneeId' && value) params.set('assigneeId', value);
		else if (data.filters.assigneeId && key !== 'assigneeId') params.set('assigneeId', data.filters.assigneeId);

		const currentPage = key === 'page' ? parseInt(value) : 1;
		if (currentPage > 1) params.set('page', String(currentPage));

		goto(`/complaints?${params.toString()}`);
	}

	function clearFilters() {
		goto('/complaints');
	}

	function truncate(str: string, len: number): string {
		if (!str) return '';
		if (str.length <= len) return str;
		return str.slice(0, len) + '…';
	}

	function formatDate(date: string | Date | null): string {
		if (!date) return '-';
		return new Date(date).toLocaleDateString('zh-CN', { month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit' });
	}

	const totalPages = $derived(Math.ceil(data.complaints.total / data.complaints.pageSize));
	const hasFilters = $derived(!!(data.filters.status || data.filters.tagCode || data.filters.assigneeId));
</script>

<svelte:head>
	<title>投诉列表 - 景区投诉协同台</title>
</svelte:head>

<div class="space-y-4">
	<div class="flex items-center justify-between">
		<h1 class="text-2xl font-bold text-slate-800">投诉列表</h1>
		<a
			href="/complaints/new"
			class="inline-flex items-center gap-2 px-4 py-2 bg-primary-600 text-white text-sm font-medium rounded-lg hover:bg-primary-700 transition"
		>
			<svg xmlns="http://www.w3.org/2000/svg" class="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
				<path stroke-linecap="round" stroke-linejoin="round" d="M12 4v16m8-8H4" />
			</svg>
			创建投诉
		</a>
	</div>

	<div class="bg-white rounded-xl shadow-sm border border-slate-200 p-4">
		<div class="flex flex-wrap items-center gap-3">
			<select
				class="border border-slate-300 rounded-lg px-3 py-2 text-sm bg-white text-slate-700 focus:outline-none focus:ring-2 focus:ring-primary-500 focus:border-primary-500"
				value={data.filters.status ?? ''}
				onchange={(e) => updateFilter('status', (e.target as HTMLSelectElement).value)}
			>
				{#each statusOptions as opt}
					<option value={opt.value}>{opt.label}</option>
				{/each}
			</select>

			<select
				class="border border-slate-300 rounded-lg px-3 py-2 text-sm bg-white text-slate-700 focus:outline-none focus:ring-2 focus:ring-primary-500 focus:border-primary-500"
				value={data.filters.tagCode ?? ''}
				onchange={(e) => updateFilter('tagCode', (e.target as HTMLSelectElement).value)}
			>
				<option value="">全部标签</option>
				{#each data.tags as tag}
					<option value={tag.code}>{tag.label}</option>
				{/each}
			</select>

			<select
				class="border border-slate-300 rounded-lg px-3 py-2 text-sm bg-white text-slate-700 focus:outline-none focus:ring-2 focus:ring-primary-500 focus:border-primary-500"
				value={data.filters.assigneeId ?? ''}
				onchange={(e) => updateFilter('assigneeId', (e.target as HTMLSelectElement).value)}
			>
				<option value="">全部处理人</option>
				{#each data.staff as s}
					<option value={s.id}>{s.displayName}</option>
				{/each}
			</select>

			{#if hasFilters}
				<button
					onclick={clearFilters}
					class="text-sm text-slate-500 hover:text-slate-700 underline transition"
				>
					清除筛选
				</button>
			{/if}

			<span class="ml-auto text-sm text-slate-500">共 {data.complaints.total} 条</span>
		</div>
	</div>

	<div class="bg-white rounded-xl shadow-sm border border-slate-200 overflow-hidden">
		{#if data.complaints.items.length === 0}
			<div class="text-center py-12 text-slate-400 text-sm">暂无投诉记录</div>
		{:else}
			<div class="overflow-x-auto">
				<table class="w-full text-sm">
					<thead>
						<tr class="bg-slate-50 border-b border-slate-200">
							<th class="text-left px-4 py-3 text-slate-600 font-semibold">编号</th>
							<th class="text-left px-4 py-3 text-slate-600 font-semibold">描述</th>
							<th class="text-left px-4 py-3 text-slate-600 font-semibold">状态</th>
							<th class="text-left px-4 py-3 text-slate-600 font-semibold">标签</th>
							<th class="text-left px-4 py-3 text-slate-600 font-semibold">处理人</th>
							<th class="text-left px-4 py-3 text-slate-600 font-semibold">截止时间</th>
							<th class="text-left px-4 py-3 text-slate-600 font-semibold">创建时间</th>
						</tr>
					</thead>
					<tbody>
						{#each data.complaints.items as item}
							<tr
								class="border-b border-slate-100 hover:bg-slate-50 transition cursor-pointer"
								onclick={() => goto(`/complaints/${item.id}`)}
							>
								<td class="px-4 py-3 font-mono text-xs text-slate-500">{item.id.slice(0, 8)}</td>
								<td class="px-4 py-3 text-slate-700 max-w-xs">
									<a href="/complaints/{item.id}" class="hover:text-primary-600 transition">{truncate(item.description, 40)}</a>
								</td>
								<td class="px-4 py-3">
									<span class="inline-block px-2 py-0.5 rounded-full text-xs font-medium {STATUS_COLORS[item.status] ?? 'bg-gray-100 text-gray-700'}">
										{STATUS_LABELS[item.status] ?? item.status}
									</span>
								</td>
								<td class="px-4 py-3">
									<div class="flex flex-wrap gap-1">
										{#each (item.tags ?? []) as tag}
											<span class="inline-block px-1.5 py-0.5 rounded text-xs bg-slate-100 text-slate-600">{tag.label}</span>
										{/each}
									</div>
								</td>
								<td class="px-4 py-3 text-slate-600">{item.assigneeName ?? '-'}</td>
								<td class="px-4 py-3 text-slate-600">{formatDate(item.deadline)}</td>
								<td class="px-4 py-3 text-slate-500">{formatDate(item.createdAt)}</td>
							</tr>
						{/each}
					</tbody>
				</table>
			</div>

			{#if totalPages > 1}
				<div class="flex items-center justify-between px-4 py-3 border-t border-slate-200">
					<button
						onclick={() => updateFilter('page', String(data.complaints.page - 1))}
						disabled={data.complaints.page <= 1}
						class="px-3 py-1.5 text-sm rounded-lg border border-slate-300 text-slate-600 hover:bg-slate-50 transition disabled:opacity-40 disabled:cursor-not-allowed"
					>
						上一页
					</button>
					<div class="flex items-center gap-1">
						{#each Array.from({ length: totalPages }, (_, i) => i + 1) as p}
							{#if p === data.complaints.page}
								<span class="px-3 py-1.5 text-sm rounded-lg bg-primary-600 text-white font-medium">{p}</span>
							{:else}
								<button
									onclick={() => updateFilter('page', String(p))}
									class="px-3 py-1.5 text-sm rounded-lg border border-slate-300 text-slate-600 hover:bg-slate-50 transition"
								>
									{p}
								</button>
							{/if}
						{/each}
					</div>
					<button
						onclick={() => updateFilter('page', String(data.complaints.page + 1))}
						disabled={data.complaints.page >= totalPages}
						class="px-3 py-1.5 text-sm rounded-lg border border-slate-300 text-slate-600 hover:bg-slate-50 transition disabled:opacity-40 disabled:cursor-not-allowed"
					>
						下一页
					</button>
				</div>
			{/if}
		{/if}
	</div>
</div>
