// src/routes/(app)/cleaning/+page.svelte
<script lang="ts">
	import { trpcClient } from '$lib/trpc/client';
	import { onMount } from 'svelte';
	import { CLEANING_STATUS_LABELS, type CleaningStatusType } from '$lib/types';

	let tasks: any[] = [];
	let properties: any[] = [];
	let users: any[] = [];
	let loading = true;
	let filterStatus = '' as CleaningStatusType | '';
	let showModal = false;

	let newTask = {
		propertyId: '', orderId: undefined as string | undefined,
		type: 'checkout' as any, priority: 'medium' as any,
		scheduledDateStr: new Date().toISOString().split('T')[0],
		scheduledTime: '', assignedTo: '' as string, fee: 0
	};

	async function loadData() {
		loading = true;
		try {
			const [t, p, u] = await Promise.all([
				trpcClient.cleaning.list.query({ status: filterStatus || undefined }),
				trpcClient.property.list.query({ status: 'active' }),
				trpcClient.auth.list.query()
			]);
			tasks = t; properties = p; users = u;
			if (p.length > 0 && !newTask.propertyId) newTask.propertyId = p[0].id;
		} finally { loading = false; }
	}
	onMount(loadData);

	async function onCreate() {
		showModal = true;
	}
	async function submitCreate() {
		await trpcClient.cleaning.create.mutate({
			...newTask,
			scheduledDate: new Date(newTask.scheduledDateStr + 'T00:00:00'),
			assignedTo: newTask.assignedTo || undefined
		});
		showModal = false;
		loadData();
	}
	async function updateStatus(t: any, s: CleaningStatusType) {
		await trpcClient.cleaning.updateStatus.mutate({ id: t.id, status: s });
		loadData();
	}
	async function autoGenerate() {
		await trpcClient.cleaning.autoCreateFromCheckout.mutate({});
		loadData();
	}

	const statusBadge: Record<string, string> = {
		pending: 'bg-yellow-100 text-yellow-800',
		in_progress: 'bg-blue-100 text-blue-800',
		completed: 'bg-green-100 text-green-800',
		cancelled: 'bg-gray-100 text-gray-800',
		rejected: 'bg-red-100 text-red-800'
	};
	const priorityBadge: Record<string, string> = {
		low: 'bg-gray-100 text-gray-700',
		medium: 'bg-blue-100 text-blue-700',
		high: 'bg-orange-100 text-orange-700',
		urgent: 'bg-red-100 text-red-700'
	};
	const typeLabels: Record<string, string> = {
		checkout: '退房清洁', periodic: '定期保洁', deep: '深度清洁', maintenance: '维护', other: '其他'
	};
	const propMap = new Map(properties.map((p) => [p.id, p.name]));
	const userMap = new Map(users.map((u) => [u.id, u.username]));

	function formatDate(d: any) {
		if (!d) return '-';
		return new Date(d).toLocaleDateString('zh-CN');
	}

	function cleaningStatusLabel(s: any) { return (CLEANING_STATUS_LABELS as any)[s]; }
</script>

<div class="space-y-6">
	<div class="flex flex-wrap items-center justify-between gap-3">
		<div class="flex items-center gap-3">
			<select bind:value={filterStatus} class="select w-40" on:change={loadData}>
				<option value="">全部状态</option>
				{#each Object.entries(CLEANING_STATUS_LABELS) as [k, v]}<option value={k}>{v}</option>{/each}
			</select>
			<div class="text-sm text-gray-500">共 {tasks.length} 条</div>
		</div>
		<div class="flex gap-2">
			<button on:click={autoGenerate} class="btn-secondary">
				<svg class="h-4 w-4 mr-1.5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15"></path></svg>
				根据退房自动生成
			</button>
			<button on:click={onCreate} class="btn-primary">新增任务</button>
		</div>
	</div>

	{#if loading}
		<div class="card card-body py-12 text-center text-gray-500">加载中...</div>
	{:else}
		<div class="card overflow-hidden">
			<table class="table">
				<thead class="bg-gray-50">
					<tr>
						<th class="table-th">任务号</th>
						<th class="table-th">类型/优先级</th>
						<th class="table-th">房源</th>
						<th class="table-th">计划时间</th>
						<th class="table-th">指派人员</th>
						<th class="table-th">费用</th>
						<th class="table-th">状态</th>
						<th class="table-th">操作</th>
					</tr>
				</thead>
				<tbody class="divide-y divide-gray-200">
					{#if tasks.length === 0}
						<tr><td colspan="8" class="py-16 text-center text-gray-400">暂无保洁任务</td></tr>
					{/if}
					{#each tasks as t}
						<tr class="hover:bg-gray-50">
							<td class="table-td font-mono text-xs">{t.taskNo}</td>
							<td class="table-td">
								<div class="flex flex-col gap-1">
									<span class="badge bg-indigo-50 text-indigo-700 w-fit">{typeLabels[t.type]}</span>
									<span class="badge {priorityBadge[t.priority]} w-fit">{t.priority === 'urgent' ? '紧急' : t.priority === 'high' ? '高' : t.priority === 'medium' ? '中' : '低'}</span>
								</div>
							</td>
							<td class="table-td text-sm">{propMap.get(t.propertyId) ?? '-'}</td>
							<td class="table-td text-sm">{formatDate(t.scheduledDate)} {t.scheduledTime ?? ''}</td>
							<td class="table-td text-sm">{userMap.get(t.assignedTo ?? '') ?? '未指派'}</td>
							<td class="table-td text-sm">¥{t.fee?.toFixed(2)}</td>
							<td class="table-td"><span class="badge {statusBadge[t.status]}">{cleaningStatusLabel(t.status)}</span></td>
							<td class="table-td">
								<div class="flex flex-wrap gap-1.5">
									{#if t.status === 'pending'}
										<button on:click={() => updateStatus(t, 'in_progress')} class="btn-primary text-xs py-1 px-2">开始</button>
									{/if}
									{#if t.status === 'in_progress'}
										<button on:click={() => updateStatus(t, 'completed')} class="btn-success text-xs py-1 px-2">完成</button>
									{/if}
									{(t.status === 'pending' || t.status === 'in_progress')}
										<button on:click={() => updateStatus(t, 'cancelled')} class="btn-secondary text-xs py-1 px-2">取消</button>
								</div>
							</td>
						</tr>
					{/each}
				</tbody>
			</table>
		</div>
	{/if}
</div>

{#if showModal}
	<div class="fixed inset-0 bg-black/40 flex items-center justify-center z-50 p-4" on:click={(e) => { if (e.target === e.currentTarget) showModal = false; }}>
		<div class="bg-white rounded-xl shadow-2xl w-full max-w-lg">
			<div class="px-6 py-4 border-b flex items-center justify-between">
				<h3 class="font-semibold text-lg">新增保洁任务</h3>
				<button on:click={() => showModal = false} class="text-gray-400 hover:text-gray-600">✕</button>
			</div>
			<div class="p-6 space-y-4">
				<div class="grid grid-cols-2 gap-4">
					<div class="col-span-2"><label class="label">房源 *</label>
						<select bind:value={newTask.propertyId} class="select">
							{#each properties as p}<option value={p.id}>{p.name}</option>{/each}
						</select>
					</div>
					<div><label class="label">类型</label>
						<select bind:value={newTask.type} class="select">
							{#each Object.entries(typeLabels) as [k, v]}<option value={k}>{v}</option>{/each}
						</select>
					</div>
					<div><label class="label">优先级</label>
						<select bind:value={newTask.priority} class="select">
							<option value="low">低</option><option value="medium">中</option><option value="high">高</option><option value="urgent">紧急</option>
						</select>
					</div>
					<div><label class="label">计划日期</label><input type="date" bind:value={newTask.scheduledDateStr} class="input" /></div>
					<div><label class="label">计划时间</label><input type="time" bind:value={newTask.scheduledTime} class="input" /></div>
					<div><label class="label">指派人员</label>
						<select bind:value={newTask.assignedTo} class="select">
							<option value="">未指派</option>
							{#each users as u}<option value={u.id}>{u.username}</option>{/each}
						</select>
					</div>
					<div><label class="label">费用 (¥)</label><input type="number" min="0" bind:value={newTask.fee} class="input" /></div>
				</div>
				<div class="pt-2 flex justify-end gap-3">
					<button on:click={() => showModal = false} class="btn-secondary">取消</button>
					<button on:click={submitCreate} class="btn-primary">创建</button>
				</div>
			</div>
		</div>
	</div>
{/if}

// apps/frontend/src/pages/cleaning.tsx
import { useEffect, useState } from 'react';
import { Search, Plus, Filter, Clock, CheckCircle, AlertCircle, User } from 'lucide-react';
import api from '@/lib/api';
import { cn, formatDateTime, getStatusText, getStatusClass } from '@/lib/utils';
import { useAuthStore } from '@/store/auth';

interface CleaningTask {
  id: number;
  taskNo: string;
  status: string;
  priority: number;
  scheduledAt: string;
  remarks: string;
  property: { name: string };
  room: { roomNumber: string; roomType: string };
  order: { orderNo: string; guestName: string } | null;
  assignedTo: { id: number; fullName: string } | null;
}

export default function CleaningPage() {
  const { user } = useAuthStore();
  const [tasks, setTasks] = useState<CleaningTask[]>([]);
  const [total, setTotal] = useState(0);
  const [page, setPage] = useState(1);
  const [pageSize] = useState(10);
  const [statusFilter, setStatusFilter] = useState('');
  const [propertyId, setPropertyId] = useState('');
  const [properties, setProperties] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [selectedTask, setSelectedTask] = useState<CleaningTask | null>(null);
  const [showDetail, setShowDetail] = useState(false);

  useEffect(() => {
    fetchProperties();
  }, []);

  useEffect(() => {
    fetchTasks();
  }, [page, statusFilter, propertyId, user]);

  const fetchProperties = async () => {
    try {
      const res = await api.get('/properties?pageSize=100');
      setProperties(res.data.list || []);
    } catch (e) {
      console.error(e);
    }
  };

  const fetchTasks = async () => {
    setLoading(true);
    try {
      const params: any = { page, pageSize };
      if (statusFilter) params.status = statusFilter;
      if (propertyId) params.propertyId = propertyId;

      const res = await api.get('/cleaning', { params });
      setTasks(res.data.list || []);
      setTotal(res.data.total || 0);
    } catch (e) {
      console.error(e);
    } finally {
      setLoading(false);
    }
  };

  const viewTask = async (task: CleaningTask) => {
    try {
      const res = await api.get(`/cleaning/${task.id}`);
      setSelectedTask(res.data);
      setShowDetail(true);
    } catch (e) {
      console.error(e);
    }
  };

  const updateStatus = async (id: number, status: string) => {
    try {
      await api.patch(`/cleaning/${id}/status`, { status });
      fetchTasks();
      if (showDetail) {
        const res = await api.get(`/cleaning/${id}`);
        setSelectedTask(res.data);
      }
    } catch (e) {
      alert('操作失败');
    }
  };

  const getPriorityText = (priority: number) => {
    if (priority >= 2) return '高';
    if (priority >= 1) return '中';
    return '普通';
  };

  const getPriorityClass = (priority: number) => {
    if (priority >= 2) return 'bg-red-100 text-red-700';
    if (priority >= 1) return 'bg-yellow-100 text-yellow-700';
    return 'bg-gray-100 text-gray-700';
  };

  const totalPages = Math.ceil(total / pageSize);

  const statusStats = [
    { label: '待分配', status: 'PENDING', count: 0 },
    { label: '已分配', status: 'ASSIGNED', count: 0 },
    { label: '进行中', status: 'IN_PROGRESS', count: 0 },
    { label: '已完成', status: 'COMPLETED', count: 0 },
  ];

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-3">
          <select
            value={propertyId}
            onChange={(e) => setPropertyId(e.target.value)}
            className="input w-48"
          >
            <option value="">全部房源</option>
            {properties.map((p) => (
              <option key={p.id} value={p.id}>
                {p.name}
              </option>
            ))}
          </select>
          <select
            value={statusFilter}
            onChange={(e) => setStatusFilter(e.target.value)}
            className="input w-36"
          >
            <option value="">全部状态</option>
            <option value="PENDING">待分配</option>
            <option value="ASSIGNED">已分配</option>
            <option value="IN_PROGRESS">进行中</option>
            <option value="COMPLETED">已完成</option>
            <option value="INSPECTED">已检查</option>
          </select>
        </div>
        {user?.role !== 'FRONTLINE' && (
          <button className="btn btn-primary flex items-center gap-1">
            <Plus className="w-4 h-4" />
            新建任务
          </button>
        )}
      </div>

      <div className="grid grid-cols-4 gap-4">
        {statusStats.map((stat) => (
          <div key={stat.status} className="card p-4">
            <div className="text-sm text-gray-500">{stat.label}</div>
            <div className="text-2xl font-bold text-gray-800 mt-1">-</div>
          </div>
        ))}
      </div>

      <div className="card overflow-hidden">
        {loading ? (
          <div className="p-8 text-center text-gray-500">加载中...</div>
        ) : (
          <table className="w-full">
            <thead className="bg-gray-50">
              <tr>
                <th className="px-4 py-3 text-left text-sm font-medium text-gray-700">任务编号</th>
                <th className="px-4 py-3 text-left text-sm font-medium text-gray-700">房源/房间</th>
                <th className="px-4 py-3 text-left text-sm font-medium text-gray-700">优先级</th>
                <th className="px-4 py-3 text-left text-sm font-medium text-gray-700">计划时间</th>
                <th className="px-4 py-3 text-left text-sm font-medium text-gray-700">负责人</th>
                <th className="px-4 py-3 text-left text-sm font-medium text-gray-700">状态</th>
                <th className="px-4 py-3 text-left text-sm font-medium text-gray-700">操作</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-200">
              {tasks.length === 0 ? (
                <tr>
                  <td colSpan={7} className="px-4 py-12 text-center text-gray-400">
                    暂无保洁任务
                  </td>
                </tr>
              ) : (
                tasks.map((task) => (
                  <tr key={task.id} className="hover:bg-gray-50">
                    <td className="px-4 py-3">
                      <div className="font-medium text-gray-800">{task.taskNo}</div>
                      {task.order && (
                        <div className="text-xs text-gray-500">
                          订单: {task.order.guestName}
                        </div>
                      )}
                    </td>
                    <td className="px-4 py-3">
                      <div className="text-sm text-gray-800">{task.property?.name}</div>
                      <div className="text-xs text-gray-500">
                        {task.room?.roomNumber} · {task.room?.roomType}
                      </div>
                    </td>
                    <td className="px-4 py-3">
                      <span className={cn('badge', getPriorityClass(task.priority))}>
                        {getPriorityText(task.priority)}
                      </span>
                    </td>
                    <td className="px-4 py-3 text-sm text-gray-600">
                      <div className="flex items-center gap-1">
                        <Clock className="w-4 h-4" />
                        {task.scheduledAt ? formatDateTime(task.scheduledAt) : '未安排'}
                      </div>
                    </td>
                    <td className="px-4 py-3">
                      <div className="flex items-center gap-2">
                        <div className="w-7 h-7 bg-gray-200 rounded-full flex items-center justify-center">
                          <User className="w-4 h-4 text-gray-500" />
                        </div>
                        <span className="text-sm text-gray-600">
                          {task.assignedTo?.fullName || '未分配'}
                        </span>
                      </div>
                    </td>
                    <td className="px-4 py-3">
                      <span className={cn('badge', getStatusClass(task.status, 'cleaning'))}>
                        {getStatusText(task.status, 'cleaning')}
                      </span>
                    </td>
                    <td className="px-4 py-3">
                      <button
                        onClick={() => viewTask(task)}
                        className="text-primary-600 hover:text-primary-700 text-sm"
                      >
                        查看详情
                      </button>
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        )}

        {totalPages > 1 && (
          <div className="flex items-center justify-between px-4 py-3 border-t border-gray-200">
            <div className="text-sm text-gray-500">
              共 {total} 条，第 {page}/{totalPages} 页
            </div>
            <div className="flex items-center gap-2">
              <button
                onClick={() => setPage(Math.max(1, page - 1))}
                disabled={page === 1}
                className="px-3 py-1 border border-gray-300 rounded text-sm disabled:opacity-50"
              >
                上一页
              </button>
              <button
                onClick={() => setPage(Math.min(totalPages, page + 1))}
                disabled={page === totalPages}
                className="px-3 py-1 border border-gray-300 rounded text-sm disabled:opacity-50"
              >
                下一页
              </button>
            </div>
          </div>
        )}
      </div>

      {showDetail && selectedTask && (
        <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4">
          <div className="bg-white rounded-lg w-full max-w-lg max-h-[90vh] overflow-y-auto">
            <div className="flex items-center justify-between p-4 border-b border-gray-200">
              <h3 className="text-lg font-semibold text-gray-800">保洁任务详情</h3>
              <button
                onClick={() => setShowDetail(false)}
                className="text-gray-400 hover:text-gray-600"
              >
                ✕
              </button>
            </div>
            <div className="p-6 space-y-4">
              <div className="grid grid-cols-2 gap-4 text-sm">
                <div>
                  <span className="text-gray-500">任务编号：</span>
                  <span className="text-gray-800">{selectedTask.taskNo}</span>
                </div>
                <div>
                  <span className="text-gray-500">状态：</span>
                  <span className={cn('badge', getStatusClass(selectedTask.status, 'cleaning'))}>
                    {getStatusText(selectedTask.status, 'cleaning')}
                  </span>
                </div>
                <div>
                  <span className="text-gray-500">房源：</span>
                  <span className="text-gray-800">{selectedTask.property?.name}</span>
                </div>
                <div>
                  <span className="text-gray-500">房间：</span>
                  <span className="text-gray-800">
                    {selectedTask.room?.roomNumber} · {selectedTask.room?.roomType}
                  </span>
                </div>
                <div>
                  <span className="text-gray-500">优先级：</span>
                  <span className={cn('badge', getPriorityClass(selectedTask.priority))}>
                    {getPriorityText(selectedTask.priority)}
                  </span>
                </div>
                <div>
                  <span className="text-gray-500">负责人：</span>
                  <span className="text-gray-800">
                    {selectedTask.assignedTo?.fullName || '未分配'}
                  </span>
                </div>
              </div>

              {selectedTask.remarks && (
                <div>
                  <span className="text-gray-500 text-sm">备注：</span>
                  <p className="text-sm text-gray-700 mt-1 bg-gray-50 p-3 rounded">
                    {selectedTask.remarks}
                  </p>
                </div>
              )}

              <div className="flex gap-2 pt-4 border-t border-gray-200">
                {selectedTask.status === 'PENDING' && (
                  <button
                    onClick={() => updateStatus(selectedTask.id, 'ASSIGNED')}
                    className="btn btn-primary text-sm"
                  >
                    分配任务
                  </button>
                )}
                {(selectedTask.status === 'ASSIGNED' || selectedTask.status === 'PENDING') && (
                  <button
                    onClick={() => updateStatus(selectedTask.id, 'IN_PROGRESS')}
                    className="btn btn-primary text-sm"
                  >
                    开始清洁
                  </button>
                )}
                {selectedTask.status === 'IN_PROGRESS' && (
                  <button
                    onClick={() => updateStatus(selectedTask.id, 'COMPLETED')}
                    className="btn btn-primary text-sm flex items-center gap-1"
                  >
                    <CheckCircle className="w-4 h-4" />
                    完成清洁
                  </button>
                )}
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
