// src/lib/components/HeatmapChart.svelte
<script lang="ts">
	import BaseChart from './BaseChart.svelte';
	import type { TimeSlotData } from '$lib/types';

	export let data: TimeSlotData[] = [];
	export let title = '预约时段分布';
	export let height = 360;

	const days = ['周日', '周一', '周二', '周三', '周四', '周五', '周六'];
	const hours = Array.from({ length: 13 }, (_, i) => `${i + 8}:00`);

	$: {
		const map = new Map<string, number>();
		let max = 0;
		for (const d of data) {
			const k = `${d.dayOfWeek}_${d.hour}`;
			map.set(k, d.count);
			if (d.count > max) max = d.count;
		}

		const heatData: [number, number, number][] = [];
		for (let day = 0; day < 7; day++) {
			for (let h = 0; h < 13; h++) {
				const hour = h + 8;
				heatData.push([h, day, map.get(`${day}_${hour}`) ?? 0]);
			}
		}

		option = {
			backgroundColor: 'transparent',
			title: {
				text: title,
				textStyle: { color: '#fff', fontSize: 14, fontWeight: 600 },
				left: 16,
				top: 12
			},
			tooltip: {
				backgroundColor: 'rgba(15,23,42,0.95)',
				borderColor: '#334155',
				textStyle: { color: '#e2e8f0' },
				formatter: (params: unknown) => {
					const p = params as { value: [number, number, number] };
					const [h, d, v] = p.value;
					return `<div>${days[d]} ${hours[h]}</div>
						<div>预约数：<span class="text-cyan-400 font-semibold">${v}</span></div>`;
				}
			},
			grid: {
				left: 60,
				right: 40,
				top: 56,
				bottom: 40
			},
			xAxis: {
				type: 'category',
				data: hours,
				splitArea: { show: true },
				axisLabel: { color: '#64748b', fontSize: 10 },
				axisLine: { lineStyle: { color: '#334155' } }
			},
			yAxis: {
				type: 'category',
				data: days,
				splitArea: { show: true },
				axisLabel: { color: '#64748b', fontSize: 11 },
				axisLine: { lineStyle: { color: '#334155' } }
			},
			visualMap: {
				min: 0,
				max: Math.max(max, 1),
				calculable: true,
				orient: 'horizontal',
				right: 20,
				bottom: 4,
				textStyle: { color: '#94a3b8', fontSize: 10 },
				inRange: {
					color: ['#0b1625', '#0e7490', '#22d3ee', '#a5f3fc']
				}
			},
			series: [
				{
					type: 'heatmap',
					data: heatData,
					label: {
						show: true,
						color: '#e2e8f0',
						fontSize: 10,
						formatter: (p: unknown) => {
							const v = (p as { value: [number, number, number] }).value;
							return v[2] > 0 ? v[2] : '';
						}
					},
					emphasis: {
						itemStyle: {
							shadowBlur: 10,
							shadowColor: 'rgba(34,211,238,0.5)'
						}
					}
				}
			] as unknown as import('echarts').EChartsOption['series']
		};
	}

	let option: import('echarts').EChartsOption = {};
</script>

<BaseChart {option} {height} />

// src/components/Charts/HeatmapChart.tsx
import { useEffect, useRef } from 'react';
import * as echarts from 'echarts';
import type { HeatmapData } from '../../types';

interface HeatmapChartProps {
  data: HeatmapData;
  height?: number;
}

export function HeatmapChart({ data, height = 300 }: HeatmapChartProps) {
  const chartRef = useRef<HTMLDivElement>(null);
  const chartInstance = useRef<echarts.ECharts | null>(null);

  useEffect(() => {
    if (!chartRef.current) return;

    if (!chartInstance.current) {
      chartInstance.current = echarts.init(chartRef.current, 'dark');
    }

    const maxCount = Math.max(...data.heatmapData.map(d => d[2] as number), 1);

    const option: echarts.EChartsOption = {
      backgroundColor: 'transparent',
      tooltip: {
        position: 'top',
        backgroundColor: 'rgba(10, 25, 41, 0.9)',
        borderColor: 'rgba(59, 130, 246, 0.3)',
        textStyle: { color: '#fff' },
        formatter: (params: any) => {
          return `${data.hours[params.value[0]]} - ${data.days[params.value[1]]}<br/>客诉数: ${params.value[2]}`;
        },
      },
      grid: {
        left: '8%',
        right: '4%',
        bottom: '10%',
        top: '5%',
      },
      xAxis: {
        type: 'category',
        data: data.hours,
        splitArea: { show: true },
        axisLabel: { color: 'rgba(255,255,255,0.5)', fontSize: 10 },
        axisLine: { lineStyle: { color: 'rgba(255,255,255,0.1)' } },
      },
      yAxis: {
        type: 'category',
        data: data.days,
        splitArea: { show: true },
        axisLabel: { color: 'rgba(255,255,255,0.5)', fontSize: 10 },
        axisLine: { lineStyle: { color: 'rgba(255,255,255,0.1)' } },
      },
      visualMap: {
        min: 0,
        max: maxCount,
        calculable: true,
        orient: 'horizontal',
        left: 'center',
        bottom: '0%',
        textStyle: { color: 'rgba(255,255,255,0.5)' },
        inRange: {
          color: ['#1e3a5f', '#2563eb', '#3b82f6', '#60a5fa', '#f59e0b', '#ef4444'],
        },
      },
      series: [{
        name: '客诉数',
        type: 'heatmap',
        data: data.heatmapData,
        label: {
          show: true,
          color: '#fff',
          fontSize: 10,
        },
        emphasis: {
          itemStyle: {
            shadowBlur: 10,
            shadowColor: 'rgba(0, 0, 0, 0.5)',
          },
        },
      }],
      animationDuration: 1000,
      animationEasing: 'cubicOut',
    };

    chartInstance.current.setOption(option);

    const handleResize = () => chartInstance.current?.resize();
    window.addEventListener('resize', handleResize);

    return () => {
      window.removeEventListener('resize', handleResize);
      chartInstance.current?.dispose();
      chartInstance.current = null;
    };
  }, [data]);

  return <div ref={chartRef} style={{ height: `${height}px`, width: '100%' }} />;
}

export default HeatmapChart;
