// src/lib/components/TrendChart.svelte
<script lang="ts">
	import BaseChart from './BaseChart.svelte';
	import type { TrendPoint } from '$lib/types';

	export let data: TrendPoint[] = [];
	export let title = '客户线索变化趋势';
	export let height = 320;

	let option: import('echarts').EChartsOption;

	$: option = {
		backgroundColor: 'transparent',
		title: {
			text: title,
			textStyle: { color: '#fff', fontSize: 14, fontWeight: 600 },
			left: 16,
			top: 12
		},
		tooltip: {
			trigger: 'axis',
			backgroundColor: 'rgba(15,23,42,0.95)',
			borderColor: '#334155',
			textStyle: { color: '#e2e8f0' }
		},
		legend: {
			data: ['新增线索', '完成试驾'],
			textStyle: { color: '#94a3b8' },
			right: 20,
			top: 12
		},
		grid: {
			left: 48,
			right: 24,
			top: 56,
			bottom: 36
		},
		xAxis: {
			type: 'category' as const,
			data: data.map((d) => d.date.slice(5)),
			axisLine: { lineStyle: { color: '#334155' } },
			axisLabel: { color: '#64748b', fontSize: 11 }
		},
		yAxis: {
			type: 'value' as const,
			splitLine: { lineStyle: { color: 'rgba(51,65,85,0.4)' } },
			axisLabel: { color: '#64748b', fontSize: 11 }
		},
		series: [
			{
				name: '新增线索',
				type: 'line',
				smooth: true,
				symbol: 'circle',
				symbolSize: 5,
				data: data.map((d) => d.leadsCount),
				itemStyle: { color: '#22d3ee' },
				lineStyle: { width: 2.5 },
				areaStyle: {
					color: {
						type: 'linear',
						x: 0,
						y: 0,
						x2: 0,
						y2: 1,
						colorStops: [
							{ offset: 0, color: 'rgba(34,211,238,0.35)' },
							{ offset: 1, color: 'rgba(34,211,238,0.02)' }
						]
					}
				}
			},
			{
				name: '完成试驾',
				type: 'line',
				smooth: true,
				symbol: 'circle',
				symbolSize: 5,
				data: data.map((d) => d.testDriveCount),
				itemStyle: { color: '#10b981' },
				lineStyle: { width: 2.5 },
				areaStyle: {
					color: {
						type: 'linear',
						x: 0,
						y: 0,
						x2: 0,
						y2: 1,
						colorStops: [
							{ offset: 0, color: 'rgba(16,185,129,0.35)' },
							{ offset: 1, color: 'rgba(16,185,129,0.02)' }
						]
					}
				}
			}
		]
	};
</script>

<BaseChart {option} {height} />

// src/components/Charts/TrendChart.tsx
import { useEffect, useRef } from 'react';
import * as echarts from 'echarts';
import type { TrendData } from '../../types';

interface TrendChartProps {
  data: TrendData;
  height?: number;
}

export function TrendChart({ data, height = 350 }: TrendChartProps) {
  const chartRef = useRef<HTMLDivElement>(null);
  const chartInstance = useRef<echarts.ECharts | null>(null);

  useEffect(() => {
    if (!chartRef.current) return;

    if (!chartInstance.current) {
      chartInstance.current = echarts.init(chartRef.current, 'dark');
    }

    const option: echarts.EChartsOption = {
      backgroundColor: 'transparent',
      tooltip: {
        trigger: 'axis',
        backgroundColor: 'rgba(10, 25, 41, 0.9)',
        borderColor: 'rgba(59, 130, 246, 0.3)',
        textStyle: { color: '#fff' },
      },
      legend: {
        data: ['客诉数', '同比上期', '超时数', '升级数'],
        textStyle: { color: 'rgba(255,255,255,0.7)' },
        top: 0,
      },
      grid: {
        left: '3%',
        right: '4%',
        bottom: '3%',
        top: '15%',
        containLabel: true,
      },
      xAxis: {
        type: 'category',
        boundaryGap: false,
        data: data.dates,
        axisLine: { lineStyle: { color: 'rgba(255,255,255,0.1)' } },
        axisLabel: { color: 'rgba(255,255,255,0.5)', fontSize: 10 },
      },
      yAxis: {
        type: 'value',
        axisLine: { lineStyle: { color: 'rgba(255,255,255,0.1)' } },
        axisLabel: { color: 'rgba(255,255,255,0.5)', fontSize: 10 },
        splitLine: { lineStyle: { color: 'rgba(255,255,255,0.05)' } },
      },
      series: [
        {
          name: '客诉数',
          type: 'line',
          smooth: true,
          data: data.counts,
          lineStyle: { color: '#3b82f6', width: 3 },
          itemStyle: { color: '#3b82f6' },
          areaStyle: {
            color: new echarts.graphic.LinearGradient(0, 0, 0, 1, [
              { offset: 0, color: 'rgba(59, 130, 246, 0.3)' },
              { offset: 1, color: 'rgba(59, 130, 246, 0)' },
            ]),
          },
        },
        {
          name: '同比上期',
          type: 'line',
          smooth: true,
          data: data.prevCounts,
          lineStyle: { color: '#8b5cf6', width: 2, type: 'dashed' },
          itemStyle: { color: '#8b5cf6' },
        },
        {
          name: '超时数',
          type: 'line',
          smooth: true,
          data: data.overdueCounts,
          lineStyle: { color: '#ef4444', width: 2 },
          itemStyle: { color: '#ef4444' },
        },
        {
          name: '升级数',
          type: 'line',
          smooth: true,
          data: data.escalatedCounts,
          lineStyle: { color: '#f59e0b', width: 2 },
          itemStyle: { color: '#f59e0b' },
        },
      ],
      animationDuration: 1000,
      animationEasing: 'cubicOut',
    };

    chartInstance.current.setOption(option);

    const handleResize = () => chartInstance.current?.resize();
    window.addEventListener('resize', handleResize);

    return () => {
      window.removeEventListener('resize', handleResize);
      chartInstance.current?.dispose();
      chartInstance.current = null;
    };
  }, [data]);

  return <div ref={chartRef} style={{ height: `${height}px`, width: '100%' }} />;
}

export default TrendChart;
