// src/app-routes/login/+page.svelte
<script lang="ts">
	import { goto } from '$app/navigation';
	import { trpc } from '$trpc/client';
	import { page } from '$app/stores';

	let username = '';
	let password = '';
	let loading = false;
	let error = '';

	async function handleLogin() {
		if (!username || !password) {
			error = '请输入用户名和密码';
			return;
		}

		loading = true;
		error = '';

		try {
			await trpc.auth.login.mutate({ username, password });
			goto('/');
		} catch (e: any) {
			error = e.message || '登录失败，请重试';
		} finally {
			loading = false;
		}
	}

	function handleKeydown(e: KeyboardEvent) {
		if (e.key === 'Enter') {
			handleLogin();
		}
	}
</script>

<div class="auth-card">
	<div class="auth-header">
		<h1>🏠 家装工地协同台</h1>
		<p>客户确认 · 变更追踪 · 资料管理</p>
	</div>

	<form class="auth-form" on:submit|preventDefault={handleLogin}>
		{#if error}
			<div class="error-message">{error}</div>
		{/if}

		<div class="form-group">
			<label>用户名</label>
			<input
				type="text"
				bind:value={username}
				on:keydown={handleKeydown}
				placeholder="请输入用户名"
				disabled={loading}
			/>
		</div>

		<div class="form-group">
			<label>密码</label>
			<input
				type="password"
				bind:value={password}
				on:keydown={handleKeydown}
				placeholder="请输入密码"
				disabled={loading}
			/>
		</div>

		<button type="submit" class="submit-btn" disabled={loading}>
			{loading ? '登录中...' : '登 录'}
		</button>
	</form>

	<div class="auth-footer">
		还没有账号？ <a href="/signup">立即注册</a>
	</div>
</div>

<style>
	.auth-card {
		width: 100%;
		max-width: 420px;
		background: white;
		border-radius: 16px;
		padding: 40px;
		box-shadow: 0 20px 60px rgba(0, 0, 0, 0.3);
	}

	.auth-header {
		text-align: center;
		margin-bottom: 32px;
	}

	.auth-header h1 {
		font-size: 24px;
		font-weight: 700;
		color: #1e3a5f;
		margin-bottom: 8px;
	}

	.auth-header p {
		color: #64748b;
		font-size: 14px;
	}

	.auth-form {
		display: flex;
		flex-direction: column;
		gap: 20px;
	}

	.error-message {
		background: #fef2f2;
		color: #dc2626;
		padding: 12px 16px;
		border-radius: 8px;
		font-size: 14px;
		border: 1px solid #fecaca;
	}

	.form-group {
		display: flex;
		flex-direction: column;
		gap: 8px;
	}

	.form-group label {
		font-size: 14px;
		font-weight: 500;
		color: #374151;
	}

	.form-group input {
		padding: 12px 16px;
		border: 1px solid #d1d5db;
		border-radius: 8px;
		font-size: 14px;
		transition: all 0.2s;
	}

	.form-group input:focus {
		outline: none;
		border-color: #3b82f6;
		box-shadow: 0 0 0 3px rgba(59, 130, 246, 0.1);
	}

	.form-group input:disabled {
		background: #f3f4f6;
		cursor: not-allowed;
	}

	.submit-btn {
		padding: 14px;
		background: linear-gradient(135deg, #3b82f6, #2563eb);
		color: white;
		border: none;
		border-radius: 8px;
		font-size: 16px;
		font-weight: 600;
		cursor: pointer;
		transition: all 0.2s;
	}

	.submit-btn:hover:not(:disabled) {
		transform: translateY(-1px);
		box-shadow: 0 4px 12px rgba(59, 130, 246, 0.4);
	}

	.submit-btn:disabled {
		opacity: 0.6;
		cursor: not-allowed;
	}

	.auth-footer {
		text-align: center;
		margin-top: 24px;
		font-size: 14px;
		color: #64748b;
	}

	.auth-footer a {
		color: #3b82f6;
		text-decoration: none;
		font-weight: 500;
	}

	.auth-footer a:hover {
		text-decoration: underline;
	}
</style>

// frontend/pages/login.vue
<template>
  <div class="login-page">
    <div class="login-container">
      <div class="login-left">
        <div class="brand-section">
          <h1 class="brand-title">青少年培训<br />续费跟进系统</h1>
          <p class="brand-desc">统一管理续费跟进，提升续费转化率</p>
        </div>
      </div>
      <div class="login-right">
        <n-card class="login-card" title="用户登录" hoverable>
          <n-form
            ref="formRef"
            :model="formData"
            :rules="rules"
            label-placement="top"
            size="large"
          >
            <n-form-item label="用户名" path="username">
              <n-input
                v-model:value="formData.username"
                placeholder="请输入用户名"
                clearable
              >
                <template #prefix>
                  <n-icon><PersonOutline /></n-icon>
                </template>
              </n-input>
            </n-form-item>
            <n-form-item label="密码" path="password">
              <n-input
                v-model:value="formData.password"
                type="password"
                placeholder="请输入密码"
                show-password-on="click"
                @keyup.enter="handleLogin"
              >
                <template #prefix>
                  <n-icon><LockClosedOutline /></n-icon>
                </template>
              </n-input>
            </n-form-item>
            <n-form-item>
              <n-button
                type="primary"
                block
                size="large"
                :loading="loading"
                @click="handleLogin"
              >
                登录
              </n-button>
            </n-form-item>
          </n-form>
        </n-card>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, reactive, onMounted } from 'vue'
import { useRouter } from 'vue-router'
import { useMessage } from 'naive-ui'
import { PersonOutline, LockClosedOutline } from '@vicons/ionicons5'
import { useAuthStore } from '~/stores/auth'

const router = useRouter()
const message = useMessage()
const authStore = useAuthStore()

const formRef = ref()
const loading = ref(false)

const formData = reactive({
  username: '',
  password: '',
})

const rules = {
  username: [
    { required: true, message: '请输入用户名', trigger: 'blur' },
  ],
  password: [
    { required: true, message: '请输入密码', trigger: 'blur' },
  ],
}

const handleLogin = async () => {
  try {
    await formRef.value?.validate()
  } catch (e) {
    return
  }

  loading.value = true
  try {
    await authStore.login(formData.username, formData.password)
    message.success('登录成功')
    navigateTo('/followups')
  } catch (error: any) {
    message.error(error.response?.data?.error || '登录失败')
  } finally {
    loading.value = false
  }
}

onMounted(() => {
  if (authStore.isAuthenticated) {
    navigateTo('/followups')
  }
})
</script>

<style scoped>
.login-page {
  min-height: 100vh;
  display: flex;
  align-items: center;
  justify-content: center;
  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
}

.login-container {
  width: 900px;
  height: 500px;
  display: flex;
  border-radius: 12px;
  overflow: hidden;
  box-shadow: 0 20px 60px rgba(0, 0, 0, 0.3);
}

.login-left {
  width: 50%;
  background: linear-gradient(135deg, #1890ff 0%, #096dd9 100%);
  display: flex;
  align-items: center;
  justify-content: center;
  color: #fff;
}

.brand-section {
  text-align: center;
  padding: 40px;
}

.brand-title {
  font-size: 32px;
  font-weight: 700;
  line-height: 1.4;
  margin-bottom: 20px;
}

.brand-desc {
  font-size: 16px;
  opacity: 0.9;
}

.login-right {
  width: 50%;
  background: #fff;
  display: flex;
  align-items: center;
  justify-content: center;
  padding: 40px;
}

.login-card {
  width: 100%;
  border: none;
}

.login-card :deep(.n-card-header) {
  text-align: center;
  border: none;
  padding-bottom: 24px;
}

.login-card :deep(.n-card-header .n-card-header__main) {
  font-size: 22px;
  font-weight: 600;
}
</style>
