// components/ui/Badge.tsx
import * as React from 'react'
import { cva, type VariantProps } from 'class-variance-authority'
import { cn } from '@/lib/utils'

const badgeVariants = cva(
  'inline-flex items-center rounded-full px-2.5 py-0.5 text-xs font-medium transition-colors focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2',
  {
    variants: {
      variant: {
        default:
          'bg-primary/15 text-primary hover:bg-primary/25',
        secondary:
          'bg-secondary/50 text-secondary-foreground hover:bg-secondary/70',
        destructive:
          'bg-destructive/15 text-destructive hover:bg-destructive/25',
        accent:
          'bg-accent/15 text-accent hover:bg-accent/25',
        success:
          'bg-green-500/15 text-green-400 hover:bg-green-500/25',
        warning:
          'bg-yellow-500/15 text-yellow-400 hover:bg-yellow-500/25',
      },
    },
    defaultVariants: {
      variant: 'default',
    },
  }
)

export interface BadgeProps
  extends React.HTMLAttributes<HTMLDivElement>,
    VariantProps<typeof badgeVariants> {}

function Badge({ className, variant, ...props }: BadgeProps) {
  return (
    <div className={cn(badgeVariants({ variant }), className)} {...props} />
  )
}

export { Badge, badgeVariants }

// src/lib/components/ui/Badge.svelte
<script lang="ts">
	import { cn } from '$lib/utils/cn';
	import type { ComponentType, SvelteComponentTyped } from 'svelte';

	type Variant = 'primary' | 'accent' | 'success' | 'warning' | 'danger' | 'secondary';
	type Size = 'sm' | 'md';

	export let variant: Variant = 'secondary';
	export let size: Size = 'md';
	export let dot = false;
	export let icon: ComponentType<SvelteComponentTyped> | undefined = undefined;
	let className: string | undefined = undefined;
	export { className as class };

	$: variantClasses = {
		primary: 'bg-primary-600/20 text-primary-300 border-primary-500/30',
		accent: 'bg-accent-500/20 text-accent-400 border-accent-500/30',
		success: 'bg-success-500/20 text-success-400 border-success-500/30',
		warning: 'bg-warning-500/20 text-warning-400 border-warning-500/30',
		danger: 'bg-danger-500/20 text-danger-400 border-danger-500/30',
		secondary: 'bg-industrial-700/60 text-industrial-300 border-industrial-600'
	}[variant];

	$: dotColor = {
		primary: 'bg-primary-400',
		accent: 'bg-accent-400',
		success: 'bg-success-400',
		warning: 'bg-warning-400',
		danger: 'bg-danger-400',
		secondary: 'bg-industrial-400'
	}[variant];

	$: classes = cn(
		'inline-flex items-center gap-1.5 rounded-full border font-medium',
		size === 'sm' ? 'px-2 py-0.5 text-xs' : 'px-2.5 py-1 text-xs',
		variantClasses,
		className
	);
</script>

<span class={classes}>
	{#if dot}
		<span class={cn('w-1.5 h-1.5 rounded-full', dotColor)} />
	{/if}
	{#if icon}
		<svelte:component this={icon} class={size === 'sm' ? 'w-3 h-3' : 'w-3.5 h-3.5'} strokeWidth={2} />
	{/if}
	<slot />
</span>
