// src/lib/components/DataTable.svelte
<script lang="ts">
	import { cn } from '$lib/utils/cn';
	import EmptyState from './EmptyState.svelte';
	import { Loader2 } from 'lucide-svelte';
	import type { ComponentType } from 'svelte';

	export interface Column<T = unknown> {
		key: keyof T | string;
		title: string;
		width?: string;
		className?: string;
		render?: (item: T, index: number) => string | number | null | undefined;
		component?: ComponentType;
		componentProps?: (item: T, index: number) => Record<string, unknown>;
	}

	type ItemType = unknown;

	export let columns: Column<ItemType>[] = [];
	export let data: ItemType[] = [];
	export let loading = false;
	export let emptyTitle = '暂无数据';
	export let emptyDescription = '';
	export let rowKey: string | undefined = undefined;
	export let className = '';
	export let onRowClick: ((item: ItemType, index: number) => void) | undefined = undefined;

	function handleRowClick(item: ItemType, index: number) {
		onRowClick?.(item, index);
	}

	function getKeyValue(item: ItemType, key: string): unknown {
		const keys = key.split('.');
		let value: unknown = item;
		for (const k of keys) {
			if (value && typeof value === 'object' && k in value) {
				value = (value as Record<string, unknown>)[k];
			} else {
				return undefined;
			}
		}
		return value;
	}

	function getCellContent(item: ItemType, column: Column<ItemType>, index: number): string | number | null | undefined {
		if (column.render) {
			return column.render(item, index);
		}
		const value = getKeyValue(item, column.key as string);
		if (value instanceof Date) {
			return value.toLocaleDateString('zh-CN');
		}
		return value as string | number | null | undefined;
	}

	function getRowKey(item: ItemType, index: number): string | number {
		if (!rowKey) return index;
		const value = getKeyValue(item, rowKey);
		return value !== undefined && value !== null ? String(value) : index;
	}
</script>

<div class={cn('card overflow-hidden', className)}>
	<div class="overflow-x-auto">
		<table class="w-full">
			<thead>
				<tr class="bg-gray-50 border-b border-gray-100">
					{#each columns as column}
						<th
							class={cn(
								'px-4 py-3 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider',
								column.className
							)}
							style={column.width ? `width: ${column.width}` : undefined}
						>
							{column.title}
						</th>
					{/each}
				</tr>
			</thead>
			<tbody class="divide-y divide-gray-100">
				{#if loading}
					<tr>
						<td colspan={columns.length || 1} class="px-4 py-16">
							<div class="flex flex-col items-center justify-center gap-3">
								<Loader2 class="w-8 h-8 text-primary-500 animate-spin" />
								<p class="text-sm text-gray-500">加载中...</p>
							</div>
						</td>
					</tr>
				{:else if data.length === 0}
					<tr>
						<td colspan={columns.length || 1} class="px-4 py-8">
							<EmptyState title={emptyTitle} description={emptyDescription} />
						</td>
					</tr>
				{:else}
					{#each data as item, index (getRowKey(item, index))}
						<tr
							class={cn(
								'transition-colors duration-150',
								onRowClick && 'hover:bg-primary-50 cursor-pointer'
							)}
							on:click={() => handleRowClick(item, index)}
						>
							{#each columns as column}
								<td class={cn('px-4 py-3 text-sm text-gray-700', column.className)}>
									{#if column.component}
										<svelte:component
											this={column.component}
											{...(column.componentProps ? column.componentProps(item, index) : { item, index })}
										/>
									{:else}
										{getCellContent(item, column, index)}
									{/if}
								</td>
							{/each}
						</tr>
					{/each}
				{/if}
			</tbody>
		</table>
	</div>
</div>

// apps/web/src/components/common/DataTable.tsx
'use client';

import { cn } from '@/lib/utils';
import type { ReactNode } from 'react';
import { ChevronLeft, ChevronRight, ChevronsLeft, ChevronsRight } from 'lucide-react';

export interface Column<T> {
  key: string;
  title: string;
  dataIndex?: keyof T;
  render?: (record: T, index: number) => ReactNode;
  width?: string | number;
  align?: 'left' | 'center' | 'right';
  sorter?: boolean;
}

interface DataTableProps<T> {
  columns: Column<T>[];
  data: T[];
  rowKey?: keyof T | ((record: T) => string);
  loading?: boolean;
  emptyText?: string;
  onRowClick?: (record: T) => void;
  pagination?: {
    current: number;
    pageSize: number;
    total: number;
    onChange: (page: number, pageSize: number) => void;
  };
  className?: string;
}

export default function DataTable<T extends Record<string, any>>({
  columns,
  data,
  rowKey,
  loading,
  emptyText = '暂无数据',
  onRowClick,
  pagination,
  className,
}: DataTableProps<T>) {
  const getRowKey = (record: T, index: number): string => {
    if (typeof rowKey === 'function') return rowKey(record);
    if (rowKey) return String(record[rowKey]);
    return String(index);
  };

  const totalPages = pagination ? Math.ceil(pagination.total / pagination.pageSize) : 0;

  return (
    <div className={cn('w-full overflow-hidden', className)}>
      <div className="overflow-x-auto">
        <table className="w-full text-sm text-left">
          <thead className="text-xs text-slate-500 uppercase bg-slate-50 border-b border-slate-200">
            <tr>
              {columns.map((col) => (
                <th
                  key={col.key}
                  className="px-4 py-3 font-medium"
                  style={{
                    width: col.width,
                    textAlign: col.align || 'left',
                  }}
                >
                  {col.title}
                </th>
              ))}
            </tr>
          </thead>
          <tbody>
            {loading ? (
              <tr>
                <td
                  colSpan={columns.length}
                  className="px-4 py-8 text-center text-slate-500"
                >
                  加载中...
                </td>
              </tr>
            ) : data.length === 0 ? (
              <tr>
                <td
                  colSpan={columns.length}
                  className="px-4 py-8 text-center text-slate-500"
                >
                  {emptyText}
                </td>
              </tr>
            ) : (
              data.map((record, index) => (
                <tr
                  key={getRowKey(record, index)}
                  onClick={() => onRowClick?.(record)}
                  className={cn(
                    'border-b border-slate-100 hover:bg-slate-50 transition-colors',
                    onRowClick && 'cursor-pointer'
                  )}
                >
                  {columns.map((col) => (
                    <td
                      key={col.key}
                      className="px-4 py-3"
                      style={{
                        width: col.width,
                        textAlign: col.align || 'left',
                      }}
                    >
                      {col.render
                        ? col.render(record, index)
                        : col.dataIndex
                        ? String(record[col.dataIndex] ?? '')
                        : null}
                    </td>
                  ))}
                </tr>
              ))
            )}
          </tbody>
        </table>
      </div>
      {pagination && pagination.total > 0 && (
        <div className="flex items-center justify-between px-4 py-3 border-t border-slate-200">
          <div className="text-sm text-slate-500">
            共 {pagination.total} 条
          </div>
          <div className="flex items-center gap-1">
            <button
              onClick={() => pagination.onChange(1, pagination.pageSize)}
              disabled={pagination.current <= 1}
              className="p-1.5 rounded-md border border-slate-200 text-slate-600 disabled:opacity-50 disabled:cursor-not-allowed hover:bg-slate-50"
            >
              <ChevronsLeft className="w-4 h-4" />
            </button>
            <button
              onClick={() =>
                pagination.onChange(pagination.current - 1, pagination.pageSize)
              }
              disabled={pagination.current <= 1}
              className="p-1.5 rounded-md border border-slate-200 text-slate-600 disabled:opacity-50 disabled:cursor-not-allowed hover:bg-slate-50"
            >
              <ChevronLeft className="w-4 h-4" />
            </button>
            <span className="px-3 text-sm text-slate-600">
              {pagination.current} / {totalPages}
            </span>
            <button
              onClick={() =>
                pagination.onChange(pagination.current + 1, pagination.pageSize)
              }
              disabled={pagination.current >= totalPages}
              className="p-1.5 rounded-md border border-slate-200 text-slate-600 disabled:opacity-50 disabled:cursor-not-allowed hover:bg-slate-50"
            >
              <ChevronRight className="w-4 h-4" />
            </button>
            <button
              onClick={() => pagination.onChange(totalPages, pagination.pageSize)}
              disabled={pagination.current >= totalPages}
              className="p-1.5 rounded-md border border-slate-200 text-slate-600 disabled:opacity-50 disabled:cursor-not-allowed hover:bg-slate-50"
            >
              <ChevronsRight className="w-4 h-4" />
            </button>
          </div>
        </div>
      )}
    </div>
  );
}
