// resources/js/Components/Toast.vue
<script setup>
import { ref, watch, onMounted } from 'vue'
import { usePage } from '@inertiajs/vue3'
import { CheckCircle2, XCircle, AlertTriangle, Info, X } from 'lucide-vue-next'

const page = usePage()
const toasts = ref([])

const typeConfig = {
  success: {
    icon: CheckCircle2,
    bgClass: 'bg-green-50 border-green-200',
    iconClass: 'text-green-600',
    textClass: 'text-green-800',
  },
  error: {
    icon: XCircle,
    bgClass: 'bg-red-50 border-red-200',
    iconClass: 'text-red-600',
    textClass: 'text-red-800',
  },
  warning: {
    icon: AlertTriangle,
    bgClass: 'bg-yellow-50 border-yellow-200',
    iconClass: 'text-yellow-600',
    textClass: 'text-yellow-800',
  },
  info: {
    icon: Info,
    bgClass: 'bg-blue-50 border-blue-200',
    iconClass: 'text-blue-600',
    textClass: 'text-blue-800',
  },
}

const addToast = (message, type = 'info') => {
  const id = Date.now() + Math.random()
  toasts.value.push({ id, message, type })
  setTimeout(() => {
    removeToast(id)
  }, 5000)
}

const removeToast = (id) => {
  toasts.value = toasts.value.filter((t) => t.id !== id)
}

onMounted(() => {
  const flash = page.props.flash || {}
  if (flash.success) addToast(flash.success, 'success')
  if (flash.error) addToast(flash.error, 'error')
  if (flash.warning) addToast(flash.warning, 'warning')
  if (flash.info) addToast(flash.info, 'info')
})

watch(
  () => page.props.flash,
  (flash) => {
    if (!flash) return
    if (flash.success) addToast(flash.success, 'success')
    if (flash.error) addToast(flash.error, 'error')
    if (flash.warning) addToast(flash.warning, 'warning')
    if (flash.info) addToast(flash.info, 'info')
  },
  { deep: true }
)
</script>

<template>
  <div class="fixed top-4 right-4 z-50 space-y-3 w-full max-w-sm">
    <TransitionGroup name="toast">
      <div
        v-for="toast in toasts"
        :key="toast.id"
        :class="[
          'flex items-start gap-3 p-4 rounded-lg border shadow-lg backdrop-blur-sm',
          typeConfig[toast.type]?.bgClass || typeConfig.info.bgClass,
        ]"
      >
        <component
          :is="typeConfig[toast.type]?.icon || Info"
          :class="['w-5 h-5 shrink-0 mt-0.5', typeConfig[toast.type]?.iconClass || typeConfig.info.iconClass]"
        />
        <p :class="['flex-1 text-sm font-medium', typeConfig[toast.type]?.textClass || typeConfig.info.textClass]">
          {{ toast.message }}
        </p>
        <button
          type="button"
          @click="removeToast(toast.id)"
          :class="['shrink-0 p-1 rounded-md transition-colors hover:bg-black/5', typeConfig[toast.type]?.textClass || typeConfig.info.textClass]"
        >
          <X class="w-4 h-4" />
        </button>
      </div>
    </TransitionGroup>
  </div>
</template>

<style scoped>
.toast-enter-active,
.toast-leave-active {
  transition: all 0.3s ease;
}
.toast-enter-from {
  opacity: 0;
  transform: translateX(100%);
}
.toast-leave-to {
  opacity: 0;
  transform: translateX(100%);
}
.toast-move {
  transition: transform 0.3s ease;
}
</style>

// apps/web/src/components/common/Toast.tsx
'use client';

import * as Toast from '@radix-ui/react-toast';
import { X, CheckCircle, AlertCircle, Info, AlertTriangle } from 'lucide-react';
import { create } from 'zustand';
import { cn } from '@/lib/utils';

export type ToastType = 'success' | 'error' | 'info' | 'warning';

interface ToastItem {
  id: string;
  title: string;
  description?: string;
  type: ToastType;
  duration?: number;
}

interface ToastStore {
  toasts: ToastItem[];
  addToast: (toast: Omit<ToastItem, 'id'>) => void;
  removeToast: (id: string) => void;
}

export const useToastStore = create<ToastStore>((set) => ({
  toasts: [],
  addToast: (toast) => {
    const id = Math.random().toString(36).slice(2);
    set((state) => ({ toasts: [...state.toasts, { ...toast, id }] }));
    setTimeout(() => {
      set((state) => ({ toasts: state.toasts.filter((t) => t.id !== id) }));
    }, toast.duration ?? 3000);
  },
  removeToast: (id) =>
    set((state) => ({ toasts: state.toasts.filter((t) => t.id !== id) })),
}));

export function toast(
  title: string,
  options?: { description?: string; type?: ToastType; duration?: number }
) {
  useToastStore.getState().addToast({
    title,
    description: options?.description,
    type: options?.type ?? 'info',
    duration: options?.duration,
  });
}

const IconMap = {
  success: CheckCircle,
  error: AlertCircle,
  info: Info,
  warning: AlertTriangle,
};

const ColorMap = {
  success: 'text-success border-success/30 bg-success/5',
  error: 'text-danger border-danger/30 bg-danger/5',
  info: 'text-info border-info/30 bg-info/5',
  warning: 'text-warning border-warning/30 bg-warning/5',
};

export function Toaster() {
  const toasts = useToastStore((state) => state.toasts);
  const removeToast = useToastStore((state) => state.removeToast);

  return (
    <Toast.Provider>
      {toasts.map((t) => {
        const Icon = IconMap[t.type];
        return (
          <Toast.Root
            key={t.id}
            open
            onOpenChange={(open) => !open && removeToast(t.id)}
            className={cn(
              'fixed right-4 top-4 z-[100] w-80 rounded-lg border shadow-lg p-4',
              ColorMap[t.type]
            )}
            style={{ marginTop: `${toasts.indexOf(t) * 80}px` }}
          >
            <div className="flex gap-3">
              <Icon className="w-5 h-5 flex-shrink-0 mt-0.5" />
              <div className="flex-1 min-w-0">
                <Toast.Title className="text-sm font-medium">{t.title}</Toast.Title>
                {t.description && (
                  <Toast.Description className="mt-1 text-sm opacity-80">
                    {t.description}
                  </Toast.Description>
                )}
              </div>
              <Toast.Close className="opacity-70 hover:opacity-100">
                <X className="w-4 h-4" />
              </Toast.Close>
            </div>
          </Toast.Root>
        );
      })}
      <Toast.Viewport />
    </Toast.Provider>
  );
}
