// src/routes/login/+page.svelte
<script lang="ts">
  import { goto } from '$app/navigation';
  import { trpc } from '$lib/trpc/client';
  import { userStore } from '$lib/stores/user';
  import { Wrench, Loader2, AlertCircle } from 'lucide-svelte';

  let username = '';
  let password = '';
  let loading = false;
  let error = '';

  async function handleLogin() {
    if (!username || !password) {
      error = '请输入用户名和密码';
      return;
    }

    loading = true;
    error = '';

    try {
      const result = await trpc.auth.login.mutate({ username, password });
      $userStore = result.user;
      await goto('/');
    } catch (e: any) {
      error = e.message || '登录失败，请重试';
    } finally {
      loading = false;
    }
  }

  async function handleKeydown(e: KeyboardEvent) {
    if (e.key === 'Enter') {
      await handleLogin();
    }
  }
</script>

<div class="min-h-screen flex items-center justify-center bg-industrial-bg p-4">
  <div class="absolute inset-0 overflow-hidden pointer-events-none">
    <div class="absolute -top-1/2 -right-1/2 w-full h-full bg-gradient-to-br from-primary-500/10 to-transparent rounded-full blur-3xl"></div>
    <div class="absolute -bottom-1/2 -left-1/2 w-full h-full bg-gradient-to-tr from-accent-orange/10 to-transparent rounded-full blur-3xl"></div>
    <div class="absolute top-1/4 left-1/4 w-96 h-96 bg-primary-500/5 rounded-full blur-3xl animate-pulse-slow"></div>
  </div>

  <div class="relative w-full max-w-md animate-fade-in">
    <div class="card p-8 backdrop-blur-sm bg-industrial-card/90">
      <div class="flex flex-col items-center mb-8">
        <div class="w-16 h-16 rounded-xl bg-gradient-to-br from-primary-500 to-primary-700 flex items-center justify-center mb-4 shadow-xl shadow-primary-500/30">
          <Wrench class="w-8 h-8 text-white" />
        </div>
        <h1 class="font-display text-2xl font-bold text-industrial-text">汽车维修报价协同台</h1>
        <p class="text-industrial-text-muted mt-1">Auto Repair Collaboration Platform</p>
      </div>

      <form class="space-y-5" on:submit|preventDefault={handleLogin}>
        <div>
          <label for="username" class="label">用户名</label>
          <input
            id="username"
            type="text"
            bind:value={username}
            on:keydown={handleKeydown}
            class="input"
            placeholder="请输入用户名"
            autocomplete="username"
          />
        </div>

        <div>
          <label for="password" class="label">密码</label>
          <input
            id="password"
            type="password"
            bind:value={password}
            on:keydown={handleKeydown}
            class="input"
            placeholder="请输入密码"
            autocomplete="current-password"
          />
        </div>

        {#if error}
          <div class="flex items-center gap-2 p-3 rounded-lg bg-accent-red/10 border border-accent-red/30 text-accent-red text-sm animate-fade-in">
            <AlertCircle class="w-4 h-4 shrink-0" />
            <span>{error}</span>
          </div>
        {/if}

        <button
          type="submit"
          disabled={loading}
          class="btn btn-primary w-full h-11 font-medium text-base"
        >
          {#if loading}
            <span class="flex items-center justify-center gap-2">
              <Loader2 class="w-5 h-5 animate-spin" />
              登录中...
            </span>
          {:else}
            登 录
          {/if}
        </button>
      </form>

      <div class="mt-6 pt-6 border-t border-industrial-border">
        <p class="text-center text-sm text-industrial-text-muted">
          演示账号：
        </p>
        <div class="mt-3 grid grid-cols-2 gap-2 text-xs">
          <div class="p-2 rounded bg-industrial-bg border border-industrial-border">
            <p class="font-medium text-industrial-text">admin / admin123</p>
            <p class="text-industrial-text-muted">系统管理员</p>
          </div>
          <div class="p-2 rounded bg-industrial-bg border border-industrial-border">
            <p class="font-medium text-industrial-text">tech01 / tech123</p>
            <p class="text-industrial-text-muted">一线人员</p>
          </div>
        </div>
      </div>
    </div>

    <p class="text-center text-xs text-industrial-text-muted mt-4">
      © 2024 汽车维修报价协同台 · 专业维修管理系统
    </p>
  </div>
</div>

// src/pages/Login.tsx
import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { BarChart3, Eye, EyeOff, Loader2 } from 'lucide-react';
import { useAuthStore } from '@/store/authStore';
import { api } from '@/services/api';

const Login: React.FC = () => {
  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');
  const [showPassword, setShowPassword] = useState(false);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const navigate = useNavigate();
  const login = useAuthStore((state) => state.login);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);
    setError('');

    try {
      const response = await api.auth.login(username, password);
      login(response.user, response.accessToken);
      navigate('/');
    } catch (err) {
      setError(err instanceof Error ? err.message : '登录失败，请检查用户名和密码');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen flex items-center justify-center p-8">
      <div className="absolute inset-0 overflow-hidden">
        <div className="absolute -top-40 -right-40 w-80 h-80 bg-primary-500/20 rounded-full blur-3xl" />
        <div className="absolute -bottom-40 -left-40 w-80 h-80 bg-primary-700/20 rounded-full blur-3xl" />
        <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-96 h-96 bg-primary-600/10 rounded-full blur-3xl" />
      </div>

      <div className="relative card-gradient p-8 w-full max-w-md animate-fade-in">
        <div className="text-center mb-8">
          <div className="inline-flex items-center justify-center w-16 h-16 bg-gradient-to-br from-primary-500 to-primary-700 rounded-2xl mb-4 shadow-lg shadow-primary-500/30">
            <BarChart3 size={32} className="text-white" />
          </div>
          <h1 className="text-2xl font-bold text-white mb-2">职业教育题库练习看板</h1>
          <p className="text-dark-400 text-sm">请登录以访问数据看板</p>
        </div>

        <form onSubmit={handleSubmit} className="space-y-5">
          <div>
            <label className="block text-sm font-medium text-dark-300 mb-2">用户名</label>
            <input
              type="text"
              value={username}
              onChange={(e) => setUsername(e.target.value)}
              className="w-full px-4 py-3 bg-dark-900/60 border border-dark-600 rounded-xl text-white placeholder-dark-500 focus:outline-none focus:border-primary-500 focus:ring-2 focus:ring-primary-500/20 transition-all duration-200"
              placeholder="请输入用户名"
              required
            />
          </div>

          <div>
            <label className="block text-sm font-medium text-dark-300 mb-2">密码</label>
            <div className="relative">
              <input
                type={showPassword ? 'text' : 'password'}
                value={password}
                onChange={(e) => setPassword(e.target.value)}
                className="w-full px-4 py-3 bg-dark-900/60 border border-dark-600 rounded-xl text-white placeholder-dark-500 focus:outline-none focus:border-primary-500 focus:ring-2 focus:ring-primary-500/20 transition-all duration-200 pr-12"
                placeholder="请输入密码"
                required
              />
              <button
                type="button"
                onClick={() => setShowPassword(!showPassword)}
                className="absolute right-4 top-1/2 -translate-y-1/2 text-dark-400 hover:text-white transition-colors"
              >
                {showPassword ? <EyeOff size={18} /> : <Eye size={18} />}
              </button>
            </div>
          </div>

          {error && (
            <div className="p-3 bg-red-500/10 border border-red-500/30 rounded-xl text-red-400 text-sm">
              {error}
            </div>
          )}

          <button
            type="submit"
            disabled={loading}
            className="w-full btn-primary py-3 flex items-center justify-center gap-2 disabled:opacity-50 disabled:cursor-not-allowed"
          >
            {loading ? (
              <>
                <Loader2 size={18} className="animate-spin" />
                登录中...
              </>
            ) : (
              '登录'
            )}
          </button>
        </form>

        <div className="mt-6 pt-6 border-t border-dark-700/50">
          <p className="text-xs text-dark-500 text-center mb-3">测试账号</p>
          <div className="grid grid-cols-2 gap-2 text-xs">
            <div className="p-2 bg-dark-800/40 rounded-lg">
              <p className="text-dark-300">管理员</p>
              <p className="text-dark-400 font-mono">admin / admin123</p>
            </div>
            <div className="p-2 bg-dark-800/40 rounded-lg">
              <p className="text-dark-300">管理层</p>
              <p className="text-dark-400 font-mono">manager / manager123</p>
            </div>
            <div className="p-2 bg-dark-800/40 rounded-lg col-span-2">
              <p className="text-dark-300">教师</p>
              <p className="text-dark-400 font-mono">teacher1 / teacher123 &nbsp;|&nbsp; teacher2 / teacher123</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Login;
