// web/src/app/biz/orders/page.tsx
'use client';

import React, { useState, useEffect, useCallback } from 'react';
import { fetchApi, buildQuery } from '@/lib/api';

interface OrderItem {
  id: string;
  ticketTypeId: string;
  ticketType?: { id: string; name: string };
  seatId?: string;
  seat?: { id: string; seatNo: string };
  unitPrice: number;
  status: string;
}

interface Order {
  id: string;
  orderNo: string;
  buyerName: string;
  buyerPhone: string;
  totalAmount: number;
  status: string;
  assigneeId?: string;
  assignee?: { id: string; name: string };
  eventId?: string;
  event?: { id: string; name: string };
  items?: OrderItem[];
  createdAt: string;
}

interface ListResponse {
  data: Order[];
  total: number;
  page: number;
  limit: number;
}

const STATUS_OPTIONS = [
  { value: '', label: '全部' },
  { value: 'pending', label: '待支付' },
  { value: 'paid', label: '已支付' },
  { value: 'cancelled', label: '已取消' },
  { value: 'refunded', label: '已退款' },
];

const STATUS_COLORS: Record<string, string> = {
  pending: 'bg-yellow-100 text-yellow-700',
  paid: 'bg-green-100 text-green-700',
  cancelled: 'bg-gray-100 text-gray-700',
  refunded: 'bg-red-100 text-red-700',
};

export default function OrdersPage() {
  const [items, setItems] = useState<Order[]>([]);
  const [total, setTotal] = useState(0);
  const [page, setPage] = useState(1);
  const [limit] = useState(10);
  const [loading, setLoading] = useState(true);
  const [filterEventId, setFilterEventId] = useState('');
  const [filterStatus, setFilterStatus] = useState('');
  const [filterAssigneeId, setFilterAssigneeId] = useState('');
  const [filterDateFrom, setFilterDateFrom] = useState('');
  const [filterDateTo, setFilterDateTo] = useState('');
  const [expandedId, setExpandedId] = useState<string | null>(null);
  const [detailItems, setDetailItems] = useState<OrderItem[]>([]);
  const [detailLoading, setDetailLoading] = useState(false);
  const [statusUpdateId, setStatusUpdateId] = useState<string | null>(null);
  const [statusUpdateValue, setStatusUpdateValue] = useState('');
  const [assignId, setAssignId] = useState<string | null>(null);
  const [assignValue, setAssignValue] = useState('');

  const loadData = useCallback(async () => {
    setLoading(true);
    try {
      const qs = buildQuery({
        page,
        limit,
        eventId: filterEventId || undefined,
        status: filterStatus || undefined,
        assigneeId: filterAssigneeId || undefined,
        dateFrom: filterDateFrom || undefined,
        dateTo: filterDateTo || undefined,
      });
      const res = await fetchApi<ListResponse>(`/orders${qs}`);
      setItems(res.data);
      setTotal(res.total);
    } catch (e) {
      console.error(e);
    } finally {
      setLoading(false);
    }
  }, [page, limit, filterEventId, filterStatus, filterAssigneeId, filterDateFrom, filterDateTo]);

  useEffect(() => {
    loadData();
  }, [loadData]);

  const totalPages = Math.ceil(total / limit);

  const handleExpand = async (order: Order) => {
    if (expandedId === order.id) {
      setExpandedId(null);
      setDetailItems([]);
      return;
    }
    setExpandedId(order.id);
    if (order.items && order.items.length > 0) {
      setDetailItems(order.items);
      return;
    }
    setDetailLoading(true);
    try {
      const res = await fetchApi<Order>(`/orders/${order.id}`);
      setDetailItems(res.items || []);
    } catch (e) {
      console.error(e);
      setDetailItems([]);
    } finally {
      setDetailLoading(false);
    }
  };

  const handleStatusUpdate = async (orderId: string) => {
    try {
      await fetchApi(`/orders/${orderId}/status`, {
        method: 'PUT',
        body: JSON.stringify({ status: statusUpdateValue }),
      });
      setStatusUpdateId(null);
      setStatusUpdateValue('');
      loadData();
    } catch (e) {
      console.error(e);
    }
  };

  const handleAssign = async (orderId: string) => {
    try {
      await fetchApi(`/orders/${orderId}/assign`, {
        method: 'PUT',
        body: JSON.stringify({ assigneeId: assignValue }),
      });
      setAssignId(null);
      setAssignValue('');
      loadData();
    } catch (e) {
      console.error(e);
    }
  };

  const statusLabel = (s: string) => STATUS_OPTIONS.find((o) => o.value === s)?.label || s;

  return (
    <div>
      <div className="flex items-center justify-between mb-6">
        <h1 className="text-2xl font-bold">订单管理</h1>
      </div>

      <div className="bg-white rounded-lg shadow p-4 mb-4 flex gap-4 items-end flex-wrap">
        <div>
          <label className="block text-xs text-gray-500 mb-1">活动ID</label>
          <input value={filterEventId} onChange={(e) => { setFilterEventId(e.target.value); setPage(1); }} placeholder="输入活动ID" className="border rounded px-3 py-1.5 text-sm" />
        </div>
        <div>
          <label className="block text-xs text-gray-500 mb-1">状态</label>
          <select value={filterStatus} onChange={(e) => { setFilterStatus(e.target.value); setPage(1); }} className="border rounded px-3 py-1.5 text-sm">
            {STATUS_OPTIONS.map((o) => <option key={o.value} value={o.value}>{o.label}</option>)}
          </select>
        </div>
        <div>
          <label className="block text-xs text-gray-500 mb-1">处理人ID</label>
          <input value={filterAssigneeId} onChange={(e) => { setFilterAssigneeId(e.target.value); setPage(1); }} placeholder="输入处理人ID" className="border rounded px-3 py-1.5 text-sm" />
        </div>
        <div>
          <label className="block text-xs text-gray-500 mb-1">开始日期</label>
          <input type="date" value={filterDateFrom} onChange={(e) => { setFilterDateFrom(e.target.value); setPage(1); }} className="border rounded px-3 py-1.5 text-sm" />
        </div>
        <div>
          <label className="block text-xs text-gray-500 mb-1">结束日期</label>
          <input type="date" value={filterDateTo} onChange={(e) => { setFilterDateTo(e.target.value); setPage(1); }} className="border rounded px-3 py-1.5 text-sm" />
        </div>
      </div>

      <div className="bg-white rounded-lg shadow overflow-hidden">
        {loading ? (
          <div className="p-8 text-center text-gray-400">加载中...</div>
        ) : (
          <table className="w-full text-sm">
            <thead className="bg-gray-50 text-gray-600">
              <tr>
                <th className="px-4 py-3 text-left">订单号</th>
                <th className="px-4 py-3 text-left">买家姓名</th>
                <th className="px-4 py-3 text-left">买家电话</th>
                <th className="px-4 py-3 text-left">总金额</th>
                <th className="px-4 py-3 text-left">状态</th>
                <th className="px-4 py-3 text-left">处理人</th>
                <th className="px-4 py-3 text-left">创建时间</th>
                <th className="px-4 py-3 text-left">操作</th>
              </tr>
            </thead>
            <tbody className="divide-y">
              {items.map((item) => (
                <React.Fragment key={item.id}>
                  <tr className="hover:bg-gray-50">
                    <td className="px-4 py-3 font-medium">{item.orderNo}</td>
                    <td className="px-4 py-3">{item.buyerName}</td>
                    <td className="px-4 py-3 text-gray-600">{item.buyerPhone}</td>
                    <td className="px-4 py-3">¥{Number(item.totalAmount).toFixed(2)}</td>
                    <td className="px-4 py-3">
                      <span className={`px-2 py-0.5 rounded text-xs ${STATUS_COLORS[item.status] || 'bg-gray-100 text-gray-700'}`}>
                        {statusLabel(item.status)}
                      </span>
                    </td>
                    <td className="px-4 py-3">{item.assignee?.name || item.assigneeId || '-'}</td>
                    <td className="px-4 py-3 text-xs text-gray-500">{new Date(item.createdAt).toLocaleString('zh-CN')}</td>
                    <td className="px-4 py-3 space-x-1">
                      <button onClick={() => handleExpand(item)} className="text-blue-600 hover:underline text-xs">
                        {expandedId === item.id ? '收起' : '详情'}
                      </button>
                      <button onClick={() => { setStatusUpdateId(item.id); setStatusUpdateValue(item.status); }} className="text-orange-600 hover:underline text-xs">状态</button>
                      <button onClick={() => { setAssignId(item.id); setAssignValue(item.assigneeId || ''); }} className="text-purple-600 hover:underline text-xs">分配</button>
                    </td>
                  </tr>
                  {expandedId === item.id && (
                    <tr>
                      <td colSpan={8} className="px-6 py-4 bg-gray-50">
                        {detailLoading ? (
                          <div className="text-gray-400 text-xs">加载明细...</div>
                        ) : detailItems.length > 0 ? (
                          <div>
                            <div className="text-xs font-medium mb-2 text-gray-600">订单明细</div>
                            <table className="w-full text-xs">
                              <thead>
                                <tr className="text-gray-500">
                                  <th className="text-left py-1 px-2">票种</th>
                                  <th className="text-left py-1 px-2">座位</th>
                                  <th className="text-left py-1 px-2">单价</th>
                                  <th className="text-left py-1 px-2">状态</th>
                                </tr>
                              </thead>
                              <tbody>
                                {detailItems.map((di) => (
                                  <tr key={di.id} className="border-t border-gray-200">
                                    <td className="py-1 px-2">{di.ticketType?.name || di.ticketTypeId}</td>
                                    <td className="py-1 px-2">{di.seat?.seatNo || '-'}</td>
                                    <td className="py-1 px-2">¥{Number(di.unitPrice).toFixed(2)}</td>
                                    <td className="py-1 px-2">{di.status}</td>
                                  </tr>
                                ))}
                              </tbody>
                            </table>
                          </div>
                        ) : (
                          <div className="text-gray-400 text-xs">暂无明细</div>
                        )}
                      </td>
                    </tr>
                  )}
                </React.Fragment>
              ))}
              {items.length === 0 && (
                <tr><td colSpan={8} className="px-4 py-8 text-center text-gray-400">暂无数据</td></tr>
              )}
            </tbody>
          </table>
        )}
        <div className="flex items-center justify-between px-4 py-3 border-t text-sm text-gray-600">
          <span>共 {total} 条</span>
          <div className="flex gap-2">
            <button onClick={() => setPage((p) => Math.max(1, p - 1))} disabled={page <= 1} className="px-3 py-1 border rounded disabled:opacity-50">上一页</button>
            <span className="px-3 py-1">{page} / {totalPages || 1}</span>
            <button onClick={() => setPage((p) => Math.min(totalPages, p + 1))} disabled={page >= totalPages} className="px-3 py-1 border rounded disabled:opacity-50">下一页</button>
          </div>
        </div>
      </div>

      {statusUpdateId && (
        <div className="fixed inset-0 bg-black/40 flex items-center justify-center z-50">
          <div className="bg-white rounded-lg shadow-lg w-full max-w-sm p-6">
            <h2 className="text-lg font-bold mb-4">更新订单状态</h2>
            <select value={statusUpdateValue} onChange={(e) => setStatusUpdateValue(e.target.value)} className="w-full border rounded px-3 py-2 text-sm mb-4">
              <option value="paid">已支付</option>
              <option value="cancelled">已取消</option>
              <option value="refunded">已退款</option>
            </select>
            <div className="flex justify-end gap-2">
              <button onClick={() => { setStatusUpdateId(null); setStatusUpdateValue(''); }} className="px-4 py-2 border rounded text-sm hover:bg-gray-50">取消</button>
              <button onClick={() => handleStatusUpdate(statusUpdateId)} className="px-4 py-2 bg-orange-600 text-white rounded text-sm hover:bg-orange-700">确认</button>
            </div>
          </div>
        </div>
      )}

      {assignId && (
        <div className="fixed inset-0 bg-black/40 flex items-center justify-center z-50">
          <div className="bg-white rounded-lg shadow-lg w-full max-w-sm p-6">
            <h2 className="text-lg font-bold mb-4">分配处理人</h2>
            <input value={assignValue} onChange={(e) => setAssignValue(e.target.value)} placeholder="输入处理人ID" className="w-full border rounded px-3 py-2 text-sm mb-4" />
            <div className="flex justify-end gap-2">
              <button onClick={() => { setAssignId(null); setAssignValue(''); }} className="px-4 py-2 border rounded text-sm hover:bg-gray-50">取消</button>
              <button onClick={() => handleAssign(assignId)} className="px-4 py-2 bg-purple-600 text-white rounded text-sm hover:bg-purple-700">确认</button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

// src/routes/orders/+page.svelte
<script lang="ts">
	import { trpc } from '$lib/trpc/client';
	import { onMount } from 'svelte';
	import { formatDateTime, formatMoney, statusBadge } from '$lib/utils';

	let page = 1, pageSize = 20;
	let total = 0, totalPages = 0;
	let items: any[] = [];
	let events: any[] = [];
	let ticketTypes: any[] = [];
	let stats: any = null;
	let loading = false;

	let filterEventId = '';
	let filterChannel = '';
	let filterStatus = '';
	let filterPayStatus = '';
	let keyword = '';
	let startDate = '';
	let endDate = '';

	let showCreateModal = false;
	let form: any = { items: [{ ticketTypeId: '', quantity: 1, unitPrice: '0' }] };

	async function loadEvents() {
		try {
			const ev = await trpc.event.list.query({ pageSize: 200 });
			events = ev.items;
		} catch {}
	}

	async function loadTicketTypes(eid?: string) {
		if (!eid) return;
		try {
			ticketTypes = await trpc.ticketType.summary.query({ eventId: eid });
		} catch {
			ticketTypes = [];
		}
	}

	async function load() {
		loading = true;
		try {
			const [res, st] = await Promise.all([
				trpc.order.list.query({
					page, pageSize,
					eventId: filterEventId || undefined,
					channel: filterChannel || undefined,
					status: filterStatus || undefined,
					paymentStatus: filterPayStatus || undefined,
					orderNo: keyword || undefined,
					dateRange: (startDate || endDate) ? { startDate: startDate || undefined, endDate: endDate || undefined } : undefined
				}),
				trpc.order.statistics.query({
					eventId: filterEventId || undefined,
					dateRange: (startDate || endDate) ? { startDate, endDate } : undefined
				})
			]);
			items = res.items;
			total = res.total;
			totalPages = res.totalPages;
			stats = st;
		} finally {
			loading = false;
		}
	}

	async function submit() {
		try {
			const res = await trpc.order.create.mutate({
				eventId: form.eventId,
				channel: form.channel || 'offline',
				buyerName: form.buyerName,
				buyerPhone: form.buyerPhone,
				buyerEmail: form.buyerEmail,
				paymentMethod: form.paymentMethod,
				paymentStatus: form.paymentStatus || 'unpaid',
				notes: form.notes,
				items: form.items.map((i: any) => ({
					ticketTypeId: i.ticketTypeId,
					quantity: Number(i.quantity) || 1,
					unitPrice: i.unitPrice || '0',
					holderName: i.holderName,
					holderPhone: i.holderPhone
				})).filter((i: any) => i.ticketTypeId)
			});
			alert('订单创建成功：' + res.order.orderNo);
			showCreateModal = false;
			form = { items: [{ ticketTypeId: '', quantity: 1, unitPrice: '0' }] };
			await load();
		} catch (e: any) {
			alert(e?.message ?? '创建失败');
		}
	}

	function addItem() {
		form.items.push({ ticketTypeId: ticketTypes[0]?.id ?? '', quantity: 1, unitPrice: ticketTypes[0]?.price ?? '0' });
	}
	function removeItem(idx: number) {
		form.items.splice(idx, 1);
	}

	onMount(async () => {
		await loadEvents();
		await load();
	});

	$effect(() => {
		load();
	});

	$effect(() => {
		if (form.eventId) loadTicketTypes(form.eventId);
	});
</script>

<div class="p-6 space-y-6">
	<div class="flex items-center justify-between">
		<div>
			<h1>购票订单</h1>
			<p class="text-sm text-slate-500 mt-1">订单从创建、支付、出票、核销到退款的完整状态管理</p>
		</div>
		<button class="btn-primary" on:click={() => (showCreateModal = true)}>🧾 新建订单</button>
	</div>

	{#if stats?.overview}
		<div class="grid grid-cols-2 md:grid-cols-4 gap-4">
			<div class="stat-card"><div class="stat-label">订单数</div><div class="stat-value">{stats.overview.orderCount}</div><div class="text-xs text-green-600 mt-1">支付 {stats.overview.paidOrderCount} 笔</div></div>
			<div class="stat-card"><div class="stat-label">总票数</div><div class="stat-value">{stats.overview.ticketCount ?? 0}</div></div>
			<div class="stat-card"><div class="stat-label">票面总额</div><div class="stat-value">¥{formatMoney(stats.overview.totalAmount)}</div></div>
			<div class="stat-card"><div class="stat-label">实收金额</div><div class="stat-value text-green-600">¥{formatMoney(stats.overview.paidAmount)}</div></div>
		</div>

		<div class="grid grid-cols-1 md:grid-cols-2 gap-4">
			<div class="card card-body">
				<h3 class="mb-3">按订单状态</h3>
				<div class="space-y-2">
					{#each stats.byStatus ?? [] as s}
						<div class="flex items-center gap-3 text-sm">
							{@const b = statusBadge(s.status)}
							<span class="w-28 {b.cls}">{b.label}</span>
							<span class="font-mono font-semibold">{s.count}</span>
							<span class="text-slate-500 ml-auto">¥{formatMoney(s.amount)}</span>
						</div>
					{/each}
				</div>
			</div>
			<div class="card card-body">
				<h3 class="mb-3">按渠道</h3>
				<div class="space-y-2">
					{#each stats.byChannel ?? [] as c}
						<div class="flex items-center gap-3 text-sm">
							<span class="w-28 tag">{c.channel}</span>
							<span class="font-mono font-semibold">{c.count}</span>
							<span class="text-slate-500 ml-auto">¥{formatMoney(c.amount)}</span>
						</div>
					{/each}
				</div>
			</div>
		</div>
	{/if}

	<div class="card">
		<div class="card-header">
			<div class="flex flex-wrap gap-3 items-center">
				<select class="select-input w-48" bind:value={filterEventId}>
					<option value="">全部活动</option>
					{#each events as e}<option value={e.event?.id ?? e.id}>{e.event?.name ?? e.name}</option>{/each}
				</select>
				<select class="select-input w-32" bind:value={filterChannel}>
					<option value="">全部渠道</option>
					<option value="official_web">官网</option>
					<option value="official_mini">小程序</option>
					<option value="official_app">APP</option>
					<option value="third_party">第三方</option>
					<option value="offline">线下</option>
					<option value="sponsor">赞助</option>
				</select>
				<select class="select-input w-32" bind:value={filterStatus}>
					<option value="">全部状态</option>
					<option value="created">待支付</option>
					<option value="paid">已支付</option>
					<option value="issued">已出票</option>
					<option value="partial_refund">部分退款</option>
					<option value="refunded">全部退款</option>
					<option value="cancelled">已取消</option>
				</select>
				<select class="select-input w-32" bind:value={filterPayStatus}>
					<option value="">支付状态</option>
					<option value="unpaid">未支付</option>
					<option value="pending">待确认</option>
					<option value="paid">已支付</option>
					<option value="refunded">已退款</option>
				</select>
				<input class="input w-48" placeholder="订单号/姓名/手机" bind:value={keyword} />
				<input class="input w-36" type="date" bind:value={startDate} />
				<input class="input w-36" type="date" bind:value={endDate} />
			</div>
		</div>
		<div class="table-wrap">
			<table class="data-table">
				<thead>
					<tr>
						<th>订单号</th>
						<th>渠道</th>
						<th>购票人</th>
						<th class="text-center">票数</th>
						<th class="text-right">票面</th>
						<th class="text-right">实付</th>
						<th>订单状态</th>
						<th>支付状态</th>
						<th>创建时间</th>
						<th class="text-right">操作</th>
					</tr>
				</thead>
				<tbody>
					{#if loading}
						<tr><td colspan="10" class="py-12 text-center text-slate-400">加载中...</td></tr>
					{:else if items.length === 0}
						<tr><td colspan="10" class="empty-state">暂无订单</td></tr>
					{:else}
						{#each items as o}
							<tr class="hover:bg-slate-50">
								<td class="font-mono text-xs text-slate-700">{o.orderNo}</td>
								<td><span class="tag">{o.channel}</span></td>
								<td>{o.buyerName ?? '-'}<div class="text-xs text-slate-500">{o.buyerPhone ?? ''}</div></td>
								<td class="text-center font-semibold">{o.totalQuantity}</td>
								<td class="text-right font-mono">¥{formatMoney(o.totalAmount)}</td>
								<td class="text-right font-mono font-semibold text-green-600">¥{formatMoney(o.paidAmount)}</td>
								<td>{@const b = statusBadge(o.status)}<span class={b.cls}>{b.label}</span></td>
								<td><span class="badge-{o.paymentStatus === 'paid' ? 'green' : o.paymentStatus === 'unpaid' ? 'gray' : o.paymentStatus === 'refunded' ? 'purple' : 'yellow'}">{o.paymentStatus}</span></td>
								<td class="text-xs text-slate-500">{formatDateTime(o.createdAt)}</td>
								<td class="text-right">
									<button class="btn-ghost !py-1 !px-2 text-xs">详情</button>
								</td>
							</tr>
						{/each}
					{/if}
				</tbody>
			</table>
		</div>
		<div class="pagination">
			<div class="text-sm text-slate-500">共 {total} 条 · 第 {page}/{totalPages || 1} 页</div>
			<div class="flex gap-2">
				<button class="btn-secondary !py-1" disabled={page <= 1} on:click={() => page--}>上一页</button>
				<button class="btn-secondary !py-1" disabled={page >= totalPages} on:click={() => page++}>下一页</button>
			</div>
		</div>
	</div>
</div>

{#if showCreateModal}
	<div class="fixed inset-0 bg-black/40 flex items-center justify-center z-50 p-4">
		<div class="card w-full max-w-3xl max-h-[90vh] overflow-y-auto">
			<div class="card-header"><h3>新建订单</h3><button class="btn-ghost !p-1" on:click={() => (showCreateModal = false)}>✕</button></div>
			<div class="card-body space-y-5">
				<div class="grid grid-cols-2 gap-4">
					<div>
						<label class="label">活动 *</label>
						<select class="select-input" bind:value={form.eventId} required>
							<option value="">请选择</option>
							{#each events as e}<option value={e.event?.id ?? e.id}>{e.event?.name ?? e.name}</option>{/each}
						</select>
					</div>
					<div>
						<label class="label">渠道</label>
						<select class="select-input" bind:value={form.channel}>
							<option value="offline">线下</option>
							<option value="official_web">官网</option>
							<option value="official_mini">小程序</option>
							<option value="official_app">APP</option>
							<option value="third_party">第三方</option>
							<option value="sponsor">赞助</option>
						</select>
					</div>
				</div>
				<div class="grid grid-cols-3 gap-4">
					<div><label class="label">购票人姓名</label><input class="input" bind:value={form.buyerName} /></div>
					<div><label class="label">手机</label><input class="input" bind:value={form.buyerPhone} /></div>
					<div><label class="label">邮箱</label><input class="input" bind:value={form.buyerEmail} /></div>
				</div>
				<div class="grid grid-cols-2 gap-4">
					<div>
						<label class="label">支付方式</label>
						<select class="select-input" bind:value={form.paymentMethod}>
							<option value="">未支付</option>
							<option value="wechat">微信</option>
							<option value="alipay">支付宝</option>
							<option value="cash">现金</option>
							<option value="bank">银行转账</option>
						</select>
					</div>
					<div>
						<label class="label">支付状态</label>
						<select class="select-input" bind:value={form.paymentStatus}>
							<option value="unpaid">未支付</option>
							<option value="paid">已支付</option>
						</select>
					</div>
				</div>

				<div>
					<div class="flex items-center justify-between mb-2">
						<label class="label !mb-0">购票明细</label>
						<button type="button" class="btn-secondary !py-1" on:click={addItem} disabled={!form.eventId}>➕ 加一行</button>
					</div>
					<div class="border border-slate-200 rounded-lg overflow-hidden">
						<table class="w-full text-sm">
							<thead><tr class="bg-slate-50">
								<th class="text-left px-3 py-2 font-medium text-slate-600">票种</th>
								<th class="w-24 text-left px-3 py-2 font-medium text-slate-600">数量</th>
								<th class="w-32 text-left px-3 py-2 font-medium text-slate-600">单价</th>
								<th class="w-36 text-left px-3 py-2 font-medium text-slate-600">持票人</th>
								<th class="w-32 text-left px-3 py-2 font-medium text-slate-600">手机</th>
								<th class="w-10"></th>
							</tr></thead>
							<tbody>
								{#each form.items as it, idx}
									<tr class="border-t border-slate-100">
										<td class="p-2">
											<select class="select-input !py-1" bind:value={it.ticketTypeId} on:change={() => {
												const tt = ticketTypes.find(t => t.id === it.ticketTypeId);
												if (tt) it.unitPrice = tt.price;
											}}>
												<option value="">选择票种</option>
												{#each ticketTypes as t}<option value={t.id}>{t.name} ({t.code}) ¥{t.price}</option>{/each}
											</select>
										</td>
										<td class="p-2"><input class="input !py-1" type="number" min="1" bind:value={it.quantity} /></td>
										<td class="p-2"><input class="input !py-1 font-mono" bind:value={it.unitPrice} /></td>
										<td class="p-2"><input class="input !py-1" bind:value={it.holderName} placeholder="可选" /></td>
										<td class="p-2"><input class="input !py-1" bind:value={it.holderPhone} placeholder="可选" /></td>
										<td class="p-2"><button type="button" class="btn-ghost !p-1 text-red-500" disabled={form.items.length <= 1} on:click={() => removeItem(idx)}>✕</button></td>
									</tr>
								{/each}
							</tbody>
						</table>
					</div>
				</div>

				<div><label class="label">备注</label><textarea class="input min-h-[60px]" bind:value={form.notes} /></div>

				<div class="flex justify-end gap-2 pt-2">
					<button class="btn-secondary" on:click={() => (showCreateModal = false)}>取消</button>
					<button class="btn-primary" on:click={submit}>提交订单</button>
				</div>
			</div>
		</div>
	</div>
{/if}
