// src/routes/auth/login/+page.svelte
<script lang="ts">
	import { auth } from '$lib/stores/auth';

	let email = 'admin@example.com';
	let password = 'admin123';
	let error = '';
	let submitting = false;

	async function handleLogin() {
		submitting = true;
		error = '';
		const result = await auth.login(email, password);
		if (!result.success) {
			error = result.error ?? '登录失败';
		}
		submitting = false;
	}
</script>

<div class="min-h-screen flex items-center justify-center bg-gradient-to-br from-primary-50 to-primary-100 py-12 px-4 sm:px-6 lg:px-8">
	<div class="max-w-md w-full space-y-8">
		<div>
			<div class="mx-auto h-16 w-16 bg-primary-600 rounded-2xl flex items-center justify-center">
				<svg class="h-8 w-8 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
					<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6"></path>
				</svg>
			</div>
			<h2 class="mt-6 text-center text-3xl font-extrabold text-gray-900">民宿房态管理协同台</h2>
			<p class="mt-2 text-center text-sm text-gray-600">高效协同管理房态、订单与运营</p>
		</div>
		<form class="mt-8 space-y-6 card card-body" on:submit|preventDefault={handleLogin}>
			<div class="space-y-4">
				<div>
					<label class="label" for="email">邮箱</label>
					<input id="email" type="email" bind:value={email} class="input" required placeholder="admin@example.com" />
				</div>
				<div>
					<label class="label" for="password">密码</label>
					<input id="password" type="password" bind:value={password} class="input" required placeholder="admin123" />
				</div>
			</div>

			{#if error}
				<div class="rounded-md bg-red-50 p-4 border border-red-200">
					<div class="text-sm text-red-700">{error}</div>
				</div>
			{/if}

			<div>
				<button type="submit" class="w-full btn-primary" disabled={submitting}>
					{submitting ? '登录中...' : '登 录'}
				</button>
			</div>

			<div class="text-center">
				<a href="/auth/register" class="text-sm text-primary-600 hover:text-primary-500">没有账号？立即注册</a>
			</div>

			<div class="mt-4 p-3 bg-blue-50 rounded-md text-xs text-blue-700 border border-blue-100">
				<div class="font-semibold mb-1">首次使用提示：</div>
				<div>首次注册的用户将自动成为管理员。您也可以使用上方默认的演示账号体验。</div>
			</div>
		</form>
	</div>
</div>

// packages/frontend/src/app/login/page.tsx
'use client';

import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { useAuth } from '@/lib/auth';

export default function LoginPage() {
  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');
  const [error, setError] = useState('');
  const [submitting, setSubmitting] = useState(false);
  const { login } = useAuth();
  const router = useRouter();

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError('');
    setSubmitting(true);
    try {
      await login(username, password);
      router.push('/dashboard');
    } catch {
      setError('用户名或密码错误');
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <div className="min-h-screen flex items-center justify-center bg-surface-900 px-4">
      <div className="w-full max-w-md">
        <div className="text-center mb-8">
          <div className="inline-flex items-center justify-center w-16 h-16 rounded-2xl bg-primary-500/10 mb-4">
            <svg className="w-8 h-8 text-primary-500" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 21V5a2 2 0 00-2-2H7a2 2 0 00-2 2v16m14 0h2m-2 0h-5m-9 0H3m2 0h5M9 7h1m-1 4h1m4-4h1m-1 4h1m-5 10v-5a1 1 0 011-1h2a1 1 0 011 1v5m-4 0h4" />
            </svg>
          </div>
          <h1 className="text-2xl font-bold text-surface-50">药店连锁用药回访</h1>
          <p className="text-surface-200 mt-2">任务分派台 · 请登录</p>
        </div>
        <form onSubmit={handleSubmit} className="bg-surface-800 rounded-xl p-6 shadow-xl border border-surface-700">
          {error && (
            <div className="mb-4 p-3 bg-red-500/10 border border-red-500/30 rounded-lg text-red-400 text-sm">{error}</div>
          )}
          <div className="space-y-4">
            <div>
              <label className="block text-sm font-medium text-surface-200 mb-1.5">用户名</label>
              <input
                type="text"
                value={username}
                onChange={(e) => setUsername(e.target.value)}
                className="w-full px-4 py-2.5 bg-surface-900 border border-surface-700 rounded-lg text-surface-50 placeholder-surface-200 focus:outline-none focus:border-primary-500 focus:ring-1 focus:ring-primary-500 transition-colors"
                placeholder="请输入用户名"
                required
              />
            </div>
            <div>
              <label className="block text-sm font-medium text-surface-200 mb-1.5">密码</label>
              <input
                type="password"
                value={password}
                onChange={(e) => setPassword(e.target.value)}
                className="w-full px-4 py-2.5 bg-surface-900 border border-surface-700 rounded-lg text-surface-50 placeholder-surface-200 focus:outline-none focus:border-primary-500 focus:ring-1 focus:ring-primary-500 transition-colors"
                placeholder="请输入密码"
                required
              />
            </div>
          </div>
          <button
            type="submit"
            disabled={submitting}
            className="w-full mt-6 py-2.5 bg-primary-600 hover:bg-primary-700 disabled:opacity-50 disabled:cursor-not-allowed text-white font-medium rounded-lg transition-colors"
          >
            {submitting ? '登录中...' : '登 录'}
          </button>
        </form>
      </div>
    </div>
  );
}
