// resources/js/Components/Pagination.vue
<script setup>
import { computed } from 'vue'
import { ChevronLeft, ChevronRight, Home } from 'lucide-vue-next'

const props = defineProps({
  links: {
    type: Array,
    default: () => [],
  },
  meta: {
    type: Object,
    default: () => ({}),
  },
})

const emit = defineEmits(['page-change'])

const currentPage = computed(() => props.meta.current_page || 1)
const lastPage = computed(() => props.meta.last_page || 1)
const total = computed(() => props.meta.total || 0)
const perPage = computed(() => props.meta.per_page || 10)
const from = computed(() => total.value === 0 ? 0 : (currentPage.value - 1) * perPage.value + 1)
const to = computed(() => Math.min(currentPage.value * perPage.value, total.value))

const pageNumbers = computed(() => {
  const totalP = lastPage.value
  const current = currentPage.value
  const pages = []
  if (totalP <= 7) {
    for (let i = 1; i <= totalP; i++) pages.push({ num: i, active: i === current })
  } else {
    pages.push({ num: 1, active: current === 1 })
    if (current > 3) pages.push({ num: '...' })
    for (let i = Math.max(2, current - 1); i <= Math.min(totalP - 1, current + 1); i++) {
      pages.push({ num: i, active: i === current })
    }
    if (current < totalP - 2) pages.push({ num: '...' })
    pages.push({ num: totalP, active: current === totalP })
  }
  return pages
})

const goToPage = (page) => {
  if (page === '...' || page < 1 || page > lastPage.value) return
  emit('page-change', page)
}
</script>

<template>
  <div class="flex flex-col sm:flex-row sm:items-center justify-between gap-4 w-full">
    <div class="flex items-center gap-4">
      <p class="text-sm text-gray-600">
        显示第
        <span class="font-semibold text-gray-900">{{ from }}</span>
        至
        <span class="font-semibold text-gray-900">{{ to }}</span>
        条，共
        <span class="font-semibold text-gray-900">{{ total }}</span>
        条记录
      </p>
    </div>

    <div class="flex items-center gap-1">
      <button
        type="button"
        @click="goToPage(1)"
        :disabled="currentPage <= 1"
        :class="[
          'inline-flex items-center justify-center p-2 rounded-lg text-sm border transition-all',
          currentPage <= 1
            ? 'border-gray-100 text-gray-300 cursor-not-allowed bg-white'
            : 'border-gray-200 text-gray-600 hover:text-gray-900 hover:bg-gray-50 bg-white',
        ]"
        title="首页"
      >
        <Home class="w-4 h-4" />
      </button>
      <button
        type="button"
        @click="goToPage(currentPage - 1)"
        :disabled="currentPage <= 1"
        :class="[
          'inline-flex items-center justify-center p-2 rounded-lg text-sm border transition-all',
          currentPage <= 1
            ? 'border-gray-100 text-gray-300 cursor-not-allowed bg-white'
            : 'border-gray-200 text-gray-600 hover:text-gray-900 hover:bg-gray-50 bg-white',
        ]"
        title="上一页"
      >
        <ChevronLeft class="w-4 h-4" />
      </button>

      <template v-for="(page, idx) in pageNumbers" :key="idx">
        <span
          v-if="page.num === '...'"
          class="px-2 py-2 text-sm text-gray-400"
        >
          ...
        </span>
        <button
          v-else
          type="button"
          @click="goToPage(page.num)"
          :class="[
            'min-w-[38px] h-9 px-3 rounded-lg text-sm font-semibold border transition-all',
            page.active
              ? 'bg-blue-600 border-blue-600 text-white shadow-sm shadow-blue-600/20'
              : 'bg-white border-gray-200 text-gray-600 hover:text-gray-900 hover:bg-gray-50',
          ]"
        >
          {{ page.num }}
        </button>
      </template>

      <button
        type="button"
        @click="goToPage(currentPage + 1)"
        :disabled="currentPage >= lastPage"
        :class="[
          'inline-flex items-center justify-center p-2 rounded-lg text-sm border transition-all',
          currentPage >= lastPage
            ? 'border-gray-100 text-gray-300 cursor-not-allowed bg-white'
            : 'border-gray-200 text-gray-600 hover:text-gray-900 hover:bg-gray-50 bg-white',
        ]"
        title="下一页"
      >
        <ChevronRight class="w-4 h-4" />
      </button>
      <button
        type="button"
        @click="goToPage(lastPage)"
        :disabled="currentPage >= lastPage"
        :class="[
          'inline-flex items-center justify-center p-2 rounded-lg text-sm border transition-all',
          currentPage >= lastPage
            ? 'border-gray-100 text-gray-300 cursor-not-allowed bg-white'
            : 'border-gray-200 text-gray-600 hover:text-gray-900 hover:bg-gray-50 bg-white',
        ]"
        title="末页"
      >
        <svg class="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
          <path d="m13 17 5-5-5-5M6 17l5-5-5-5" />
        </svg>
      </button>
    </div>
  </div>
</template>

// src/components/Pagination.tsx
import { ChevronLeft, ChevronRight, ChevronsLeft, ChevronsRight } from 'lucide-react';
import { cn } from '@/lib/utils';

interface PaginationProps {
  page: number;
  pageSize: number;
  total: number;
  onPageChange: (page: number) => void;
  onPageSizeChange?: (size: number) => void;
}

export function Pagination({ page, pageSize, total, onPageChange, onPageSizeChange }: PaginationProps) {
  const totalPages = Math.ceil(total / pageSize);
  const startItem = total > 0 ? (page - 1) * pageSize + 1 : 0;
  const endItem = Math.min(page * pageSize, total);

  const pageNumbers = () => {
    const pages: (number | string)[] = [];
    const maxVisible = 5;

    if (totalPages <= maxVisible) {
      for (let i = 1; i <= totalPages; i++) pages.push(i);
    } else {
      if (page <= 3) {
        for (let i = 1; i <= 4; i++) pages.push(i);
        pages.push('...');
        pages.push(totalPages);
      } else if (page >= totalPages - 2) {
        pages.push(1);
        pages.push('...');
        for (let i = totalPages - 3; i <= totalPages; i++) pages.push(i);
      } else {
        pages.push(1);
        pages.push('...');
        for (let i = page - 1; i <= page + 1; i++) pages.push(i);
        pages.push('...');
        pages.push(totalPages);
      }
    }

    return pages;
  };

  return (
    <div className="flex items-center justify-between px-4 py-3 bg-white border-t border-gray-200">
      <div className="flex items-center gap-2 text-sm text-gray-600">
        <span>显示 {startItem}-{endItem} 条，共 {total} 条</span>
        {onPageSizeChange && (
          <select
            value={pageSize}
            onChange={(e) => onPageSizeChange(Number(e.target.value))}
            className="ml-2 px-2 py-1 border border-gray-200 rounded text-sm focus:outline-none focus:ring-2 focus:ring-primary-500"
          >
            <option value={10}>10条/页</option>
            <option value={20}>20条/页</option>
            <option value={50}>50条/页</option>
          </select>
        )}
      </div>

      <div className="flex items-center gap-1">
        <button
          onClick={() => onPageChange(1)}
          disabled={page === 1}
          className={cn(
            'p-1.5 rounded border border-gray-200 text-gray-600 hover:bg-gray-50 disabled:opacity-50 disabled:cursor-not-allowed transition-colors'
          )}
        >
          <ChevronsLeft className="w-4 h-4" />
        </button>
        <button
          onClick={() => onPageChange(page - 1)}
          disabled={page === 1}
          className={cn(
            'p-1.5 rounded border border-gray-200 text-gray-600 hover:bg-gray-50 disabled:opacity-50 disabled:cursor-not-allowed transition-colors'
          )}
        >
          <ChevronLeft className="w-4 h-4" />
        </button>

        {pageNumbers().map((p, i) => (
          typeof p === 'number' ? (
            <button
              key={i}
              onClick={() => onPageChange(p)}
              className={cn(
                'min-w-9 h-9 px-3 rounded text-sm font-medium transition-colors',
                page === p
                  ? 'bg-primary-600 text-white'
                  : 'border border-gray-200 text-gray-600 hover:bg-gray-50'
              )}
            >
              {p}
            </button>
          ) : (
            <span key={i} className="px-2 text-gray-400">...</span>
          )
        ))}

        <button
          onClick={() => onPageChange(page + 1)}
          disabled={page === totalPages}
          className={cn(
            'p-1.5 rounded border border-gray-200 text-gray-600 hover:bg-gray-50 disabled:opacity-50 disabled:cursor-not-allowed transition-colors'
          )}
        >
          <ChevronRight className="w-4 h-4" />
        </button>
        <button
          onClick={() => onPageChange(totalPages)}
          disabled={page === totalPages}
          className={cn(
            'p-1.5 rounded border border-gray-200 text-gray-600 hover:bg-gray-50 disabled:opacity-50 disabled:cursor-not-allowed transition-colors'
          )}
        >
          <ChevronsRight className="w-4 h-4" />
        </button>
      </div>
    </div>
  );
}
