// src/lib/components/ui/DataTable.svelte
<script lang="ts">
	import { cn } from '$lib/utils/cn';
	import { Checkbox } from '.';
	import type { ComponentType, SvelteComponentTyped } from 'svelte';
	import { ChevronUp, ChevronDown } from 'lucide-svelte';

	export type Column<T> = {
		key: keyof T | string;
		title: string;
		width?: string;
		align?: 'left' | 'center' | 'right';
		sortable?: boolean;
		render?: (row: T, index: number) => unknown;
		className?: string;
	};

	export let data: T[] = [];
	export let columns: Column<T>[] = [];
	export let selectable = false;
	export let rowClickable = false;
	export let emptyText = '暂无数据';
	export let selected: Set<string | number> = new Set();
	export let rowKey: keyof T | ((row: T) => string | number) = 'id' as keyof T;
	export let sortKey: string | undefined = undefined;
	export let sortOrder: 'asc' | 'desc' | undefined = undefined;
	export let loading = false;
	export let stripe = true;
	export let compact = false;
	export let hoverable = true;
	export let bordered = true;
	let className: string | undefined = undefined;
	export { className as class };
	export let noWrap = true;

	function getRowKey(row: T, index: number): string | number {
		if (typeof rowKey === 'function') return rowKey(row);
		const val = (row as Record<string, unknown>)[rowKey as string];
		return val !== undefined && val !== null ? (val as string | number) : index;
	}

	$: allSelected = selectable && data.length > 0 && data.every((row, i) => selected.has(getRowKey(row, i)));
	$: someSelected = selectable && data.some((row, i) => selected.has(getRowKey(row, i))) && !allSelected;

	function toggleAll() {
		if (allSelected) {
			selected.clear();
		} else {
			data.forEach((row, i) => selected.add(getRowKey(row, i)));
		}
		selected = new Set(selected);
	}

	function toggleRow(row: T, index: number) {
		const key = getRowKey(row, index);
		if (selected.has(key)) {
			selected.delete(key);
		} else {
			selected.add(key);
		}
		selected = new Set(selected);
	}

	function handleRowClick(row: T, index: number, e: MouseEvent) {
		if (rowClickable) {
			dispatch('rowClick', { row, index, event: e });
		}
	}

	function handleSort(key: string) {
		const col = columns.find((c) => c.key === key);
		if (!col?.sortable) return;
		if (sortKey === key) {
			sortOrder = sortOrder === 'asc' ? 'desc' : sortOrder === 'desc' ? undefined : 'asc';
			if (!sortOrder) sortKey = undefined;
		} else {
			sortKey = key;
			sortOrder = 'asc';
		}
		dispatch('sort', { key, order: sortOrder });
	}

	import { createEventDispatcher } from 'svelte';
	const dispatch = createEventDispatcher<{
		rowClick: { row: T; index: number; event: MouseEvent };
		sort: { key: string; order: 'asc' | 'desc' | undefined };
		selectionChange: Set<string | number>;
	}>();

	$: dispatch('selectionChange', selected);

	function getCellValue(row: T, col: Column<T>): unknown {
		const key = String(col.key);
		return (row as Record<string, unknown>)[key];
	}
</script>

<div class={cn('w-full overflow-hidden rounded-xl bg-industrial-800', bordered && 'border border-industrial-700', className)}>
	<div class="overflow-x-auto">
		<table class="w-full border-collapse">
			<thead>
				<tr class="bg-industrial-900/60 border-b border-industrial-700">
					{#if selectable}
						<th class="w-12 px-4 py-3 text-left">
							<Checkbox
								checked={allSelected}
								indeterminate={someSelected}
								on:change={toggleAll}
							/>
						</th>
					{/if}
					{#each columns as col}
						<th
							class={cn(
								'px-4 text-xs font-semibold uppercase tracking-wider text-industrial-400',
								compact ? 'py-2.5' : 'py-3.5',
								col.align === 'center' && 'text-center',
								col.align === 'right' && 'text-right',
								col.className,
								col.sortable && 'cursor-pointer select-none hover:text-industrial-200 transition-colors'
							)}
							style={col.width ? `width: ${col.width}; min-width: ${col.width}` : undefined}
							on:click={() => handleSort(String(col.key))}
						>
							<div class={cn(
								'inline-flex items-center gap-1',
								col.align === 'center' && 'justify-center w-full',
								col.align === 'right' && 'justify-end w-full'
							)}>
								{col.title}
								{#if col.sortable}
									<span class="relative w-3 h-3">
										<ChevronUp
											class={cn(
												'absolute -top-1 left-0 w-3 h-3 transition-colors',
												sortKey === col.key && sortOrder === 'asc' ? 'text-primary-400' : 'text-industrial-600'
											)}
										/>
										<ChevronDown
											class={cn(
												'absolute top-0.5 left-0 w-3 h-3 transition-colors',
												sortKey === col.key && sortOrder === 'desc' ? 'text-primary-400' : 'text-industrial-600'
											)}
										/>
									</span>
								{/if}
							</div>
						</th>
					{/each}
					{#if $$slots.actions}
						<th class="px-4 text-xs font-semibold uppercase tracking-wider text-industrial-400 text-right w-28">
							操作
						</th>
					{/if}
				</tr>
			</thead>
			<tbody class="divide-y divide-industrial-700/60">
				{#if loading}
					<tr>
						<td
							colspan={columns.length + (selectable ? 1 : 0) + ($$slots.actions ? 1 : 0)}
							class="px-4 py-12 text-center"
						>
							<div class="flex flex-col items-center gap-3">
								<svg class="animate-spin w-8 h-8 text-primary-400" viewBox="0 0 24 24" fill="none">
									<circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4" />
									<path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z" />
								</svg>
								<span class="text-sm text-industrial-400">加载中...</span>
							</div>
						</td>
					</tr>
				{:else if data.length === 0}
					<tr>
						<td
							colspan={columns.length + (selectable ? 1 : 0) + ($$slots.actions ? 1 : 0)}
							class="px-4 py-16 text-center"
						>
							<div class="flex flex-col items-center gap-3">
								<svg class="w-12 h-12 text-industrial-700" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5">
									<path d="M20 13V6a2 2 0 00-2-2H6a2 2 0 00-2 2v7m16 0v5a2 2 0 01-2 2H6a2 2 0 01-2-2v-5m16 0h-2.586a1 1 0 00-.707.293l-2.414 2.414a1 1 0 01-.707.293h-3.172a1 1 0 01-.707-.293l-2.414-2.414A1 1 0 006.586 13H4" />
								</svg>
								<span class="text-sm text-industrial-500">{emptyText}</span>
								{#if $$slots.emptyExtra}
									<div class="mt-1">
										<slot name="emptyExtra" />
									</div>
								{/if}
							</div>
						</td>
					</tr>
				{:else}
					{#each data as row, index}
						{@const key = getRowKey(row, index)}
						<tr
							class={cn(
								'transition-colors duration-150',
								stripe && index % 2 === 1 && 'bg-industrial-800/30',
								hoverable && !selectable && 'hover:bg-industrial-700/30',
								selectable && selected.has(key) && 'bg-primary-600/10',
								(rowClickable || selectable) && 'cursor-pointer'
							)}
							on:click={(e) => handleRowClick(row, index, e)}
						>
							{#if selectable}
								<td class="px-4 py-3" on:click|stopPropagation>
									<Checkbox
										checked={selected.has(key)}
										on:change={() => toggleRow(row, index)}
									/>
								</td>
							{/if}
							{#each columns as col}
								<td
									class={cn(
										'px-4 text-sm text-industrial-200',
										compact ? 'py-2.5' : 'py-3.5',
										noWrap && 'whitespace-nowrap',
										col.align === 'center' && 'text-center',
										col.align === 'right' && 'text-right font-numeric',
										col.className
									)}
								>
									{#if col.render}
										{@const rendered = col.render(row, index)}
										{rendered}
									{:else}
										{getCellValue(row, col)}
									{/if}
								</td>
							{/each}
							{#if $$slots.actions}
								<td class="px-4 py-3 text-right whitespace-nowrap" on:click|stopPropagation>
									<div class="inline-flex items-center gap-1 justify-end">
										<slot name="actions" {row} {index} />
									</div>
								</td>
							{/if}
						</tr>
					{/each}
				{/if}
			</tbody>
		</table>
	</div>
	{#if $$slots.footer}
		<div class="px-4 py-3 border-t border-industrial-700 bg-industrial-900/30">
			<slot name="footer" />
		</div>
	{/if}
</div>

// apps/web/components/ui/DataTable.tsx
"use client";

import { useState, useMemo } from "react";
import { ChevronUp, ChevronDown, ChevronsUpDown } from "lucide-react";
import { cn } from "@/lib/utils";

export interface Column<T> {
  key: keyof T | string;
  title: string;
  render?: (row: T, index: number) => React.ReactNode;
  sortable?: boolean;
  width?: string;
  align?: "left" | "center" | "right";
}

interface DataTableProps<T> {
  columns: Column<T>[];
  data: T[];
  rowKey: keyof T | ((row: T) => string);
  selectable?: boolean;
  selectedKeys?: string[];
  onSelectionChange?: (keys: string[]) => void;
  onRowClick?: (row: T) => void;
  emptyText?: string;
  className?: string;
  getRowClassName?: (row: T, index: number) => string;
}

type SortDirection = "asc" | "desc" | null;

export function DataTable<T>({
  columns,
  data,
  rowKey,
  selectable = false,
  selectedKeys = [],
  onSelectionChange,
  onRowClick,
  emptyText = "暂无数据",
  className,
  getRowClassName,
}: DataTableProps<T>) {
  const [sortKey, setSortKey] = useState<string | null>(null);
  const [sortDirection, setSortDirection] = useState<SortDirection>(null);

  const getRowKey = (row: T): string => {
    if (typeof rowKey === "function") {
      return rowKey(row);
    }
    return String(row[rowKey]);
  };

  const sortedData = useMemo(() => {
    if (!sortKey || !sortDirection) return data;

    return [...data].sort((a, b) => {
      const aValue = a[sortKey as keyof T];
      const bValue = b[sortKey as keyof T];

      if (aValue === null || aValue === undefined) return 1;
      if (bValue === null || bValue === undefined) return -1;

      if (typeof aValue === "number" && typeof bValue === "number") {
        return sortDirection === "asc" ? aValue - bValue : bValue - aValue;
      }

      const aStr = String(aValue);
      const bStr = String(bValue);

      return sortDirection === "asc"
        ? aStr.localeCompare(bStr)
        : bStr.localeCompare(aStr);
    });
  }, [data, sortKey, sortDirection]);

  const handleSort = (key: string) => {
    if (sortKey === key) {
      if (sortDirection === "asc") {
        setSortDirection("desc");
      } else if (sortDirection === "desc") {
        setSortDirection(null);
        setSortKey(null);
      }
    } else {
      setSortKey(key);
      setSortDirection("asc");
    }
  };

  const allSelected =
    selectable && data.length > 0 && selectedKeys.length === data.length;
  const someSelected =
    selectable && selectedKeys.length > 0 && selectedKeys.length < data.length;

  const handleSelectAll = () => {
    if (!onSelectionChange) return;
    if (allSelected) {
      onSelectionChange([]);
    } else {
      onSelectionChange(data.map((row) => getRowKey(row)));
    }
  };

  const handleSelectRow = (key: string, checked: boolean) => {
    if (!onSelectionChange) return;
    if (checked) {
      onSelectionChange([...selectedKeys, key]);
    } else {
      onSelectionChange(selectedKeys.filter((k) => k !== key));
    }
  };

  const renderSortIcon = (key: string, sortable?: boolean) => {
    if (!sortable) return null;

    const isActive = sortKey === key;

    if (!isActive) {
      return (
        <ChevronsUpDown className="ml-1 h-3 w-3 text-muted-foreground/50" />
      );
    }

    return sortDirection === "asc" ? (
      <ChevronUp className="ml-1 h-3 w-3 text-primary" />
    ) : (
      <ChevronDown className="ml-1 h-3 w-3 text-primary" />
    );
  };

  return (
    <div className={cn("w-full overflow-auto", className)}>
      <table className="w-full caption-bottom text-sm">
        <thead className="[&_tr]:border-b">
          <tr className="border-b transition-colors hover:bg-muted/50">
            {selectable && (
              <th className="h-12 w-12 px-4 text-left">
                <input
                  type="checkbox"
                  checked={allSelected}
                  ref={(el) => {
                    if (el) el.indeterminate = someSelected;
                  }}
                  onChange={handleSelectAll}
                  className="h-4 w-4 rounded border-input text-primary focus:ring-primary"
                />
              </th>
            )}
            {columns.map((column) => (
              <th
                key={String(column.key)}
                className={cn(
                  "h-12 px-4 text-left align-middle font-medium text-muted-foreground",
                  column.align === "center" && "text-center",
                  column.align === "right" && "text-right",
                  column.sortable && "cursor-pointer select-none"
                )}
                style={{ width: column.width }}
                onClick={() => column.sortable && handleSort(String(column.key))}
              >
                <span className="inline-flex items-center">
                  {column.title}
                  {renderSortIcon(String(column.key), column.sortable)}
                </span>
              </th>
            ))}
          </tr>
        </thead>
        <tbody className="[&_tr:last-child]:border-0">
          {sortedData.length === 0 ? (
            <tr>
              <td
                colSpan={columns.length + (selectable ? 1 : 0)}
                className="h-24 text-center text-muted-foreground"
              >
                {emptyText}
              </td>
            </tr>
          ) : (
            sortedData.map((row, index) => {
              const key = getRowKey(row);
              const isSelected = selectedKeys.includes(key);

              return (
                <tr
                  key={key}
                  className={cn(
                    "border-b transition-colors hover:bg-muted/50",
                    isSelected && "bg-primary/5",
                    onRowClick && "cursor-pointer",
                    getRowClassName?.(row, index)
                  )}
                  onClick={() => onRowClick?.(row)}
                >
                  {selectable && (
                    <td className="p-4 align-middle" onClick={(e) => e.stopPropagation()}>
                      <input
                        type="checkbox"
                        checked={isSelected}
                        onChange={(e) => handleSelectRow(key, e.target.checked)}
                        className="h-4 w-4 rounded border-input text-primary focus:ring-primary"
                      />
                    </td>
                  )}
                  {columns.map((column) => (
                    <td
                      key={String(column.key)}
                      className={cn(
                        "p-4 align-middle",
                        column.align === "center" && "text-center",
                        column.align === "right" && "text-right"
                      )}
                    >
                      {column.render
                        ? column.render(row, index)
                        : String(row[column.key as keyof T] ?? "")}
                    </td>
                  ))}
                </tr>
              );
            })
          )}
        </tbody>
      </table>
    </div>
  );
}
