// src/routes/(app)/exceptions/+page.svelte
<script lang="ts">
	import { trpcClient } from '$lib/trpc/client';
	import { onMount } from 'svelte';
	import { EXCEPTION_STATUS_LABELS, EXCEPTION_TYPE_LABELS, type ExceptionStatusType, type ExceptionTypeType } from '$lib/types';

	let exceptions: any[] = [];
	let users: any[] = [];
	let properties: any[] = [];
	let loading = true;
	let filterStatus = '' as ExceptionStatusType | '';
	let filterType = '' as ExceptionTypeType | '';
	let showModal = false;
	let showDetail = false;
	let currentEx: any = null;
	let editData: any = {};
	let selectedRespUserId = '';

	async function loadData() {
		loading = true;
		try {
			const [e, u, p] = await Promise.all([
				trpcClient.exception.list.query({ status: filterStatus || undefined, type: filterType || undefined }),
				trpcClient.auth.list.query(),
				trpcClient.property.list.query({ status: 'active' })
			]);
			exceptions = e; users = u; properties = p;
		} finally { loading = false; }
	}
	onMount(loadData);

	async function runDetect() {
		await trpcClient.exception.runAutoDetect.mutate();
		loadData();
	}
	async function openDetail(ex: any) {
		const d = await trpcClient.exception.get.query(ex.id);
		if (!d) return;
		currentEx = d;
		editData = {
			status: d.status,
			impactScope: d.impactScope ?? '',
			rootCause: d.rootCause ?? '',
			resolution: d.resolution ?? '',
			conclusion: d.conclusion ?? '',
			financialImpact: d.financialImpact ?? 0,
			compensationAmount: d.compensationAmount ?? 0,
			ownerId: d.ownerId ?? ''
		};
		showDetail = true;
	}
	async function saveStatus() {
		await trpcClient.exception.updateStatus.mutate({
			id: currentEx.id,
			status: editData.status,
			impactScope: editData.impactScope || undefined,
			rootCause: editData.rootCause || undefined,
			resolution: editData.resolution || undefined,
			conclusion: editData.conclusion || undefined,
			financialImpact: Number(editData.financialImpact) || 0,
			compensationAmount: Number(editData.compensationAmount) || 0,
			ownerId: editData.ownerId || undefined
		});
		showDetail = false;
		currentEx = null;
		loadData();
	}
	async function addResp(uid: string) {
		if (!uid || !currentEx) return;
		await trpcClient.exception.addResponsibles.mutate({
			exceptionId: currentEx.id,
			responsibles: [{ userId: uid, role: '责任人' }]
		});
		const d = await trpcClient.exception.get.query(currentEx.id);
		currentEx = d;
	}
	async function handleAddResp() {
		if (selectedRespUserId) {
			await addResp(selectedRespUserId);
			selectedRespUserId = '';
		}
	}

	const statusBadge: Record<string, string> = {
		open: 'bg-red-100 text-red-800',
		investigating: 'bg-yellow-100 text-yellow-800',
		resolved: 'bg-blue-100 text-blue-800',
		closed: 'bg-gray-100 text-gray-800'
	};
	const severityBadge: Record<string, string> = {
		low: 'bg-gray-100 text-gray-700',
		medium: 'bg-blue-100 text-blue-700',
		high: 'bg-orange-100 text-orange-700',
		critical: 'bg-red-100 text-red-700'
	};
	const userMap = new Map(users.map((u) => [u.id, u.username]));
	const propMap = new Map(properties.map((p) => [p.id, p.name]));
	function formatDate(d: any) { if (!d) return '-'; return new Date(d).toLocaleString('zh-CN'); }

	function exceptionTypeLabel(t: any) { return (EXCEPTION_TYPE_LABELS as any)[t]; }
	function exceptionStatusLabel(s: any) { return (EXCEPTION_STATUS_LABELS as any)[s]; }
</script>

<div class="space-y-6">
	<div class="flex flex-wrap items-center justify-between gap-3">
		<div class="flex items-center gap-3">
			<select bind:value={filterType} class="select w-40" on:change={loadData}>
				<option value="">全部类型</option>
				{#each Object.entries(EXCEPTION_TYPE_LABELS) as [k, v]}<option value={k}>{v}</option>{/each}
			</select>
			<select bind:value={filterStatus} class="select w-40" on:change={loadData}>
				<option value="">全部状态</option>
				{#each Object.entries(EXCEPTION_STATUS_LABELS) as [k, v]}<option value={k}>{v}</option>{/each}
			</select>
		</div>
		<button on:click={runDetect} class="btn-secondary">
			<svg class="h-4 w-4 mr-1.5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2m-3 7h3m-3 4h3m-6-4h.01M9 16h.01"></path></svg>
			自动检测冲突
		</button>
	</div>

	{#if loading}
		<div class="card card-body py-12 text-center text-gray-500">加载中...</div>
	{:else}
		<div class="card overflow-hidden">
			<table class="table">
				<thead class="bg-gray-50"><tr>
					<th class="table-th">异常单号</th>
					<th class="table-th">标题</th>
					<th class="table-th">类型</th>
					<th class="table-th">严重级别</th>
					<th class="table-th">关联房源/订单</th>
					<th class="table-th">创建时间</th>
					<th class="table-th">状态</th>
					<th class="table-th">操作</th>
				</tr></thead>
				<tbody class="divide-y">
					{#if exceptions.length === 0}
						<tr><td colspan="8" class="py-16 text-center text-gray-400">暂无异常，运行良好 ✅</td></tr>
					{/if}
					{#each exceptions as e}
						<tr class="hover:bg-gray-50">
							<td class="table-td font-mono text-xs">{e.exceptionNo}</td>
							<td class="table-td font-medium max-w-xs truncate">{e.title}</td>
							<td class="table-td"><span class="badge bg-indigo-50 text-indigo-700">{exceptionTypeLabel(e.type)}</span></td>
							<td class="table-td"><span class="badge {severityBadge[e.severity]}">{e.severity === 'critical' ? '紧急' : e.severity === 'high' ? '高' : e.severity === 'medium' ? '中' : '低'}</span></td>
							<td class="table-td text-sm">
								<div>{propMap.get(e.propertyId ?? '') ?? '-'}</div>
								<div class="text-xs text-gray-400">{e.orderId ? '订单#' + e.orderId.slice(-6) : ''}</div>
							</td>
							<td class="table-td text-sm text-gray-500">{formatDate(e.createdAt)}</td>
							<td class="table-td"><span class="badge {statusBadge[e.status]}">{exceptionStatusLabel(e.status)}</span></td>
							<td class="table-td">
								<button on:click={() => openDetail(e)} class="btn-primary text-xs py-1 px-2">处理</button>
							</td>
						</tr>
					{/each}
				</tbody>
			</table>
		</div>
	{/if}
</div>

{#if showDetail && currentEx}
	<div class="fixed inset-0 bg-black/40 flex items-center justify-center z-50 p-4" on:click={(e) => { if (e.target === e.currentTarget) showDetail = false; }}>
		<div class="bg-white rounded-xl shadow-2xl w-full max-w-4xl max-h-[95vh] overflow-auto">
			<div class="px-6 py-4 border-b flex items-center justify-between sticky top-0 bg-white z-10">
				<div>
					<div class="font-semibold text-lg">异常单处理 - {currentEx.exceptionNo}</div>
					<div class="text-xs text-gray-500 mt-0.5">创建于 {formatDate(currentEx.createdAt)} · 创建人 {userMap.get(currentEx.createdBy) ?? '-'}</div>
				</div>
				<button on:click={() => showDetail = false} class="text-gray-400 hover:text-gray-600">✕</button>
			</div>
			<div class="p-6 space-y-5">
				<div class="bg-gray-50 rounded-lg p-4 border border-gray-200">
					<div class="grid grid-cols-2 gap-4 mb-3">
						<div><div class="text-xs text-gray-500">类型</div><div class="font-medium mt-0.5">{exceptionTypeLabel(currentEx.type)}</div></div>
						<div><div class="text-xs text-gray-500">严重级别</div><div class="font-medium mt-0.5">{currentEx.severity}</div></div>
						<div><div class="text-xs text-gray-500">房源</div><div class="font-medium mt-0.5">{propMap.get(currentEx.propertyId ?? '') ?? '-'}</div></div>
						<div><div class="text-xs text-gray-500">关联订单</div><div class="font-medium mt-0.5">{currentEx.orderId ?? '-'}</div></div>
					</div>
					<div><div class="text-xs text-gray-500 mb-1">标题</div><div class="font-medium">{currentEx.title}</div></div>
					<div class="mt-3"><div class="text-xs text-gray-500 mb-1">问题描述</div><div class="text-sm whitespace-pre-wrap bg-white p-3 rounded border border-gray-200">{currentEx.description}</div></div>
				</div>

				<div>
					<div class="font-semibold text-sm mb-3">责任人（关闭前必填）</div>
					<div class="flex flex-wrap gap-2 mb-2">
						{#each currentEx.responsibles ?? [] as r}
							<span class="inline-flex items-center gap-2 px-3 py-1.5 bg-primary-50 text-primary-700 rounded-lg border border-primary-200 text-sm">
								<span class="font-medium">{userMap.get(r.userId) ?? r.userId}</span>
								<span class="text-xs text-primary-600/70">{r.role}</span>
							</span>
						{/each}
						{#if (currentEx.responsibles ?? []).length === 0}
							<span class="text-sm text-red-500">⚠ 尚未指定责任人</span>
						{/if}
					</div>
					<div class="flex gap-2">
						<select bind:value={selectedRespUserId} class="select w-48">
							<option value="">选择添加责任人...</option>
							{#each users as u}
								<option value={u.id}>{u.username} ({u.role})</option>
							{/each}
						</select>
						<button on:click={handleAddResp} class="btn-secondary">添加</button>
					</div>
				</div>

				<div class="grid grid-cols-2 gap-4">
					<div><label class="label">影响范围（关闭前必填）</label>
						<textarea bind:value={editData.impactScope} class="input min-h-[80px]" placeholder="描述受影响的房源、日期、客人、经济损失范围等" />
					</div>
					<div><label class="label">根本原因分析</label>
						<textarea bind:value={editData.rootCause} class="input min-h-[80px]" placeholder="分析冲突产生的原因，如：操作失误、系统问题、渠道同步延迟等" />
					</div>
					<div><label class="label">处理方案</label>
						<textarea bind:value={editData.resolution} class="input min-h-[80px]" placeholder="已采取的解决措施" />
					</div>
					<div><label class="label">处理结论（关闭前必填）</label>
						<textarea bind:value={editData.conclusion} class="input min-h-[80px]" placeholder="最终处理结论，包含对客处理、内部整改、经验教训等" />
					</div>
					<div><label class="label">经济损失 (¥)</label>
						<input type="number" min="0" bind:value={editData.financialImpact} class="input" />
					</div>
					<div><label class="label">赔偿/补偿金额 (¥)</label>
						<input type="number" min="0" bind:value={editData.compensationAmount} class="input" />
					</div>
					<div><label class="label">跟进人</label>
						<select bind:value={editData.ownerId} class="select">
							<option value="">未指定</option>
							{#each users as u}<option value={u.id}>{u.username}</option>{/each}
						</select>
					</div>
					<div><label class="label">状态流转</label>
						<select bind:value={editData.status} class="select">
							{#each Object.entries(EXCEPTION_STATUS_LABELS) as [k, v]}<option value={k}>{v}</option>{/each}
						</select>
					</div>
				</div>

				<div class="border-t pt-4 flex justify-end gap-3">
					<button on:click={() => showDetail = false} class="btn-secondary">取消</button>
					<button on:click={saveStatus} class="btn-primary">保存并{editData.status === 'closed' ? '关闭' : '更新'}</button>
				</div>
			</div>
		</div>
	</div>
{/if}

// apps/web/src/app/exceptions/page.tsx
'use client';

import { useEffect, useState } from 'react';
import Link from 'next/link';
import {
  Plus, AlertTriangle, Search, Filter, ChevronRight, ShieldAlert, Clock, User, Target,
  FileCheck2, BadgeCheck, ArrowUpRight,
} from 'lucide-react';
import { api } from '@/lib/api';
import { useActivityId } from '@/components/ActivitySelector';
import { fmtDateTime, STATUS_STYLES, LABELS } from '@/lib/utils';

const STATUS_FILTERS = [
  { value: '', label: '全部' },
  ...Object.entries(LABELS.ExceptionStatus).map(([k, v]) => ({ value: k, label: v })),
];
const TYPE_FILTERS = [
  { value: '', label: '全部类型' },
  ...Object.entries(LABELS.ExceptionType).map(([k, v]) => ({ value: k, label: v })),
];

const SEVERITY_STYLES: Record<string, string> = {
  LOW: 'badge bg-emerald-100 text-emerald-700',
  MEDIUM: 'badge bg-amber-100 text-amber-700',
  HIGH: 'badge bg-orange-100 text-orange-700',
  CRITICAL: 'badge bg-rose-100 text-rose-700',
};

export default function ExceptionsPage() {
  const activityId = useActivityId();
  const [data, setData] = useState<any>({ list: [], total: 0 });
  const [status, setStatus] = useState('');
  const [type, setType] = useState('');
  const [keyword, setKeyword] = useState('');
  const [page, setPage] = useState(1);
  const pageSize = 20;

  const [showForm, setShowForm] = useState(false);
  const [formData, setFormData] = useState<any>({});

  const refresh = () => {
    api.get('/exceptions', { activityId, status, type, keyword, page, pageSize }).then(setData);
  };
  useEffect(() => { refresh(); }, [activityId, status, type, keyword, page]);

  const openNew = () => {
    setFormData({ activityId, type: 'REFUND_DISPUTE', title: '', description: '', impactScope: '', severity: 'MEDIUM', liabilityParty: 'UNCLEAR' });
    setShowForm(true);
  };

  const submit = async () => {
    await api.post('/exceptions', formData);
    setShowForm(false);
    refresh();
  };

  const groupByStatus: Record<string, number> = {};
  (data.list || []).forEach((e: any) => {
    groupByStatus[e.status] = (groupByStatus[e.status] || 0) + 1;
  });

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-slate-900 flex items-center gap-2">
            <ShieldAlert className="w-7 h-7 text-rose-500" />
            异常处理台
          </h1>
          <p className="text-sm text-slate-500 mt-1">退票争议、座位冲突等异常单闭环处理，影响范围与责任归属明确记录</p>
        </div>
        <button className="btn-primary" onClick={openNew}>
          <Plus className="w-4 h-4" /> 新建异常单
        </button>
      </div>

      <div className="grid grid-cols-5 gap-4">
        {[
          { label: '全部异常', value: data.total || 0, color: 'from-slate-500 to-slate-700', icon: AlertTriangle },
          { label: '待处理', value: groupByStatus.OPEN || 0, color: 'from-rose-500 to-rose-600', icon: Target },
          { label: '处理中', value: (groupByStatus.INVESTIGATING || 0) + (groupByStatus.PENDING_RESPONSE || 0), color: 'from-amber-500 to-orange-600', icon: Clock },
          { label: '已解决', value: (groupByStatus.RESOLVED || 0) + (groupByStatus.CLOSED || 0), color: 'from-emerald-500 to-teal-600', icon: BadgeCheck },
          { label: '已升级', value: groupByStatus.ESCALATED || 0, color: 'from-violet-500 to-purple-600', icon: ArrowUpRight },
        ].map((k) => (
          <div key={k.label} className="card p-5">
            <div className="flex items-start justify-between">
              <div>
                <div className="text-sm text-slate-500">{k.label}</div>
                <div className="mt-2 text-2xl font-bold text-slate-900">{k.value}</div>
              </div>
              <div className={`w-10 h-10 rounded-xl bg-gradient-to-br ${k.color} text-white flex items-center justify-center`}>
                <k.icon className="w-5 h-5" />
              </div>
            </div>
          </div>
        ))}
      </div>

      <div className="card p-4 flex items-center gap-4 flex-wrap">
        <div className="relative flex-1 max-w-sm">
          <Search className="w-4 h-4 text-slate-400 absolute left-3 top-1/2 -translate-y-1/2" />
          <input
            className="input pl-9"
            placeholder="异常单号 / 标题 / 描述"
            value={keyword}
            onChange={(e) => { setKeyword(e.target.value); setPage(1); }}
          />
        </div>
        <div className="flex items-center gap-2">
          <Filter className="w-4 h-4 text-slate-500" />
          <select className="input !w-32" value={status} onChange={(e) => { setStatus(e.target.value); setPage(1); }}>
            {STATUS_FILTERS.map((f) => <option key={f.value} value={f.value}>{f.label}</option>)}
          </select>
          <select className="input !w-40" value={type} onChange={(e) => { setType(e.target.value); setPage(1); }}>
            {TYPE_FILTERS.map((f) => <option key={f.value} value={f.value}>{f.label}</option>)}
          </select>
        </div>
      </div>

      <div className="card overflow-hidden">
        <table className="table">
          <thead>
            <tr>
              <th>异常单号</th>
              <th>类型</th>
              <th>标题 / 关联</th>
              <th>严重程度</th>
              <th>责任归属</th>
              <th>处理人</th>
              <th>状态</th>
              <th>创建时间</th>
              <th className="text-right">操作</th>
            </tr>
          </thead>
          <tbody>
            {data.list?.length === 0 && <tr><td colSpan={9} className="text-center py-10 text-slate-400">暂无异常单</td></tr>}
            {data.list?.map((e: any) => (
              <tr key={e.id}>
                <td className="font-mono text-brand-600 font-semibold">{e.exceptionNo}</td>
                <td>
                  <span className="badge bg-indigo-50 text-indigo-700">
                    {LABELS.ExceptionType[e.type] || e.type}
                  </span>
                </td>
                <td>
                  <div className="font-medium text-slate-900 max-w-xs truncate">{e.title}</div>
                  {e.order && (
                    <div className="text-xs text-slate-500 mt-0.5">
                      关联订单：
                      <Link href={`/orders/${e.orderId}`} className="text-brand-600 hover:underline ml-1">
                        {e.order.orderNo}
                      </Link>
                      {e.order.customerName && <span className="text-slate-400 ml-1">({e.order.customerName})</span>}
                    </div>
                  )}
                </td>
                <td>
                  <span className={SEVERITY_STYLES[e.severity] || SEVERITY_STYLES.MEDIUM}>
                    {LABELS.Severity[e.severity] || e.severity}
                  </span>
                </td>
                <td>
                  <span className="badge bg-slate-100 text-slate-700">
                    {LABELS.LiabilityParty[e.liabilityParty] || e.liabilityParty}
                  </span>
                </td>
                <td>
                  {e.handlerName ? (
                    <div className="text-sm flex items-center gap-1">
                      <User className="w-3.5 h-3.5 text-slate-400" />
                      {e.handlerName}
                    </div>
                  ) : <span className="text-slate-400 text-xs">未分配</span>}
                </td>
                <td>
                  <span className={STATUS_STYLES[e.status]}>{LABELS.ExceptionStatus[e.status] || e.status}</span>
                </td>
                <td className="text-xs text-slate-500">{fmtDateTime(e.createdAt)}</td>
                <td className="text-right">
                  <Link href={`/exceptions/${e.id}`} className="btn-secondary !px-3 !py-1 text-xs inline-flex items-center">
                    处理 <ChevronRight className="w-3.5 h-3.5" />
                  </Link>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      {showForm && (
        <div className="fixed inset-0 bg-slate-900/50 z-50 flex items-center justify-center p-6" onClick={() => setShowForm(false)}>
          <div className="card w-full max-w-xl p-6" onClick={(e) => e.stopPropagation()}>
            <div className="flex items-center justify-between mb-4">
              <div className="text-lg font-semibold flex items-center gap-2">
                <ShieldAlert className="w-5 h-5 text-rose-500" />
                新建异常单
              </div>
              <button onClick={() => setShowForm(false)} className="text-slate-400 hover:text-slate-600 text-xl leading-none">×</button>
            </div>
            <div className="space-y-4">
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="label">异常类型</label>
                  <select className="input" value={formData.type} onChange={(e) => setFormData({ ...formData, type: e.target.value })}>
                    {Object.entries(LABELS.ExceptionType).map(([k, v]) => <option key={k} value={k}>{v}</option>)}
                  </select>
                </div>
                <div>
                  <label className="label">严重程度</label>
                  <select className="input" value={formData.severity} onChange={(e) => setFormData({ ...formData, severity: e.target.value })}>
                    {Object.entries(LABELS.Severity).map(([k, v]) => <option key={k} value={k}>{v}</option>)}
                  </select>
                </div>
              </div>
              <div>
                <label className="label">标题</label>
                <input className="input" value={formData.title || ''} onChange={(e) => setFormData({ ...formData, title: e.target.value })} placeholder="一句话概括异常" />
              </div>
              <div>
                <label className="label">详细描述</label>
                <textarea className="input min-h-[80px]" value={formData.description || ''} onChange={(e) => setFormData({ ...formData, description: e.target.value })} />
              </div>
              <div>
                <label className="label">影响范围</label>
                <textarea className="input min-h-[60px]" value={formData.impactScope || ''} onChange={(e) => setFormData({ ...formData, impactScope: e.target.value })} placeholder="涉及订单数、金额、客户数量等" />
              </div>
              <div>
                <label className="label">关联订单 ID（可选）</label>
                <input className="input" value={formData.orderId || ''} onChange={(e) => setFormData({ ...formData, orderId: e.target.value })} />
              </div>
              <div>
                <label className="label">初步责任归属</label>
                <select className="input" value={formData.liabilityParty} onChange={(e) => setFormData({ ...formData, liabilityParty: e.target.value })}>
                  {Object.entries(LABELS.LiabilityParty).map(([k, v]) => <option key={k} value={k}>{v}</option>)}
                </select>
              </div>
            </div>
            <div className="flex justify-end gap-2 mt-6">
              <button className="btn-secondary" onClick={() => setShowForm(false)}>取消</button>
              <button className="btn-primary" onClick={submit}>提交</button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
