// src/routes/login/+page.svelte
<script lang="ts">
	import { trpc } from '$lib/trpc';
	import { goto } from '$app/navigation';

	let username = '';
	let password = '';
	let error = '';
	let loading = false;

	async function handleLogin(e: Event) {
		e.preventDefault();
		error = '';
		loading = true;
		try {
			await trpc().user.login.mutate({ username, password });
			await goto('/');
		} catch (e: any) {
			error = e?.message || '登录失败，请检查用户名和密码';
		} finally {
			loading = false;
		}
	}
</script>

<div class="min-h-screen flex items-center justify-center bg-gradient-to-br from-brand-50 to-brand-100">
	<div class="max-w-md w-full mx-4">
		<div class="text-center mb-8">
			<div class="inline-flex items-center justify-center w-16 h-16 rounded-2xl bg-brand-600 text-white text-3xl mb-4">
				🏡
			</div>
			<h1 class="text-3xl font-bold text-gray-900">民宿保洁排班协同台</h1>
			<p class="text-gray-600 mt-2">高效协同 · 透明追溯 · 品质保障</p>
		</div>

		<form on:submit={handleLogin} class="bg-white rounded-2xl shadow-xl p-8">
			{#if error}
				<div class="mb-6 p-4 rounded-lg bg-red-50 border border-red-200 text-red-700 text-sm">
					{error}
				</div>
			{/if}

			<div class="space-y-5">
				<div>
					<label for="username" class="label">用户名</label>
					<input
						id="username"
						type="text"
						bind:value={username}
						class="input"
						placeholder="请输入用户名"
						required
					/>
				</div>
				<div>
					<label for="password" class="label">密码</label>
					<input
						id="password"
						type="password"
						bind:value={password}
						class="input"
						placeholder="请输入密码"
						required
					/>
				</div>
			</div>

			<button
				type="submit"
				disabled={loading}
				class="btn-primary w-full mt-6 disabled:opacity-50"
			>
				{loading ? '登录中...' : '登 录'}
			</button>

			<div class="mt-6 pt-6 border-t border-gray-100">
				<p class="text-xs text-gray-500 mb-3">演示账号（密码均为 123456）：</p>
				<div class="grid grid-cols-2 gap-2 text-xs">
					<button type="button" on:click={() => { username = 'admin'; password = '123456'; }}
						class="p-2 rounded border border-gray-200 hover:bg-gray-50 text-left">
						<div class="font-medium text-gray-800">admin</div>
						<div class="text-gray-500">系统管理员</div>
					</button>
					<button type="button" on:click={() => { username = 'manager'; password = '123456'; }}
						class="p-2 rounded border border-gray-200 hover:bg-gray-50 text-left">
						<div class="font-medium text-gray-800">manager</div>
						<div class="text-gray-500">运营经理</div>
					</button>
					<button type="button" on:click={() => { username = 'cleaner1'; password = '123456'; }}
						class="p-2 rounded border border-gray-200 hover:bg-gray-50 text-left">
						<div class="font-medium text-gray-800">cleaner1</div>
						<div class="text-gray-500">张阿姨</div>
					</button>
					<button type="button" on:click={() => { username = 'viewer'; password = '123456'; }}
						class="p-2 rounded border border-gray-200 hover:bg-gray-50 text-left">
						<div class="font-medium text-gray-800">viewer</div>
						<div class="text-gray-500">只读查看</div>
					</button>
				</div>
			</div>
		</form>

		<p class="text-center text-xs text-gray-400 mt-6">
			© 2026 民宿保洁排班协同台 · 全流程可追溯
		</p>
	</div>
</div>

<script lang="ts" context="module">
</script>

// frontend/src/pages/Login.tsx
import { useState } from 'react'
import { useNavigate, Navigate } from '@tanstack/react-router'
import { useAuthStore } from '@/hooks/useAuthStore'
import { Building2, Loader2 } from 'lucide-react'

export default function Login() {
  const [username, setUsername] = useState('')
  const [password, setPassword] = useState('')
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState('')
  const { login, isAuthenticated } = useAuthStore()
  const navigate = useNavigate()

  if (isAuthenticated) {
    return <Navigate to="/" />
  }

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    setError('')
    setLoading(true)
    try {
      await login(username, password)
      navigate({ to: '/' })
    } catch (err: any) {
      setError(err.response?.data?.detail || '登录失败，请检查用户名和密码')
    } finally {
      setLoading(false)
    }
  }

  const quickLogin = (user: string, pwd: string) => {
    setUsername(user)
    setPassword(pwd)
  }

  return (
    <div className="min-h-screen flex items-center justify-center bg-gradient-to-br from-blue-50 to-indigo-100 py-12 px-4 sm:px-6 lg:px-8">
      <div className="max-w-md w-full space-y-8 bg-white p-8 rounded-xl shadow-lg">
        <div className="text-center">
          <div className="mx-auto h-16 w-16 bg-primary-100 rounded-full flex items-center justify-center">
            <Building2 className="h-8 w-8 text-primary-600" />
          </div>
          <h2 className="mt-6 text-2xl font-bold text-gray-900">
            物业园区报修工单跟进台
          </h2>
          <p className="mt-2 text-sm text-gray-600">请登录您的账号</p>
        </div>

        <form className="mt-8 space-y-6" onSubmit={handleSubmit}>
          {error && (
            <div className="bg-red-50 text-red-600 px-4 py-3 rounded-lg text-sm">
              {error}
            </div>
          )}

          <div className="space-y-4">
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                用户名
              </label>
              <input
                type="text"
                value={username}
                onChange={(e) => setUsername(e.target.value)}
                className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary-500 focus:border-transparent outline-none transition-all"
                placeholder="请输入用户名"
                required
              />
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                密码
              </label>
              <input
                type="password"
                value={password}
                onChange={(e) => setPassword(e.target.value)}
                className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary-500 focus:border-transparent outline-none transition-all"
                placeholder="请输入密码"
                required
              />
            </div>
          </div>

          <button
            type="submit"
            disabled={loading}
            className="w-full flex justify-center items-center py-3 px-4 border border-transparent rounded-lg shadow-sm text-sm font-medium text-white bg-primary-600 hover:bg-primary-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-primary-500 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
          >
            {loading ? (
              <Loader2 className="w-5 h-5 animate-spin mr-2" />
            ) : null}
            {loading ? '登录中...' : '登 录'}
          </button>
        </form>

        <div className="mt-6 pt-6 border-t border-gray-100">
          <p className="text-xs text-gray-500 text-center mb-3">快速登录</p>
          <div className="grid grid-cols-3 gap-2">
            <button
              onClick={() => quickLogin('admin', 'admin123')}
              className="text-xs py-2 px-2 bg-gray-100 hover:bg-gray-200 rounded text-gray-700 transition-colors"
            >
              管理员
            </button>
            <button
              onClick={() => quickLogin('manager', 'manager123')}
              className="text-xs py-2 px-2 bg-gray-100 hover:bg-gray-200 rounded text-gray-700 transition-colors"
            >
              经理
            </button>
            <button
              onClick={() => quickLogin('worker1', 'worker123')}
              className="text-xs py-2 px-2 bg-gray-100 hover:bg-gray-200 rounded text-gray-700 transition-colors"
            >
              工人
            </button>
          </div>
        </div>
      </div>
    </div>
  )
}
