// src/routes/(app)/admin/tags/+page.svelte
<script lang="ts">
	import { trpc } from '$lib/client/trpc';
	import type { PageData } from './$types';
	import { invalidateAll } from '$app/navigation';

	let { data }: { data: PageData } = $props();

	let showCreateModal = $state(false);
	let showEditModal = $state(false);
	let editingTag = $state<{ id: string; code: string; label: string; category: string } | null>(null);

	let newCode = $state('');
	let newLabel = $state('');
	let newCategory = $state('type');
	let submitting = $state(false);
	let editLabel = $state('');

	const categories = [
		{ value: 'type', label: '问题类型' },
		{ value: 'area', label: '区域' },
		{ value: 'priority', label: '优先级' }
	];

	const categoryLabels: Record<string, string> = {
		type: '问题类型',
		area: '区域',
		priority: '优先级'
	};

	async function handleCreate() {
		if (!newCode || !newLabel) return;
		submitting = true;
		try {
			await trpc.tag.create.mutate({
				code: newCode,
				label: newLabel,
				category: newCategory
			});
			showCreateModal = false;
			newCode = '';
			newLabel = '';
			newCategory = 'type';
			await invalidateAll();
		} catch (e: any) {
			alert(e?.message || '创建失败');
		} finally {
			submitting = false;
		}
	}

	function openEditModal(tag: any) {
		editingTag = tag;
		editLabel = tag.label;
		showEditModal = true;
	}

	async function handleEdit() {
		if (!editingTag || !editLabel) return;
		submitting = true;
		try {
			await trpc.tag.update.mutate({
				id: editingTag.id,
				label: editLabel
			});
			showEditModal = false;
			editingTag = null;
			await invalidateAll();
		} catch (e: any) {
			alert(e?.message || '更新失败');
		} finally {
			submitting = false;
		}
	}

	async function handleDelete(tagId: string) {
		if (!confirm('确认删除该标签？')) return;
		try {
			await trpc.tag.delete.mutate({ id: tagId });
			await invalidateAll();
		} catch (e: any) {
			alert(e?.message || '删除失败');
		}
	}

	const groupedTags = $derived(() => {
		const groups: Record<string, typeof data.tags> = {};
		for (const tag of data.tags) {
			const cat = tag.category;
			if (!groups[cat]) groups[cat] = [];
			groups[cat].push(tag);
		}
		return groups;
	});
</script>

<svelte:head>
	<title>标签管理 - 景区投诉协同台</title>
</svelte:head>

<div class="space-y-4">
	<div class="flex items-center justify-between">
		<h1 class="text-2xl font-bold text-slate-800">标签管理</h1>
		<button
			onclick={() => showCreateModal = true}
			class="inline-flex items-center gap-2 px-4 py-2 bg-primary-600 text-white text-sm font-medium rounded-lg hover:bg-primary-700 transition"
		>
			<svg xmlns="http://www.w3.org/2000/svg" class="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
				<path stroke-linecap="round" stroke-linejoin="round" d="M12 4v16m8-8H4" />
			</svg>
			添加标签
		</button>
	</div>

	<div class="grid grid-cols-1 md:grid-cols-3 gap-4">
		{#each categories as cat}
			<div class="bg-white rounded-xl shadow-sm border border-slate-200 overflow-hidden">
				<div class="px-4 py-3 border-b border-slate-200 bg-slate-50">
					<h3 class="text-sm font-semibold text-slate-800">{cat.label}</h3>
					<p class="text-xs text-slate-400 mt-0.5">
						{(groupedTags()[cat.value] ?? []).length} 个标签
					</p>
				</div>
				<div class="p-3">
					{#if (groupedTags()[cat.value] ?? []).length === 0}
						<p class="text-sm text-slate-400 text-center py-4">暂无标签</p>
					{:else}
						<div class="space-y-2">
							{#each groupedTags()[cat.value] ?? [] as tag}
								<div class="flex items-center justify-between p-2.5 rounded-lg bg-slate-50 hover:bg-slate-100 transition">
									<div>
										<span class="text-sm text-slate-800 font-medium">{tag.label}</span>
										<span class="text-xs text-slate-400 ml-2 font-mono">{tag.code}</span>
									</div>
									<div class="flex items-center gap-1">
										<button
											onclick={() => openEditModal(tag)}
											class="p-1.5 text-slate-500 hover:text-primary-600 hover:bg-white rounded transition"
											title="编辑"
										>
											<svg xmlns="http://www.w3.org/2000/svg" class="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
												<path stroke-linecap="round" stroke-linejoin="round" d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z" />
											</svg>
										</button>
										<button
											onclick={() => handleDelete(tag.id)}
											class="p-1.5 text-slate-500 hover:text-red-600 hover:bg-white rounded transition"
											title="删除"
										>
											<svg xmlns="http://www.w3.org/2000/svg" class="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
												<path stroke-linecap="round" stroke-linejoin="round" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
											</svg>
										</button>
									</div>
								</div>
							{/each}
						</div>
					{/if}
				</div>
			</div>
		{/each}
	</div>
</div>

{#if showCreateModal}
	<div class="fixed inset-0 bg-black/50 flex items-center justify-center z-50" onclick={() => showCreateModal = false}>
		<div class="bg-white rounded-xl p-6 w-full max-w-md mx-4 animate-fade-in" onclick={(e) => e.stopPropagation()}>
			<h3 class="text-lg font-semibold text-slate-800 mb-4">添加标签</h3>
			<div class="space-y-4">
				<div>
					<label class="block text-sm font-medium text-slate-700 mb-1">标签编码</label>
					<input
						type="text"
						bind:value={newCode}
						class="w-full border border-slate-300 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-primary-500 focus:border-primary-500"
						placeholder="例如：noise"
					/>
				</div>
				<div>
					<label class="block text-sm font-medium text-slate-700 mb-1">标签名称</label>
					<input
						type="text"
						bind:value={newLabel}
						class="w-full border border-slate-300 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-primary-500 focus:border-primary-500"
						placeholder="例如：噪音扰民"
					/>
				</div>
				<div>
					<label class="block text-sm font-medium text-slate-700 mb-1">分类</label>
					<select
						bind:value={newCategory}
						class="w-full border border-slate-300 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-primary-500 focus:border-primary-500"
					>
						{#each categories as cat}
							<option value={cat.value}>{cat.label}</option>
						{/each}
					</select>
				</div>
				<div class="flex justify-end gap-3 pt-2">
					<button onclick={() => showCreateModal = false} class="px-4 py-2 text-sm text-slate-600 hover:text-slate-800 transition">
						取消
					</button>
					<button
						onclick={handleCreate}
						disabled={submitting || !newCode || !newLabel}
						class="px-4 py-2 bg-primary-600 text-white text-sm font-medium rounded-lg hover:bg-primary-700 transition disabled:opacity-50"
					>
						创建
					</button>
				</div>
			</div>
		</div>
	</div>
{/if}

{#if showEditModal && editingTag}
	<div class="fixed inset-0 bg-black/50 flex items-center justify-center z-50" onclick={() => showEditModal = false}>
		<div class="bg-white rounded-xl p-6 w-full max-w-md mx-4 animate-fade-in" onclick={(e) => e.stopPropagation()}>
			<h3 class="text-lg font-semibold text-slate-800 mb-4">编辑标签</h3>
			<div class="space-y-4">
				<div>
					<label class="block text-sm font-medium text-slate-700 mb-1">标签编码</label>
					<input
						type="text"
						value={editingTag.code}
						disabled
						class="w-full border border-slate-200 bg-slate-50 rounded-lg px-3 py-2 text-sm text-slate-400"
					/>
				</div>
				<div>
					<label class="block text-sm font-medium text-slate-700 mb-1">标签名称</label>
					<input
						type="text"
						bind:value={editLabel}
						class="w-full border border-slate-300 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-primary-500 focus:border-primary-500"
					/>
				</div>
				<div>
					<label class="block text-sm font-medium text-slate-700 mb-1">分类</label>
					<input
						type="text"
						value={categoryLabels[editingTag.category] ?? editingTag.category}
						disabled
						class="w-full border border-slate-200 bg-slate-50 rounded-lg px-3 py-2 text-sm text-slate-400"
					/>
				</div>
				<div class="flex justify-end gap-3 pt-2">
					<button onclick={() => showEditModal = false} class="px-4 py-2 text-sm text-slate-600 hover:text-slate-800 transition">
						取消
					</button>
					<button
						onclick={handleEdit}
						disabled={submitting || !editLabel}
						class="px-4 py-2 bg-primary-600 text-white text-sm font-medium rounded-lg hover:bg-primary-700 transition disabled:opacity-50"
					>
						保存
					</button>
				</div>
			</div>
		</div>
	</div>
{/if}

// frontend/src/pages/Tags.tsx
import { useState, useEffect } from 'react';
import { tagsApi } from '@/api';
import { useAuthStore } from '@/store/auth';
import type { Tag } from '@/types';

const presetColors = [
  '#3b82f6', '#10b981', '#f59e0b', '#ef4444', '#8b5cf6',
  '#ec4899', '#06b6d4', '#84cc16', '#f97316', '#6366f1',
];

export default function TagsPage() {
  const { hasRole } = useAuthStore();
  const [tags, setTags] = useState<Tag[]>([]);
  const [category, setCategory] = useState('');
  const [showModal, setShowModal] = useState(false);
  const [editingTag, setEditingTag] = useState<Tag | null>(null);
  const [formData, setFormData] = useState({ name: '', category: '', color: '#3b82f6' });

  useEffect(() => {
    loadTags();
  }, [category]);

  const loadTags = async () => {
    try {
      const data = await tagsApi.list(category || undefined);
      setTags(data);
    } catch (error) {
      console.error('加载标签失败:', error);
    }
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    try {
      if (editingTag) {
        await tagsApi.update(editingTag.id, formData);
      } else {
        await tagsApi.create(formData);
      }
      setShowModal(false);
      setEditingTag(null);
      setFormData({ name: '', category: '', color: '#3b82f6' });
      loadTags();
    } catch (error: any) {
      alert(error.response?.data?.detail || '操作失败');
    }
  };

  const handleEdit = (tag: Tag) => {
    setEditingTag(tag);
    setFormData({ name: tag.name, category: tag.category || '', color: tag.color });
    setShowModal(true);
  };

  const handleDelete = async (id: number) => {
    if (!confirm('确定要删除这个标签吗？')) return;
    try {
      await tagsApi.delete(id);
      loadTags();
    } catch (error: any) {
      alert(error.response?.data?.detail || '删除失败');
    }
  };

  const categories = Array.from(new Set(tags.map(t => t.category).filter(Boolean)));
  const canEdit = hasRole(['admin', 'teacher']);

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <h1 className="text-2xl font-bold text-gray-900">标签管理</h1>
        {canEdit && (
          <button
            onClick={() => { setEditingTag(null); setFormData({ name: '', category: '', color: '#3b82f6' }); setShowModal(true); }}
            className="px-4 py-2 bg-primary-600 text-white rounded-lg hover:bg-primary-700 transition"
          >
            + 新建标签
          </button>
        )}
      </div>

      <div className="bg-white rounded-xl shadow-sm border border-gray-200">
        <div className="p-4 border-b border-gray-200 flex gap-2 flex-wrap">
          <button
            onClick={() => setCategory('')}
            className={`px-3 py-1.5 text-sm rounded-lg transition ${
              !category ? 'bg-primary-100 text-primary-700' : 'text-gray-600 hover:bg-gray-100'
            }`}
          >
            全部
          </button>
          {categories.map(cat => (
            <button
              key={cat}
              onClick={() => setCategory(cat!)}
              className={`px-3 py-1.5 text-sm rounded-lg transition ${
                category === cat ? 'bg-primary-100 text-primary-700' : 'text-gray-600 hover:bg-gray-100'
              }`}
            >
              {cat}
            </button>
          ))}
        </div>

        <div className="p-4">
          <div className="flex flex-wrap gap-3">
            {tags.map(tag => (
              <div
                key={tag.id}
                className="group flex items-center gap-2 px-3 py-2 bg-gray-50 rounded-lg hover:bg-gray-100 transition"
              >
                <span
                  className="w-3 h-3 rounded-full"
                  style={{ backgroundColor: tag.color }}
                />
                <span className="text-sm font-medium text-gray-700">{tag.name}</span>
                {tag.category && (
                  <span className="text-xs text-gray-400">({tag.category})</span>
                )}
                {canEdit && (
                  <div className="opacity-0 group-hover:opacity-100 transition flex gap-1 ml-1">
                    <button
                      onClick={() => handleEdit(tag)}
                      className="text-xs text-gray-500 hover:text-primary-600"
                    >
                      编辑
                    </button>
                    <button
                      onClick={() => handleDelete(tag.id)}
                      className="text-xs text-gray-500 hover:text-red-600"
                    >
                      删除
                    </button>
                  </div>
                )}
              </div>
            ))}
          </div>
          {tags.length === 0 && (
            <div className="text-center text-gray-400 py-12">
              暂无标签数据
            </div>
          )}
        </div>
      </div>

      {showModal && (
        <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50">
          <div className="bg-white rounded-xl w-full max-w-md p-6">
            <h2 className="text-lg font-semibold mb-4">
              {editingTag ? '编辑标签' : '新建标签'}
            </h2>
            <form onSubmit={handleSubmit} className="space-y-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">标签名称</label>
                <input
                  type="text"
                  value={formData.name}
                  onChange={(e) => setFormData({ ...formData, name: e.target.value })}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary-500 focus:border-transparent outline-none"
                  required
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">分类</label>
                <input
                  type="text"
                  value={formData.category}
                  onChange={(e) => setFormData({ ...formData, category: e.target.value })}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary-500 focus:border-transparent outline-none"
                  placeholder="例如：知识点、难度、章节"
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">颜色</label>
                <div className="flex flex-wrap gap-2">
                  {presetColors.map(color => (
                    <button
                      key={color}
                      type="button"
                      onClick={() => setFormData({ ...formData, color })}
                      className={`w-8 h-8 rounded-full transition ${
                        formData.color === color ? 'ring-2 ring-offset-2 ring-gray-400' : ''
                      }`}
                      style={{ backgroundColor: color }}
                    />
                  ))}
                </div>
              </div>
              <div className="flex justify-end gap-3 pt-2">
                <button
                  type="button"
                  onClick={() => setShowModal(false)}
                  className="px-4 py-2 text-gray-600 hover:bg-gray-100 rounded-lg transition"
                >
                  取消
                </button>
                <button
                  type="submit"
                  className="px-4 py-2 bg-primary-600 text-white rounded-lg hover:bg-primary-700 transition"
                >
                  保存
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
}
