// src/routes/ticket-types/+page.svelte
<script lang="ts">
	import { trpc } from '$lib/trpc/client';
	import { onMount } from 'svelte';
	import { formatDateTime, formatMoney, statusBadge } from '$lib/utils';

	let page = 1, pageSize = 20;
	let total = 0, totalPages = 0;
	let items: any[] = [];
	let events: any[] = [];
	let loading = false;

	let filterEventId = '';
	let filterCategory = '';
	let filterStatus = '';
	let keyword = '';

	let showCreateModal = false;
	let form: any = {};

	async function loadEvents() {
		try {
			const res = await trpc.event.list.query({ pageSize: 200 });
			events = res.items;
		} catch {}
	}

	async function load() {
		loading = true;
		try {
			const res = await trpc.ticketType.list.query({
				page, pageSize,
				eventId: filterEventId || undefined,
				category: filterCategory || undefined,
				status: filterStatus || undefined,
				keyword: keyword || undefined
			});
			items = res.items;
			total = res.total;
			totalPages = res.totalPages;
		} finally {
			loading = false;
		}
	}

	async function submit() {
		try {
			await trpc.ticketType.create.mutate({
				eventId: form.eventId,
				code: form.code,
				name: form.name,
				description: form.description,
				category: form.category,
				price: form.price || '0',
				costPrice: form.costPrice || '0',
				totalQuota: Number(form.totalQuota) || 0,
				refundPolicy: form.refundPolicy || 'non_refundable',
				transferAllowed: !!form.transferAllowed,
				requiresSeat: !!form.requiresSeat
			});
			showCreateModal = false;
			form = {};
			await load();
		} catch (e: any) {
			alert(e?.message ?? '创建失败');
		}
	}

	onMount(async () => {
		await loadEvents();
		await load();
	});

	$effect(() => {
		load();
	});
</script>

<div class="p-6 space-y-6">
	<div class="flex items-center justify-between">
		<div>
			<h1>票种规则</h1>
			<p class="text-sm text-slate-500 mt-1">定义票类分级、价格、库存、退票政策、转赠和核验规则</p>
		</div>
		<button class="btn-primary" on:click={() => (showCreateModal = true)}>➕ 新增票种</button>
	</div>

	<div class="card">
		<div class="card-header">
			<div class="flex flex-wrap gap-3 items-center">
				<select class="select-input w-48" bind:value={filterEventId}>
					<option value="">全部活动</option>
					{#each events as e}<option value={e.event?.id ?? e.id}>{e.event?.name ?? e.name}</option>{/each}
				</select>
				<select class="select-input w-32" bind:value={filterCategory}>
					<option value="">全部类别</option>
					<option value="vip">VIP</option>
					<option value="premium">高级</option>
					<option value="standard">标准</option>
					<option value="economy">经济</option>
					<option value="standing">站票</option>
				</select>
				<select class="select-input w-32" bind:value={filterStatus}>
					<option value="">全部状态</option>
					<option value="active">启用</option>
					<option value="inactive">停用</option>
					<option value="sold_out">售罄</option>
				</select>
				<input class="input w-48" placeholder="搜索票种名/编码" bind:value={keyword} />
			</div>
		</div>
		<div class="table-wrap">
			<table class="data-table">
				<thead>
					<tr>
						<th>票种编码</th>
						<th>名称</th>
						<th>类别</th>
						<th class="text-right">售价</th>
						<th class="text-center">配额</th>
						<th class="text-center">已售</th>
						<th class="text-center">预占</th>
						<th>退票</th>
						<th>状态</th>
						<th>更新时间</th>
						<th class="text-right">操作</th>
					</tr>
				</thead>
				<tbody>
					{#if loading}
						<tr><td colspan="11" class="py-12 text-center text-slate-400">加载中...</td></tr>
					{:else if items.length === 0}
						<tr><td colspan="11" class="empty-state">暂无数据，点击右上角新增票种</td></tr>
					{:else}
						{#each items as t}
							{@const available = Math.max(0, (t.totalQuota ?? 0) - (t.soldQuota ?? 0) - (t.heldQuota ?? 0))}
							<tr class="hover:bg-slate-50">
								<td class="font-mono text-xs">{t.code}</td>
								<td class="font-medium">{t.name}</td>
								<td><span class="badge-{t.category === 'vip' ? 'yellow' : t.category === 'premium' ? 'purple' : 'blue'}">{t.category}</span></td>
								<td class="text-right font-mono font-semibold">¥{formatMoney(t.price)}</td>
								<td class="text-center font-semibold">{t.totalQuota}</td>
								<td class="text-center text-blue-600">{t.soldQuota ?? 0}</td>
								<td class="text-center text-yellow-600">{t.heldQuota ?? 0}</td>
								<td><span class="tag text-xs">{t.refundPolicy}</span></td>
								<td>{@const b = statusBadge(t.status)}<span class={b.cls}>{b.label}</span></td>
								<td class="text-xs text-slate-500">{formatDateTime(t.updatedAt)}</td>
								<td class="text-right"><button class="btn-ghost !py-1 !px-2 text-xs">编辑</button></td>
							</tr>
						{/each}
					{/if}
				</tbody>
			</table>
		</div>
		<div class="pagination">
			<div class="text-sm text-slate-500">共 {total} 条 · 第 {page}/{totalPages || 1} 页</div>
			<div class="flex gap-2">
				<button class="btn-secondary !py-1" disabled={page <= 1} on:click={() => page--}>上一页</button>
				<button class="btn-secondary !py-1" disabled={page >= totalPages} on:click={() => page++}>下一页</button>
			</div>
		</div>
	</div>
</div>

{#if showCreateModal}
	<div class="fixed inset-0 bg-black/40 flex items-center justify-center z-50 p-4">
		<div class="card w-full max-w-2xl max-h-[90vh] overflow-y-auto">
			<div class="card-header"><h3>新增票种</h3><button class="btn-ghost !p-1" on:click={() => (showCreateModal = false)}>✕</button></div>
			<div class="card-body space-y-4">
				<div class="grid grid-cols-2 gap-4">
					<div>
						<label class="label">所属活动 *</label>
						<select class="select-input" bind:value={form.eventId} required>
							<option value="">请选择</option>
							{#each events as e}<option value={e.event?.id ?? e.id}>{e.event?.name ?? e.name}</option>{/each}
						</select>
					</div>
					<div>
						<label class="label">类别 *</label>
						<select class="select-input" bind:value={form.category} required>
							<option value="">请选择</option>
							<option value="vip">VIP</option>
							<option value="premium">高级</option>
							<option value="standard">标准</option>
							<option value="economy">经济</option>
							<option value="standing">站票</option>
							<option value="other">其他</option>
						</select>
					</div>
				</div>
				<div class="grid grid-cols-2 gap-4">
					<div>
						<label class="label">票种编码 *</label>
						<input class="input font-mono" bind:value={form.code} required placeholder="如 STANDARD-001" />
					</div>
					<div>
						<label class="label">票种名称 *</label>
						<input class="input" bind:value={form.name} required placeholder="内场 VIP 票" />
					</div>
				</div>
				<div class="grid grid-cols-3 gap-4">
					<div>
						<label class="label">售价(¥) *</label>
						<input class="input" bind:value={form.price} required placeholder="99.00" />
					</div>
					<div>
						<label class="label">成本价(¥)</label>
						<input class="input" bind:value={form.costPrice} placeholder="0.00" />
					</div>
					<div>
						<label class="label">总配额 *</label>
						<input class="input" type="number" bind:value={form.totalQuota} required placeholder="500" />
					</div>
				</div>
				<div>
					<label class="label">描述</label>
					<textarea class="input min-h-[60px]" bind:value={form.description} placeholder="权限、区域、服务说明..." />
				</div>
				<div class="grid grid-cols-2 gap-4">
					<div>
						<label class="label">退票政策</label>
						<select class="select-input" bind:value={form.refundPolicy}>
							<option value="non_refundable">不可退</option>
							<option value="partial_refund">部分退</option>
							<option value="full_refund_before_date">时限前全退</option>
						</select>
					</div>
				</div>
				<div class="flex gap-6 pt-2">
					<label class="flex items-center gap-2"><input type="checkbox" bind:checked={form.transferAllowed} class="w-4 h-4" /><span class="text-sm">允许转赠</span></label>
					<label class="flex items-center gap-2"><input type="checkbox" bind:checked={form.requiresSeat} class="w-4 h-4" checked /><span class="text-sm">需要选座</span></label>
				</div>
				<div class="flex justify-end gap-2 pt-2">
					<button class="btn-secondary" on:click={() => (showCreateModal = false)}>取消</button>
					<button class="btn-primary" disabled={!form.eventId || !form.code || !form.name} on:click={submit}>保存</button>
				</div>
			</div>
		</div>
	</div>
{/if}

// web/src/app/biz/ticket-types/page.tsx
'use client';

import { useState, useEffect, useCallback } from 'react';
import { fetchApi, buildQuery } from '@/lib/api';

interface TicketType {
  id: string;
  name: string;
  price: number;
  quota: number;
  soldCount: number;
  refundable: boolean;
  transferable: boolean;
  rules?: string;
  eventId?: string;
}

interface ListResponse {
  data: TicketType[];
  total: number;
  page: number;
  limit: number;
}

const EMPTY_FORM = { name: '', price: '', quota: '', refundable: false, transferable: false, rules: '', eventId: '' };

export default function TicketTypesPage() {
  const [items, setItems] = useState<TicketType[]>([]);
  const [total, setTotal] = useState(0);
  const [page, setPage] = useState(1);
  const [limit] = useState(10);
  const [loading, setLoading] = useState(true);
  const [filterEventId, setFilterEventId] = useState('');
  const [showForm, setShowForm] = useState(false);
  const [editingId, setEditingId] = useState<string | null>(null);
  const [form, setForm] = useState(EMPTY_FORM);

  const loadData = useCallback(async () => {
    setLoading(true);
    try {
      const qs = buildQuery({
        page,
        limit,
        eventId: filterEventId || undefined,
      });
      const res = await fetchApi<ListResponse>(`/ticket-types${qs}`);
      setItems(res.data);
      setTotal(res.total);
    } catch (e) {
      console.error(e);
    } finally {
      setLoading(false);
    }
  }, [page, limit, filterEventId]);

  useEffect(() => {
    loadData();
  }, [loadData]);

  const totalPages = Math.ceil(total / limit);

  const openCreate = () => {
    setEditingId(null);
    setForm(EMPTY_FORM);
    setShowForm(true);
  };

  const openEdit = (item: TicketType) => {
    setEditingId(item.id);
    setForm({
      name: item.name,
      price: String(item.price),
      quota: String(item.quota),
      refundable: item.refundable,
      transferable: item.transferable,
      rules: item.rules || '',
      eventId: item.eventId || '',
    });
    setShowForm(true);
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    const payload = {
      name: form.name,
      price: Number(form.price),
      quota: Number(form.quota),
      refundable: form.refundable,
      transferable: form.transferable,
      rules: form.rules || undefined,
      eventId: form.eventId || undefined,
    };
    try {
      if (editingId) {
        await fetchApi(`/ticket-types/${editingId}`, { method: 'PUT', body: JSON.stringify(payload) });
      } else {
        await fetchApi('/ticket-types', { method: 'POST', body: JSON.stringify(payload) });
      }
      setShowForm(false);
      loadData();
    } catch (e) {
      console.error(e);
    }
  };

  const handleDelete = async (id: string) => {
    if (!confirm('确认删除该票种？')) return;
    try {
      await fetchApi(`/ticket-types/${id}`, { method: 'DELETE' });
      loadData();
    } catch (e) {
      console.error(e);
    }
  };

  const quotaPercent = (sold: number, quota: number) => {
    if (quota <= 0) return 0;
    return Math.min(100, Math.round((sold / quota) * 100));
  };

  const barColor = (percent: number) => {
    if (percent >= 90) return 'bg-red-500';
    if (percent >= 60) return 'bg-yellow-500';
    return 'bg-green-500';
  };

  return (
    <div>
      <div className="flex items-center justify-between mb-6">
        <h1 className="text-2xl font-bold">票种管理</h1>
        <button onClick={openCreate} className="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 text-sm">
          新增票种
        </button>
      </div>

      <div className="bg-white rounded-lg shadow p-4 mb-4 flex gap-4 items-end flex-wrap">
        <div>
          <label className="block text-xs text-gray-500 mb-1">活动ID</label>
          <input value={filterEventId} onChange={(e) => { setFilterEventId(e.target.value); setPage(1); }} placeholder="输入活动ID" className="border rounded px-3 py-1.5 text-sm" />
        </div>
      </div>

      <div className="bg-white rounded-lg shadow overflow-hidden">
        {loading ? (
          <div className="p-8 text-center text-gray-400">加载中...</div>
        ) : (
          <table className="w-full text-sm">
            <thead className="bg-gray-50 text-gray-600">
              <tr>
                <th className="px-4 py-3 text-left">名称</th>
                <th className="px-4 py-3 text-left">价格</th>
                <th className="px-4 py-3 text-left">配额</th>
                <th className="px-4 py-3 text-left min-w-[180px]">已售/配额</th>
                <th className="px-4 py-3 text-left">可退</th>
                <th className="px-4 py-3 text-left">可转</th>
                <th className="px-4 py-3 text-left">操作</th>
              </tr>
            </thead>
            <tbody className="divide-y">
              {items.map((item) => {
                const pct = quotaPercent(item.soldCount, item.quota);
                return (
                  <tr key={item.id} className="hover:bg-gray-50">
                    <td className="px-4 py-3 font-medium">{item.name}</td>
                    <td className="px-4 py-3">¥{Number(item.price).toFixed(2)}</td>
                    <td className="px-4 py-3">{item.quota}</td>
                    <td className="px-4 py-3">
                      <div className="flex items-center gap-2">
                        <div className="flex-1 bg-gray-200 rounded-full h-2">
                          <div className={`h-2 rounded-full ${barColor(pct)}`} style={{ width: `${pct}%` }} />
                        </div>
                        <span className="text-xs text-gray-600 whitespace-nowrap">{item.soldCount}/{item.quota} ({pct}%)</span>
                      </div>
                    </td>
                    <td className="px-4 py-3">
                      {item.refundable ? (
                        <span className="px-2 py-0.5 rounded text-xs bg-green-100 text-green-700">是</span>
                      ) : (
                        <span className="px-2 py-0.5 rounded text-xs bg-gray-100 text-gray-500">否</span>
                      )}
                    </td>
                    <td className="px-4 py-3">
                      {item.transferable ? (
                        <span className="px-2 py-0.5 rounded text-xs bg-green-100 text-green-700">是</span>
                      ) : (
                        <span className="px-2 py-0.5 rounded text-xs bg-gray-100 text-gray-500">否</span>
                      )}
                    </td>
                    <td className="px-4 py-3 space-x-2">
                      <button onClick={() => openEdit(item)} className="text-blue-600 hover:underline text-xs">编辑</button>
                      <button onClick={() => handleDelete(item.id)} className="text-red-600 hover:underline text-xs">删除</button>
                    </td>
                  </tr>
                );
              })}
              {items.length === 0 && (
                <tr><td colSpan={7} className="px-4 py-8 text-center text-gray-400">暂无数据</td></tr>
              )}
            </tbody>
          </table>
        )}
        <div className="flex items-center justify-between px-4 py-3 border-t text-sm text-gray-600">
          <span>共 {total} 条</span>
          <div className="flex gap-2">
            <button onClick={() => setPage((p) => Math.max(1, p - 1))} disabled={page <= 1} className="px-3 py-1 border rounded disabled:opacity-50">上一页</button>
            <span className="px-3 py-1">{page} / {totalPages || 1}</span>
            <button onClick={() => setPage((p) => Math.min(totalPages, p + 1))} disabled={page >= totalPages} className="px-3 py-1 border rounded disabled:opacity-50">下一页</button>
          </div>
        </div>
      </div>

      {showForm && (
        <div className="fixed inset-0 bg-black/40 flex items-center justify-center z-50">
          <div className="bg-white rounded-lg shadow-lg w-full max-w-md p-6">
            <h2 className="text-lg font-bold mb-4">{editingId ? '编辑票种' : '新增票种'}</h2>
            <form onSubmit={handleSubmit} className="space-y-4">
              <div>
                <label className="block text-sm font-medium mb-1">名称</label>
                <input value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} required className="w-full border rounded px-3 py-2 text-sm" />
              </div>
              <div>
                <label className="block text-sm font-medium mb-1">价格</label>
                <input type="number" step="0.01" min="0" value={form.price} onChange={(e) => setForm({ ...form, price: e.target.value })} required className="w-full border rounded px-3 py-2 text-sm" />
              </div>
              <div>
                <label className="block text-sm font-medium mb-1">配额</label>
                <input type="number" min="0" value={form.quota} onChange={(e) => setForm({ ...form, quota: e.target.value })} required className="w-full border rounded px-3 py-2 text-sm" />
              </div>
              <div className="flex gap-6">
                <label className="flex items-center gap-2 text-sm">
                  <input type="checkbox" checked={form.refundable} onChange={(e) => setForm({ ...form, refundable: e.target.checked })} className="rounded" />
                  可退票
                </label>
                <label className="flex items-center gap-2 text-sm">
                  <input type="checkbox" checked={form.transferable} onChange={(e) => setForm({ ...form, transferable: e.target.checked })} className="rounded" />
                  可转赠
                </label>
              </div>
              <div>
                <label className="block text-sm font-medium mb-1">规则 (JSON)</label>
                <textarea value={form.rules} onChange={(e) => setForm({ ...form, rules: e.target.value })} rows={3} placeholder='{"maxPerUser": 5}' className="w-full border rounded px-3 py-2 text-sm font-mono" />
              </div>
              <div>
                <label className="block text-sm font-medium mb-1">活动ID</label>
                <input value={form.eventId} onChange={(e) => setForm({ ...form, eventId: e.target.value })} className="w-full border rounded px-3 py-2 text-sm" />
              </div>
              <div className="flex justify-end gap-2">
                <button type="button" onClick={() => setShowForm(false)} className="px-4 py-2 border rounded text-sm hover:bg-gray-50">取消</button>
                <button type="submit" className="px-4 py-2 bg-blue-600 text-white rounded text-sm hover:bg-blue-700">保存</button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
}
