// frontend/src/components/common/DataTable.tsx
import { useMemo } from 'react'

export interface DataTableColumn<T = any> {
  key: string
  title: string
  render?: (row: T, index: number) => React.ReactNode
  width?: string | number
}

export interface DataTablePagination {
  currentPage: number
  pageSize: number
  total: number
  onPageChange: (page: number) => void
}

interface DataTableProps<T = any> {
  columns: DataTableColumn<T>[]
  data: T[]
  onRowClick?: (row: T, index: number) => void
  pagination?: DataTablePagination
  rowKey?: (row: T) => string | number
  emptyText?: string
}

export default function DataTable<T extends Record<string, any>>({
  columns,
  data,
  onRowClick,
  pagination,
  rowKey,
  emptyText = '暂无数据',
}: DataTableProps<T>) {
  const totalPages = useMemo(() => {
    if (!pagination) return 0
    return Math.max(1, Math.ceil(pagination.total / pagination.pageSize))
  }, [pagination])

  const renderCell = (column: DataTableColumn<T>, row: T, index: number) => {
    if (column.render) {
      return column.render(row, index)
    }
    return row[column.key] ?? '-'
  }

  const getRowKey = (row: T, index: number): string | number => {
    if (rowKey) {
      return rowKey(row)
    }
    if ('id' in row) {
      return row.id as string | number
    }
    return index
  }

  return (
    <div className="bg-white rounded-lg border border-gray-200 overflow-hidden">
      <div className="overflow-x-auto">
        <table className="w-full">
          <thead className="bg-gray-50">
            <tr>
              {columns.map((column) => (
                <th
                  key={column.key}
                  className="px-4 py-3 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider"
                  style={
                    column.width
                      ? { width: typeof column.width === 'number' ? `${column.width}px` : column.width }
                      : undefined
                  }
                >
                  {column.title}
                </th>
              ))}
            </tr>
          </thead>
          <tbody className="divide-y divide-gray-100">
            {data.length === 0 ? (
              <tr>
                <td
                  colSpan={columns.length}
                  className="px-4 py-12 text-center text-gray-400 text-sm"
                >
                  {emptyText}
                </td>
              </tr>
            ) : (
              data.map((row, index) => (
                <tr
                  key={getRowKey(row, index)}
                  className={
                    onRowClick
                      ? 'cursor-pointer hover:bg-blue-50 transition-colors'
                      : undefined
                  }
                  onClick={
                    onRowClick ? () => onRowClick(row, index) : undefined
                  }
                >
                  {columns.map((column) => (
                    <td
                      key={column.key}
                      className="px-4 py-3 text-sm text-gray-700"
                    >
                      {renderCell(column, row, index)}
                    </td>
                  ))}
                </tr>
              ))
            )}
          </tbody>
        </table>
      </div>

      {pagination && pagination.total > 0 && (
        <div className="flex items-center justify-between px-4 py-3 border-t border-gray-200 bg-gray-50">
          <div className="text-sm text-gray-600">
            共 <span className="font-medium">{pagination.total}</span> 条
          </div>
          <div className="flex items-center gap-2">
            <button
              onClick={() => pagination.onPageChange(pagination.currentPage - 1)}
              disabled={pagination.currentPage <= 1}
              className="px-3 py-1.5 text-sm border border-gray-300 rounded-md bg-white text-gray-700 hover:bg-gray-100 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
            >
              上一页
            </button>
            <div className="px-3 py-1.5 text-sm text-gray-600">
              <span className="font-medium">{pagination.currentPage}</span>
              <span className="mx-1">/</span>
              <span>{totalPages}</span>
            </div>
            <button
              onClick={() => pagination.onPageChange(pagination.currentPage + 1)}
              disabled={pagination.currentPage >= totalPages}
              className="px-3 py-1.5 text-sm border border-gray-300 rounded-md bg-white text-gray-700 hover:bg-gray-100 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
            >
              下一页
            </button>
          </div>
        </div>
      )}
    </div>
  )
}

// src/lib/components/DataTable.svelte
<script lang="ts">
	import { cn } from '$lib/utils/cn';
	import EmptyState from './EmptyState.svelte';
	import { Loader2 } from 'lucide-svelte';
	import type { ComponentType } from 'svelte';

	export interface Column<T = unknown> {
		key: keyof T | string;
		title: string;
		width?: string;
		className?: string;
		render?: (item: T, index: number) => string | number | null | undefined;
		component?: ComponentType;
		componentProps?: (item: T, index: number) => Record<string, unknown>;
	}

	type ItemType = unknown;

	export let columns: Column<ItemType>[] = [];
	export let data: ItemType[] = [];
	export let loading = false;
	export let emptyTitle = '暂无数据';
	export let emptyDescription = '';
	export let rowKey: string | undefined = undefined;
	export let className = '';
	export let onRowClick: ((item: ItemType, index: number) => void) | undefined = undefined;

	function handleRowClick(item: ItemType, index: number) {
		onRowClick?.(item, index);
	}

	function getKeyValue(item: ItemType, key: string): unknown {
		const keys = key.split('.');
		let value: unknown = item;
		for (const k of keys) {
			if (value && typeof value === 'object' && k in value) {
				value = (value as Record<string, unknown>)[k];
			} else {
				return undefined;
			}
		}
		return value;
	}

	function getCellContent(item: ItemType, column: Column<ItemType>, index: number): string | number | null | undefined {
		if (column.render) {
			return column.render(item, index);
		}
		const value = getKeyValue(item, column.key as string);
		if (value instanceof Date) {
			return value.toLocaleDateString('zh-CN');
		}
		return value as string | number | null | undefined;
	}

	function getRowKey(item: ItemType, index: number): string | number {
		if (!rowKey) return index;
		const value = getKeyValue(item, rowKey);
		return value !== undefined && value !== null ? String(value) : index;
	}
</script>

<div class={cn('card overflow-hidden', className)}>
	<div class="overflow-x-auto">
		<table class="w-full">
			<thead>
				<tr class="bg-gray-50 border-b border-gray-100">
					{#each columns as column}
						<th
							class={cn(
								'px-4 py-3 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider',
								column.className
							)}
							style={column.width ? `width: ${column.width}` : undefined}
						>
							{column.title}
						</th>
					{/each}
				</tr>
			</thead>
			<tbody class="divide-y divide-gray-100">
				{#if loading}
					<tr>
						<td colspan={columns.length || 1} class="px-4 py-16">
							<div class="flex flex-col items-center justify-center gap-3">
								<Loader2 class="w-8 h-8 text-primary-500 animate-spin" />
								<p class="text-sm text-gray-500">加载中...</p>
							</div>
						</td>
					</tr>
				{:else if data.length === 0}
					<tr>
						<td colspan={columns.length || 1} class="px-4 py-8">
							<EmptyState title={emptyTitle} description={emptyDescription} />
						</td>
					</tr>
				{:else}
					{#each data as item, index (getRowKey(item, index))}
						<tr
							class={cn(
								'transition-colors duration-150',
								onRowClick && 'hover:bg-primary-50 cursor-pointer'
							)}
							on:click={() => handleRowClick(item, index)}
						>
							{#each columns as column}
								<td class={cn('px-4 py-3 text-sm text-gray-700', column.className)}>
									{#if column.component}
										<svelte:component
											this={column.component}
											{...(column.componentProps ? column.componentProps(item, index) : { item, index })}
										/>
									{:else}
										{getCellContent(item, column, index)}
									{/if}
								</td>
							{/each}
						</tr>
					{/each}
				{/if}
			</tbody>
		</table>
	</div>
</div>
