// frontend/components/layout/Topbar.tsx
"use client";

import { useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import {
  Search,
  Bell,
  Menu,
  X,
  LogOut,
  User,
  ChevronDown,
} from "lucide-react";
import { useAuth } from "@/lib/context/AuthContext";
import { useApp } from "@/lib/context/AppContext";
import { Avatar } from "@/components/ui/Avatar";
import { Button } from "@/components/ui/Button";
import { ReminderBadge } from "@/components/ui/ReminderBadge";
import { USER_ROLE_LABELS } from "@/lib/constants";

export function Topbar() {
  const { user, logout } = useAuth();
  const { unreadRemindersCount, reminders, markAllRemindersAsRead } = useApp();
  const router = useRouter();
  const [showUserMenu, setShowUserMenu] = useState(false);
  const [showNotifications, setShowNotifications] = useState(false);
  const [showMobileMenu, setShowMobileMenu] = useState(false);

  const handleLogout = () => {
    logout();
    router.push("/login");
  };

  const latestReminders = reminders
    .filter((r) => !r.isRead)
    .slice(0, 5);

  return (
    <header className="sticky top-0 z-40 h-16 bg-white border-b border-gray-200">
      <div className="flex h-full items-center justify-between px-6">
        <div className="flex items-center gap-4">
          <button
            className="lg:hidden p-2 text-gray-600 hover:bg-gray-100 rounded-lg"
            onClick={() => setShowMobileMenu(!showMobileMenu)}
          >
            {showMobileMenu ? (
              <X className="h-5 w-5" />
            ) : (
              <Menu className="h-5 w-5" />
            )}
          </button>

          <div className="hidden md:flex items-center">
            <div className="relative">
              <Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-gray-400" />
              <input
                type="search"
                placeholder="搜索任务、项目..."
                className="w-80 pl-10 pr-4 py-2 border border-gray-300 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-primary-500 focus:border-transparent"
              />
            </div>
          </div>
        </div>

        <div className="flex items-center gap-3">
          <div className="relative">
            <button
              className="relative p-2 text-gray-600 hover:bg-gray-100 rounded-lg"
              onClick={() => setShowNotifications(!showNotifications)}
            >
              <ReminderBadge count={unreadRemindersCount} />
            </button>

            {showNotifications && (
              <div className="absolute right-0 mt-2 w-80 bg-white rounded-lg shadow-lg border border-gray-200 z-50">
                <div className="flex items-center justify-between px-4 py-3 border-b border-gray-200">
                  <h3 className="font-semibold text-gray-900">通知</h3>
                  {unreadRemindersCount > 0 && (
                    <button
                      className="text-xs text-primary-600 hover:underline"
                      onClick={markAllRemindersAsRead}
                    >
                      全部已读
                    </button>
                  )}
                </div>
                <div className="max-h-80 overflow-y-auto">
                  {latestReminders.length === 0 ? (
                    <div className="px-4 py-8 text-center text-gray-500">
                      暂无新通知
                    </div>
                  ) : (
                    latestReminders.map((reminder) => (
                      <Link
                        key={reminder.id}
                        href={`/reminders`}
                        className="block px-4 py-3 hover:bg-gray-50 border-b border-gray-100 last:border-b-0"
                        onClick={() => setShowNotifications(false)}
                      >
                        <p className="text-sm font-medium text-gray-900">
                          {reminder.title}
                        </p>
                        <p className="text-xs text-gray-500 mt-1 line-clamp-2">
                          {reminder.description}
                        </p>
                      </Link>
                    ))
                  )}
                </div>
                <div className="px-4 py-3 border-t border-gray-200">
                  <Link
                    href="/reminders"
                    className="text-sm text-primary-600 hover:underline"
                    onClick={() => setShowNotifications(false)}
                  >
                    查看全部
                  </Link>
                </div>
              </div>
            )}
          </div>

          {user && (
            <div className="relative">
              <button
                className="flex items-center gap-2 p-1.5 hover:bg-gray-100 rounded-lg"
                onClick={() => setShowUserMenu(!showUserMenu)}
              >
                <Avatar src={user.avatar} fallback={user.name} size="sm" />
                <div className="hidden sm:block text-left">
                  <p className="text-sm font-medium text-gray-900">
                    {user.name}
                  </p>
                  <p className="text-xs text-gray-500">
                    {USER_ROLE_LABELS[user.role]}
                  </p>
                </div>
                <ChevronDown className="h-4 w-4 text-gray-500" />
              </button>

              {showUserMenu && (
                <div className="absolute right-0 mt-2 w-56 bg-white rounded-lg shadow-lg border border-gray-200 z-50">
                  <div className="px-4 py-3 border-b border-gray-200">
                    <p className="text-sm font-medium text-gray-900">
                      {user.name}
                    </p>
                    <p className="text-xs text-gray-500">{user.email}</p>
                  </div>
                  <div className="py-1">
                    <button className="flex w-full items-center gap-3 px-4 py-2 text-sm text-gray-700 hover:bg-gray-100">
                      <User className="h-4 w-4" />
                      个人中心
                    </button>
                    <button
                      onClick={handleLogout}
                      className="flex w-full items-center gap-3 px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 text-danger-600"
                    >
                      <LogOut className="h-4 w-4" />
                      退出登录
                    </button>
                  </div>
                </div>
              )}
            </div>
          )}
        </div>
      </div>
    </header>
  );
}

// src/lib/components/layout/Topbar.svelte
<script lang="ts">
	import { page } from '$app/stores';
	import { cn } from '$lib/utils/cn';
	import { getRoleLabel } from '$lib/utils/enumLabels';
	import type { AuthUser } from '$lib/server/auth/lucia';
	import {
		ChevronRight,
		Search,
		Bell,
		Menu,
		User,
		LogOut,
		Settings as SettingsIcon,
		X
	} from 'lucide-svelte';
	import Badge from '$lib/components/ui/Badge.svelte';

	export let user: AuthUser | null = null;
	let className: string | undefined = undefined;
	export { className as class };
	export let searchOpen = false;
	export let searchQuery = '';

	import { createEventDispatcher } from 'svelte';
	const dispatch = createEventDispatcher<{
		toggleSidebar: void;
		logout: void;
		search: string;
	}>();

	type Crumb = { label: string; href?: string };

	$: breadcrumbs = getBreadcrumbs($page.url.pathname);

	function getBreadcrumbs(path: string): Crumb[] {
		const crumbs: Crumb[] = [{ label: '首页', href: '/' }];
		const segments = path.split('/').filter(Boolean);
		const map: Record<string, string> = {
			workorders: '工单管理',
			parts: '配件库存',
			quotes: '报价管理',
			inspection: '质检管理',
			exceptions: '异常处理',
			stats: '数据统计',
			users: '用户管理',
			settings: '系统设置'
		};
		let current = '';
		for (let i = 0; i < segments.length; i++) {
			current += '/' + segments[i];
			const label = map[segments[i]] ?? segments[i];
			if (i === segments.length - 1) {
				crumbs.push({ label });
			} else {
				crumbs.push({ label, href: current });
			}
		}
		return crumbs;
	}

	function handleSearchInput(e: Event) {
		const target = e.target as HTMLInputElement;
		dispatch('search', target.value);
	}

	function handleSearchFocus() {
		searchFocused = true;
		searchOpen = true;
	}

	function handleSearchBlur() {
		searchFocused = false;
		setTimeout(() => {
			searchOpen = false;
		}, 200);
	}

	function handleClearSearch() {
		searchQuery = '';
		dispatch('search', '');
	}

	let userMenuOpen = false;
	let searchFocused = false;
	let notifications = [
		{ id: 1, title: '新工单 WO-20240115-001', time: '5分钟前', unread: true },
		{ id: 2, title: '配件 A-100 库存低于安全线', time: '1小时前', unread: true },
		{ id: 3, title: '异常单 EX-001 已关闭', time: '2小时前', unread: false }
	];
	$: unreadCount = notifications.filter((n) => n.unread).length;
	let notifOpen = false;
</script>

<header class={cn(
	'h-16 flex-shrink-0 flex items-center gap-4 px-4 md:px-6',
	'bg-industrial-900/80 backdrop-blur-md border-b border-industrial-800',
	'sticky top-0 z-30',
	className
)}>
	<button
		type="button"
		on:click={() => dispatch('toggleSidebar')}
		class="md:hidden flex-shrink-0 w-10 h-10 rounded-lg flex items-center justify-center text-industrial-400 hover:text-white hover:bg-industrial-800 transition-colors"
		aria-label="切换菜单"
	>
		<Menu class="w-5 h-5" strokeWidth={2} />
	</button>

	<nav class="hidden md:flex items-center gap-1 flex-shrink-0 min-w-0">
		{#each breadcrumbs as crumb, index}
			{#if index > 0}
				<ChevronRight class="w-4 h-4 text-industrial-600 flex-shrink-0 mx-0.5" strokeWidth={2} />
			{/if}
			{#if crumb.href}
				<a
					href={crumb.href}
					class="text-sm text-industrial-400 hover:text-white transition-colors truncate max-w-[160px]"
				>
					{crumb.label}
				</a>
			{:else}
				<span class="text-sm font-medium text-white truncate max-w-[200px]">{crumb.label}</span>
			{/if}
		{/each}
	</nav>

	<div class="flex-1 max-w-xl mx-auto w-full">
		<div class={cn(
			'relative transition-all duration-300',
			searchFocused && 'md:scale-[1.02]'
		)}>
			<div class={cn(
				'flex items-center gap-2 h-10 rounded-lg bg-industrial-800 border transition-all duration-200',
				searchFocused
					? 'border-primary-500 ring-2 ring-primary-500/30'
					: 'border-industrial-700 hover:border-industrial-600'
			)}>
				<div class="pl-3.5 flex-shrink-0 text-industrial-500">
					<Search class="w-4 h-4" strokeWidth={2} />
				</div>
				<input
					type="text"
					bind:value={searchQuery}
					placeholder="搜索工单、客户、配件..."
					on:focus={handleSearchFocus}
					on:blur={handleSearchBlur}
					on:input={handleSearchInput}
					class="flex-1 w-full bg-transparent text-sm text-industrial-100 placeholder-industrial-500 focus:outline-none pr-3"
				/>
				{#if searchQuery}
					<button
						type="button"
						on:click={handleClearSearch}
						class="mr-2 p-1 rounded text-industrial-500 hover:text-industrial-200 hover:bg-industrial-700 transition-colors"
					>
						<X class="w-4 h-4" strokeWidth={2} />
					</button>
				{/if}
				<span class="hidden sm:flex mr-3 items-center gap-1 px-2 h-6 rounded text-[11px] font-medium text-industrial-500 border border-industrial-700 bg-industrial-900/50">
					⌘K
				</span>
			</div>
		</div>
	</div>

	<div class="flex items-center gap-1 flex-shrink-0">
		<div class="relative">
			<button
				type="button"
				on:click={() => { notifOpen = !notifOpen; userMenuOpen = false; }}
				class={cn(
					'relative w-10 h-10 rounded-lg flex items-center justify-center transition-all duration-200',
					notifOpen
						? 'bg-industrial-800 text-white'
						: 'text-industrial-400 hover:text-white hover:bg-industrial-800'
				)}
				aria-label="通知"
			>
				<Bell class="w-5 h-5" strokeWidth={2} />
				{#if unreadCount > 0}
					<span class="absolute top-2 right-2 min-w-[18px] h-[18px] px-1 rounded-full bg-accent-500 text-white text-[10px] font-bold flex items-center justify-center ring-2 ring-industrial-900">
						{unreadCount > 9 ? '9+' : unreadCount}
					</span>
				{/if}
			</button>

			{#if notifOpen}
				<div class="absolute right-0 mt-2 w-80 rounded-xl border border-industrial-700 bg-industrial-800 shadow-industrial-lg overflow-hidden animate-fade-in z-50">
					<div class="flex items-center justify-between px-4 py-3 border-b border-industrial-700">
						<h3 class="font-semibold text-white text-sm">通知中心</h3>
						{#if unreadCount > 0}
							<button class="text-xs text-primary-400 hover:text-primary-300 font-medium">
								全部已读
							</button>
						{/if}
					</div>
					<div class="max-h-80 overflow-y-auto">
						{#each notifications as notif}
							<div class={cn(
								'px-4 py-3 border-b border-industrial-700/60 last:border-b-0 transition-colors',
								notif.unread && 'bg-primary-600/5',
								'hover:bg-industrial-700/30 cursor-pointer'
							)}>
								<div class="flex items-start gap-3">
									<div class={cn(
										'w-2 h-2 mt-2 rounded-full flex-shrink-0',
										notif.unread ? 'bg-accent-500' : 'bg-transparent'
									)} />
									<div class="flex-1 min-w-0">
										<p class="text-sm text-industrial-100">{notif.title}</p>
										<p class="text-xs text-industrial-500 mt-0.5 font-numeric">{notif.time}</p>
									</div>
								</div>
							</div>
						{/each}
					</div>
					<div class="px-4 py-2.5 border-t border-industrial-700 bg-industrial-800/50">
						<a href="/notifications" class="block text-center text-xs text-primary-400 hover:text-primary-300 font-medium">
							查看全部通知
						</a>
					</div>
				</div>
			{/if}
		</div>

		<div class="relative">
			<button
				type="button"
				on:click={() => { userMenuOpen = !userMenuOpen; notifOpen = false; }}
				class={cn(
					'flex items-center gap-2 h-10 pl-1 pr-3 rounded-lg transition-all duration-200',
					userMenuOpen
						? 'bg-industrial-800'
						: 'hover:bg-industrial-800'
				)}
			>
				<div class="w-8 h-8 rounded-full bg-gradient-to-br from-accent-500 to-primary-500 flex items-center justify-center text-white text-xs font-semibold ring-2 ring-industrial-700/50">
					{user?.name?.charAt(0) ?? 'U'}
				</div>
				<div class="hidden sm:block text-left">
					<p class="text-sm font-medium text-white leading-tight">{user?.name ?? '用户'}</p>
					<p class="text-[11px] text-industrial-500 leading-tight">{user ? getRoleLabel(user.role) : ''}</p>
				</div>
			</button>

			{#if userMenuOpen}
				<div class="absolute right-0 mt-2 w-56 rounded-xl border border-industrial-700 bg-industrial-800 shadow-industrial-lg overflow-hidden animate-fade-in z-50">
					<div class="px-4 py-3 border-b border-industrial-700 bg-industrial-800/50">
						<p class="text-sm font-semibold text-white">{user?.name ?? '用户'}</p>
						<div class="flex items-center gap-2 mt-1">
							<Badge variant="primary" size="sm">{user ? getRoleLabel(user.role) : '未登录'}</Badge>
						</div>
					</div>
					<div class="py-1.5">
						<a
							href="/settings/profile"
							class="flex items-center gap-3 px-4 py-2.5 text-sm text-industrial-200 hover:bg-industrial-700/50 transition-colors"
							on:click={() => (userMenuOpen = false)}
						>
							<User class="w-4 h-4 text-industrial-400" strokeWidth={2} />
							个人资料
						</a>
						<a
							href="/settings"
							class="flex items-center gap-3 px-4 py-2.5 text-sm text-industrial-200 hover:bg-industrial-700/50 transition-colors"
							on:click={() => (userMenuOpen = false)}
						>
							<SettingsIcon class="w-4 h-4 text-industrial-400" strokeWidth={2} />
							系统设置
						</a>
					</div>
					<div class="py-1.5 border-t border-industrial-700">
						<button
							type="button"
							on:click={() => { userMenuOpen = false; dispatch('logout'); }}
							class="w-full flex items-center gap-3 px-4 py-2.5 text-sm text-danger-400 hover:bg-danger-500/10 transition-colors"
						>
							<LogOut class="w-4 h-4" strokeWidth={2} />
							退出登录
						</button>
					</div>
				</div>
			{/if}
		</div>
	</div>
</header>

{#if notifOpen || userMenuOpen}
	<div
		class="fixed inset-0 z-20"
		role="presentation"
		on:click={() => { notifOpen = false; userMenuOpen = false; }}
		on:keydown={(e) => {
			if (e.key === 'Escape' || e.key === ' ') {
				notifOpen = false;
				userMenuOpen = false;
			}
		}}
	/>
{/if}
