// src/lib/components/ui/Select.svelte
<script lang="ts">
	import { cn } from '$lib/utils/cn';
	import { ChevronDown } from 'lucide-svelte';

	type $$Props = Record<string, unknown>;

	export let value: string | number | undefined = undefined;
	export let placeholder = '请选择';
	export let disabled = false;
	export let error: string | undefined = undefined;
	export let id: string | undefined = undefined;
	let className: string | undefined = undefined;
	export { className as class };

	type Option = { value: string | number; label: string; disabled?: boolean };
	export let options: Option[] = [];
</script>

<div class="w-full">
	<div class="relative">
		<select
			{value}
			{disabled}
			{id}
			on:change
			on:focus
			on:blur
			class={cn(
				'w-full appearance-none rounded-lg border bg-industrial-900/50 text-sm text-industrial-100 transition-all duration-200 px-4 py-2.5 pr-10',
				error
					? 'border-danger-500/50 focus:border-danger-500 focus:ring-2 focus:ring-danger-500/30'
					: 'border-industrial-700 focus:border-primary-500 focus:ring-2 focus:ring-primary-500/30 focus:bg-industrial-900',
				disabled ? 'opacity-50 cursor-not-allowed' : 'hover:border-industrial-600',
				'focus:outline-none',
				className
			)}
			{...$$restProps}
		>
			{#if placeholder}
				<option value="" disabled selected={!value}>{placeholder}</option>
			{/if}
			{#each options as opt}
				<option value={opt.value} disabled={opt.disabled}>{opt.label}</option>
			{/each}
		</select>
		<div class="absolute inset-y-0 right-0 flex items-center pr-3 pointer-events-none text-industrial-400">
			<ChevronDown class="w-4 h-4" strokeWidth={2} />
		</div>
	</div>
	{#if error}
		<p class="mt-1.5 text-xs text-danger-400">{error}</p>
	{/if}
</div>

// src/components/ui/Select.tsx
import * as React from 'react';
import { cn } from '@/lib/utils';
import { ChevronDown } from 'lucide-react';

export interface SelectOption {
  value: string;
  label: string;
  disabled?: boolean;
}

export interface SelectProps extends React.SelectHTMLAttributes<HTMLSelectElement> {
  options: SelectOption[];
  placeholder?: string;
}

const Select = React.forwardRef<HTMLSelectElement, SelectProps>(
  ({ className, options, placeholder, children, ...props }, ref) => {
    return (
      <div className="relative">
        <select
          ref={ref}
          className={cn(
            'flex h-9 w-full items-center justify-between whitespace-nowrap rounded-md border border-input bg-transparent px-3 py-2 text-sm shadow-sm ring-offset-background placeholder:text-muted-foreground focus:outline-none focus:ring-1 focus:ring-ring disabled:cursor-not-allowed disabled:opacity-50 appearance-none cursor-pointer pr-10',
            className
          )}
          {...props}
        >
          {placeholder && (
            <option value="" disabled>
              {placeholder}
            </option>
          )}
          {options.map((option) => (
            <option
              key={option.value}
              value={option.value}
              disabled={option.disabled}
            >
              {option.label}
            </option>
          ))}
          {children}
        </select>
        <ChevronDown className="absolute right-3 top-1/2 -translate-y-1/2 h-4 w-4 opacity-50 pointer-events-none" />
      </div>
    );
  }
);
Select.displayName = 'Select';

export { Select };
