// src/lib/components/Timeline.svelte
<script lang="ts">
	import { cn } from '$lib/utils/cn';
	import { Check, Circle } from 'lucide-svelte';
	import type { ComponentType } from 'svelte';

	export interface TimelineItem {
		id: string;
		title: string;
		description?: string;
		time?: Date | string;
		status?: 'completed' | 'current' | 'pending';
		icon?: ComponentType;
		extra?: unknown;
	}

	export let items: TimelineItem[] = [];
	export let className = '';

	function formatTime(time: Date | string | undefined): string {
		if (!time) return '';
		const date = time instanceof Date ? time : new Date(time);
		return date.toLocaleString('zh-CN', {
			year: 'numeric',
			month: '2-digit',
			day: '2-digit',
			hour: '2-digit',
			minute: '2-digit'
		});
	}

	function getStatusColor(status: TimelineItem['status']): { dot: string; line: string; badge: string } {
		switch (status) {
			case 'completed':
				return {
					dot: 'bg-mint-500 border-mint-500',
					line: 'bg-mint-200',
					badge: 'bg-mint-50 text-mint-700 border-mint-200'
				};
			case 'current':
				return {
					dot: 'bg-primary-600 border-primary-600',
					line: 'bg-primary-200',
					badge: 'bg-primary-50 text-primary-700 border-primary-200'
				};
			case 'pending':
			default:
				return {
					dot: 'bg-white border-gray-300',
					line: 'bg-gray-200',
					badge: 'bg-gray-50 text-gray-500 border-gray-200'
				};
		}
	}

	function getStatusLabel(status: TimelineItem['status']): string {
		switch (status) {
			case 'completed':
				return '已完成';
			case 'current':
				return '进行中';
			case 'pending':
			default:
				return '待处理';
		}
	}
</script>

<ol class={cn('relative', className)}>
	{#each items as item, index}
		{@const colors = getStatusColor(item.status)}
		{@const isLast = index === items.length - 1}
		<li class="relative pl-10 pb-6">
			{#if !isLast}
				<span
					class={cn(
						'absolute left-[11px] top-6 w-0.5 bottom-0',
						colors.line
					)}
				/>
			{/if}

			<span
				class={cn(
					'absolute left-0 top-0 w-6 h-6 rounded-full border-2 flex items-center justify-center',
					colors.dot
				)}
			>
				{#if item.status === 'completed'}
					<Check class="w-3.5 h-3.5 text-white" strokeWidth={3} />
				{:else if item.status === 'current'}
					<span class="w-2 h-2 rounded-full bg-white" />
				{:else if item.icon}
					<svelte:component this={item.icon} class="w-3.5 h-3.5 text-gray-400" />
				{:else}
					<Circle class="w-2 h-2 text-gray-300" fill="currentColor" />
				{/if}
			</span>

			<div class="space-y-1.5">
				<div class="flex items-center gap-2 flex-wrap">
					<h4 class="text-sm font-semibold text-gray-800">{item.title}</h4>
					<span class={cn('badge border text-[11px]', colors.badge)}>
						{getStatusLabel(item.status)}
					</span>
				</div>
				{#if item.description}
					<p class="text-sm text-gray-600 leading-relaxed">{item.description}</p>
				{/if}
				{#if item.time}
					<p class="text-xs text-gray-400">{formatTime(item.time)}</p>
				{/if}
				{#if item.extra}
					<div class="pt-1">
						<slot name="extra" {item} {index} />
					</div>
				{/if}
			</div>
		</li>
	{/each}
</ol>

// apps/web/src/components/complaint/Timeline.tsx
'use client';

import dayjs from 'dayjs';
import { cn } from '@/lib/utils';
import type { ReactNode } from 'react';

export interface TimelineItem {
  id: string;
  title: string;
  description?: string;
  time: Date | string;
  icon?: ReactNode;
  color?: string;
}

interface TimelineProps {
  items: TimelineItem[];
  className?: string;
}

export default function Timeline({ items, className }: TimelineProps) {
  if (items.length === 0) {
    return (
      <div className="py-8 text-center text-slate-400 text-sm">
        暂无记录
      </div>
    );
  }

  return (
    <div className={cn('relative', className)}>
      <div className="absolute left-3 top-0 bottom-0 w-px bg-slate-200" />
      <div className="space-y-4">
        {items.map((item, index) => (
          <div key={item.id} className="relative pl-10">
            <div
              className={cn(
                'absolute left-0 w-6 h-6 rounded-full border-2 border-white flex items-center justify-center text-xs font-medium text-white shadow-sm',
                item.color ? `bg-[${item.color}]` : index === 0 ? 'bg-primary' : 'bg-slate-400'
              )}
              style={{ backgroundColor: item.color || (index === 0 ? '#1e3a5f' : '#94a3b8') }}
            >
              {item.icon || (
                <div className="w-2 h-2 rounded-full bg-white" />
              )}
            </div>
            <div className="py-0.5">
              <div className="flex items-center gap-2 mb-1">
                <h4 className="text-sm font-medium text-slate-800">
                  {item.title}
                </h4>
                <span className="text-xs text-slate-400">
                  {dayjs(item.time).format('YYYY-MM-DD HH:mm')}
                </span>
              </div>
              {item.description && (
                <p className="text-sm text-slate-600">{item.description}</p>
              )}
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
